/**
 * BidcoreAI · sitemap.js
 *
 * Turns the page registry built in server.js into the XML served at
 * /sitemap.xml. Nothing here knows what the pages are — server.js registers
 * every page through page(), and this file renders whatever that produced. Add
 * a page there and it appears here on the next boot; there is no second list to
 * remember.
 *
 * <lastmod> is read from git: one `git log` pass at first request gives the
 * date of the last commit that touched each file. File mtimes would have been
 * easier, but a deploy clones the repo and stamps every file with the clone
 * time, so every page would claim to have changed on every deploy — a signal
 * Google is documented to start ignoring once it stops matching reality. If git
 * is not available on the host (some serverless builds strip .git), lastmod is
 * left out entirely rather than guessed: a sitemap without lastmod is normal,
 * a sitemap with wrong lastmod is worse than none.
 */
const { execFileSync } = require('child_process');
const fs   = require('fs');
const path = require('path');

const SITE_URL = 'https://www.bidcoreai.com';

/* Last commit date per file, as YYYY-MM-DD.

   `git log --name-only` prints newest first, so the first time a path appears
   is the last time it changed — one process, one pass over history, rather than
   a `git log` per page. The @ prefix is what separates a date line from the
   file paths that follow it. */
function gitLastModified(root) {
  const dates = new Map();
  let out;
  try {
    out = execFileSync('git', ['log', '--pretty=format:@%cI', '--name-only'], {
      cwd: root,
      encoding: 'utf8',
      maxBuffer: 64 * 1024 * 1024,
      timeout: 20000,
      stdio: ['ignore', 'pipe', 'ignore'],
    });
  } catch {
    return dates;                       // no git, no history — caller omits lastmod
  }

  let current = null;
  for (const line of out.split('\n')) {
    const value = line.trim();
    if (!value) continue;
    if (value.startsWith('@')) {
      current = value.slice(1, 11);     // @2026-08-10T… → 2026-08-10
    } else if (current && !dates.has(value)) {
      dates.set(value, current);
    }
  }
  return dates;
}

/* A file git has never seen is either brand new or untracked; its mtime is the
   honest answer there, and the deploy-clone problem does not apply, because a
   file that is not in the repository is not in the clone either. */
function mtimeDate(root, relPath) {
  try {
    return fs.statSync(path.join(root, relPath)).mtime.toISOString().slice(0, 10);
  } catch {
    return null;
  }
}

const escapeXml = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

/**
 * @param {Array<{url:string, file:string, priority:number, changefreq:string}>} entries
 * @param {string} root  repository root, for resolving `file` and running git
 * @returns {string} the full sitemap XML document
 */
function buildSitemap(entries, root) {
  const gitDates = gitLastModified(root);
  const haveGit  = gitDates.size > 0;

  const urls = entries.map(({ url, file, priority, changefreq }) => {
    const relPath = path.posix.join('views', file);
    const lastmod = haveGit
      ? (gitDates.get(relPath) || mtimeDate(root, relPath))
      : null;

    return [
      '  <url>',
      `    <loc>${escapeXml(SITE_URL + url)}</loc>`,
      lastmod ? `    <lastmod>${lastmod}</lastmod>` : null,
      `    <changefreq>${changefreq}</changefreq>`,
      `    <priority>${priority.toFixed(1)}</priority>`,
      '  </url>',
    ].filter(Boolean).join('\n');
  });

  return `<?xml version="1.0" encoding="UTF-8"?>
<!--
  Generated by sitemap.js from the page registry in server.js. Do not hand-edit
  a copy of this: the URLs here are exactly the URLs the server serves, and they
  are rebuilt on every boot.

  Every URL uses the www host, because bidcoreai.com 301-redirects to
  www.bidcoreai.com. Listing the bare domain would point crawlers at a redirect
  and waste the signal.
-->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.join('\n')}
</urlset>
`;
}

module.exports = { buildSitemap, SITE_URL };
