/**
 * Bid management: bidding software, AI bidding software, federal bidding.
 *
 * These three sit downstream of the estimating pages — the estimate exists and
 * the question is now how the bid gets assembled, sent, compared and won. They
 * are deliberately written to different angles: the bidding page is about the
 * workflow, the AI page is about what the model does and where a person still
 * has to sign, and the federal page is about a procurement process the other
 * two never touch. They cross-link rather than compete.
 */
module.exports = [

/* ══════════════════ CONSTRUCTION BIDDING SOFTWARE ══════════════════ */
{
  slug: 'construction-bidding-software',
  name: 'Construction Bidding Software',
  h1: 'Construction Bidding Software for Packages, ITBs and Leveling',
  title: 'Construction Bidding Software for Contractors | BidcoreAI',
  description: 'Construction bidding software: build packages from the estimate, track ITBs and coverage, level subcontractor quotes and draft the proposal in one place.',
  keywords: 'construction bidding software, bidding software, bid management software, subcontractor bid software, bid leveling software, itb management software, contractor bidding software',
  eyebrow: 'Bid management',
  eyebrowIcon: 'ic-pkg',
  heroLead: 'Bidding software for general contractors, primes and subcontractors. Split a priced estimate into subcontractor packages, send ITBs with the right sheets attached, track coverage by trade, level the quotes that come back against the scope you actually sent, and draft the proposal from the estimate you priced.',
  pills: [
    { icon: 'ic-pkg',   text: 'Packages from the estimate' },
    { icon: 'ic-chart', text: 'Quote leveling' },
    { icon: 'ic-file',  text: 'Proposal from the bid' },
  ],
  card: {
    eyebrow: 'What bid day should look like',
    headline: 'Coverage you can see',
    sub: 'Which trades are covered, which quotes are comparable, and what nobody has bid',
    items: [
      'Bid packages generated from the priced estimate',
      'ITBs tracked by trade, with coverage visible',
      'Quotes levelled line against line, not total against total',
      'Inclusions, exclusions and gaps made explicit',
      'Proposal drafted from the numbers you actually carried',
    ],
  },
  intro: {
    eyebrow: 'What it is',
    h2: 'Bidding Is Where a Good Estimate Gets Lost',
    paras: [
      'Estimating and bidding are different problems. Estimating asks what the work costs. Bidding asks whether every scope item is covered by somebody, whether the quotes you received can be compared at all, and whether the number you submit reflects the scope you priced. Plenty of contractors lose money on jobs they estimated accurately, because a trade went uncovered, a low quote turned out to exclude half the scope, or an addendum landed on the Tuesday and never reached the four subs already holding the old drawings.',
      'BidcoreAI treats bidding as the second half of one workflow rather than as a separate product. The estimate you built is what generates the bid packages: scope, quantities, drawings and specification sections travel together, so a package sent to a drywall subcontractor contains the wall types, the finish schedule and the sheets those quantities came from, rather than a link to the whole set and a hope.',
      'Coverage is the number that matters on bid day, and it is the one most contractors track in a spreadsheet that is out of date by lunchtime. The platform tracks invitations by trade and package: who was invited, who confirmed, who is quoting, who declined and which packages have no bidder at all. That last group is the one that decides whether you submit with confidence or with a plug number.',
      'Leveling is where the actual judgement lives. Quotes rarely cover the same scope — one includes hoisting, another excludes it; one carries the specified product, another substituted; one covers the whole package, another priced two of its five sections. Comparing totals in that situation is meaningless. Leveling puts the quotes side by side against the scope you sent, shows what each included and left out, and produces a comparable number for each. The proposal is then drafted from the priced estimate itself, so the narrative, the inclusions and the number cannot drift apart between the spreadsheet and the letter.',
    ],
  },
  measures: {
    eyebrow: 'Coverage',
    icon: 'ic-pkg',
    h2: 'What the Bidding Workspace Handles',
    lead: 'From the moment the estimate is priced to the moment the proposal is submitted.',
    cards: [
      {
        icon: 'ic-pkg', title: 'Bid Packages',
        desc: 'Generated from the estimate, so scope, quantities and drawings travel together.',
        items: ['Packages by trade or division', 'Scope statements from the estimate', 'Relevant sheets and spec sections attached', 'Quantities included or withheld by choice'],
      },
      {
        icon: 'ic-send', title: 'Invitations to Bid',
        desc: 'Sent, tracked and chased, with a record of who has what version of the documents.',
        items: ['ITBs by package and bidder', 'Invited, confirmed, quoting, declined', 'Document version per bidder', 'Reminders and follow-up tracking'],
      },
      {
        icon: 'ic-chart', title: 'Coverage Tracking',
        desc: 'The question that actually decides bid day: what has no bidder on it.',
        items: ['Coverage by trade and package', 'Packages with no bidder flagged', 'Single-quote risk highlighted', 'Coverage over time as bid day approaches'],
      },
      {
        icon: 'ic-layers', title: 'Bid Leveling',
        desc: 'Quotes compared against the scope you sent rather than against each other\'s totals.',
        items: ['Line-against-line comparison', 'Inclusions and exclusions extracted', 'Substitutions and alternates flagged', 'Adjusted comparable number per bidder'],
      },
      {
        icon: 'ic-refresh', title: 'Addenda Distribution',
        desc: 'Because an addendum a subcontractor never saw is a quote for the wrong project.',
        items: ['Addenda logged against packages', 'Distribution recorded per bidder', 'Acknowledgement tracking', 'Requoting flagged where scope moved'],
      },
      {
        icon: 'ic-file', title: 'Proposal Assembly',
        desc: 'Drafted from the priced estimate, with the assumptions carried across intact.',
        items: ['Proposal drafted from the estimate', 'Inclusions, exclusions and allowances', 'Alternates and unit prices', 'Export to Word, PDF or Excel'],
      },
    ],
  },
  features: {
    eyebrow: 'Features',
    h2: 'Bidding Features',
    lead: 'Built for the week where the estimate is done and the bid still is not.',
    cards: [
      { icon: 'ic-pkg',    title: 'Package Generation', desc: 'Bid packages built from the priced estimate, carrying scope, quantities, drawings and the relevant specification sections.' },
      { icon: 'ic-send',   title: 'ITB Distribution', desc: 'Invitations sent per package with the correct document version recorded against each bidder.' },
      { icon: 'ic-chart',  title: 'Coverage Dashboard', desc: 'Live view of which trades are covered, which have a single quote and which have nobody bidding at all.' },
      { icon: 'ic-layers', title: 'Line-Level Leveling', desc: 'Quotes compared against the scope sent, not against each other, with an adjusted comparable figure per bidder.' },
      { icon: 'ic-brain',  title: 'Quote Reading', desc: 'Subcontractor quotes read for inclusions, exclusions, substitutions and alternates rather than retyped by an estimator.' },
      { icon: 'ic-refresh',title: 'Addendum Control', desc: 'Addenda logged, distributed and acknowledged per bidder, so nobody quotes a superseded set unknowingly.' },
      { icon: 'ic-shield', title: 'Risk and Compliance Review', desc: 'Contract clauses, liquidated damages, insurance limits and schedule risk extracted with page citations before you commit.' },
      { icon: 'ic-file',   title: 'Proposal Generation', desc: 'A proposal drafted from the estimate, in the structure the client or solicitation asked for.' },
      { icon: 'ic-tag',    title: 'Alternates and Unit Prices', desc: 'Alternates, allowances and unit price schedules carried through the estimate into the proposal without re-entry.' },
      { icon: 'ic-percent',title: 'Markup at Bid Time', desc: 'Fee, contingency and escalation adjusted at the last minute with the effect on the number visible immediately.' },
      { icon: 'ic-users',  title: 'Bid Day Collaboration', desc: 'Several people working the same bid — one levelling MEP, one chasing coverage — with a record of every change.' },
      { icon: 'ic-dl',     title: 'Excel Export', desc: 'Comparisons, coverage reports and the final bid exported to Excel or CSV for your own bid form.' },
    ],
  },
  csi: {
    eyebrow: 'Package structure',
    icon: 'ic-pkg',
    h2: 'Packages Structured the Way Subcontractors Bid',
    lead: 'Split by division, or by the trade boundaries your market actually uses.',
    rows: [
      { n: 'Division 02', l: 'Demolition and existing conditions' },
      { n: 'Division 03', l: 'Concrete — including forming and reinforcing' },
      { n: 'Division 04–05', l: 'Masonry and metals' },
      { n: 'Division 06–07', l: 'Carpentry, roofing and building envelope' },
      { n: 'Division 08–09', l: 'Openings and interior finishes' },
      { n: 'Division 21–23', l: 'Fire protection, plumbing and HVAC' },
      { n: 'Division 26–28', l: 'Electrical, communications and safety systems' },
      { n: 'Division 31–33', l: 'Earthwork, site improvements and utilities' },
      { n: 'Custom', l: 'Combined packages matched to how your subs sell' },
    ],
  },
  projectsLead: 'Hard bid, design-build, CM at risk and negotiated work — the coverage problem is the same in all of them.',
  workflow: {
    h2: 'From Priced Estimate to Submitted Bid',
    lead: 'Seven steps, and the estimate stays the single source of the number throughout.',
    steps: [
      { t: 'Start from the priced estimate', s: 'The estimate is already built in the same project, so scope, quantities and drawing references are available to package without re-entry.' },
      { t: 'Split into packages', s: 'Scope splits into subcontractor packages by division or by your own trade boundaries, each carrying its drawings, specification sections and scope statement.' },
      { t: 'Send the invitations', s: 'ITBs go out per package with the document version recorded against each bidder, and responses are tracked as invited, confirmed, quoting or declined.' },
      { t: 'Watch coverage', s: 'Coverage by trade updates as quotes arrive, with uncovered packages and single-quote trades flagged while there is still time to chase them.' },
      { t: 'Distribute addenda', s: 'Every addendum is logged against the affected packages, distributed to the bidders holding them and acknowledged, so nobody quotes a superseded set.' },
      { t: 'Level the quotes', s: 'Quotes are compared line against line to the scope you sent, with inclusions, exclusions, substitutions and alternates extracted and an adjusted comparable number produced.' },
      { t: 'Assemble and submit', s: 'Selected quotes flow back into the estimate, markup is set, and the proposal is drafted from the priced estimate with the assumptions carried across.' },
    ],
  },
  benefits: {
    eyebrow: 'Benefits',
    h2: 'What Changes on Bid Day',
    lead: 'The panic is usually about information, not about time.',
    cards: [
      { icon: 'ic-chart',  title: 'Coverage Stops Being a Guess', desc: 'Knowing at 9am which packages have no bidder is what turns bid day into a plan instead of a scramble for a plug number.' },
      { icon: 'ic-layers', title: 'Comparable Quotes', desc: 'A quote 18% below the others is either a bargain or a misread scope. Line-level leveling is the only thing that tells you which before you carry it.' },
      { icon: 'ic-refresh',title: 'No Superseded Quotes', desc: 'Tracking which bidder holds which addendum removes the failure where a sub prices last week\'s drawings and you find out after award.' },
      { icon: 'ic-file',   title: 'Proposal Matches the Number', desc: 'Drafting the proposal from the priced estimate is what stops the narrative and the bid form disagreeing about what was included.' },
      { icon: 'ic-shield', title: 'Risk Read Before You Commit', desc: 'Liquidated damages, insurance limits and schedule terms extracted with citations gives you a position on risk rather than a discovery after signing.' },
      { icon: 'ic-users',  title: 'A Record That Survives', desc: 'Who was invited, what they were sent, what they said and what you carried — recorded, and still there when the job is being argued about in month seven.' },
    ],
  },
  why: {
    h2: 'Why Contractors Bid in BidcoreAI',
    lead: 'Because the bid and the estimate are the same project, not two exports.',
    items: [
      { icon: 'ic-pkg',    t: 'Packages from real scope', s: 'Built from the estimate, carrying quantities, drawings and spec sections rather than a link to the full set.' },
      { icon: 'ic-chart',  t: 'Coverage in front of you', s: 'Uncovered trades and single-quote risk visible while there is still time to do something about them.' },
      { icon: 'ic-layers', t: 'Leveling that reads the quote', s: 'Inclusions and exclusions extracted from the document rather than retyped by whoever opened the email.' },
      { icon: 'ic-flag',   t: 'Federal work supported', s: 'Solicitation-driven bidding is built in too — see <a href="/software/federal-bidding-software">federal bidding software</a>.' },
      { icon: 'ic-cloud',  t: 'Browser-based', s: 'Bid day works from anywhere, with several people in the same bid at once.' },
      { icon: 'ic-users',  t: 'Estimators available', s: 'When the estimate itself is the bottleneck, <a href="/construction-estimating-services">estimating services</a> run in this same platform.' },
    ],
  },
  faqs: [
    { q: 'What is construction bidding software?', a: 'Construction bidding software manages everything between a finished estimate and a submitted bid: splitting scope into subcontractor packages, sending and tracking invitations to bid, monitoring coverage by trade, levelling the quotes that come back, distributing addenda and assembling the proposal. It is a different problem from estimating, which is why contractors with accurate estimates still lose money on bids.' },
    { q: 'How is bidding software different from estimating software?', a: 'Estimating asks what the work costs. Bidding asks whether every scope item is covered by a bidder, whether the quotes received can be compared at all, and whether the submitted number reflects the scope that was priced. BidcoreAI does both in one project, so the estimate is what generates the packages and the proposal — see <a href="/software/construction-estimating-software">construction estimating software</a> for the pricing side.' },
    { q: 'What is bid leveling?', a: 'Bid leveling is adjusting quotes so they can be compared. Subcontractor quotes rarely cover identical scope — one includes hoisting, another excludes it; one carries the specified product, another substituted; one priced three of the package\'s five sections. Leveling compares each quote line against the scope that was sent, extracts what was included and excluded, and produces a comparable adjusted number for each bidder.' },
    { q: 'Does it track which subcontractors have which drawings?', a: 'Yes. Document versions are recorded per bidder, and every addendum is logged against the affected packages, distributed and acknowledged. A subcontractor quoting a superseded set is one of the more expensive failures in bidding, and it is almost entirely an administrative problem.' },
    { q: 'Can it show me which trades have no coverage?', a: 'Yes, and it is the point of the coverage view. Packages with no bidder, trades with only one quote and packages where everyone declined are flagged as bid day approaches, while there is still time to chase or to price the scope yourself.' },
    { q: 'Does it read subcontractor quotes automatically?', a: 'It reads them for inclusions, exclusions, substitutions, alternates and scope coverage, and presents what it found for confirmation. An estimator reviews the extraction before it feeds the comparison — a misread exclusion is exactly the kind of error that should not be automated away silently.' },
    { q: 'Can it generate the proposal?', a: 'Yes, drafted from the priced estimate so the narrative, the inclusions and the number cannot drift apart. Alternates, allowances and unit price schedules carry across without re-entry, and the output exports to Word, PDF or Excel.' },
    { q: 'Does it work for subcontractors bidding to general contractors?', a: 'Yes. A subcontractor uses the same workspace to price trade scope quickly across many invitations, track which GCs they are bidding to, manage the versions each one issued, and produce a proposal with the inclusions and exclusions written down — which is what makes their quote survive somebody else\'s levelling.' },
    { q: 'Is contract risk reviewed as part of bidding?', a: 'Yes. The <a href="/ai-risk-compliance-analyser">risk and compliance analyser</a> extracts liquidated damages, insurance and bonding limits, schedule terms and unusual clauses with page citations, so risk is a position you take at bid time rather than a discovery after signing.' },
    { q: 'Can several people work the same bid at once?', a: 'Yes. One person levelling MEP quotes while another chases coverage on finishes is the normal state of a bid day, and the platform records who changed which number and when — which matters when the bid is reconstructed months later.' },
  ],
  service: {
    h2: 'Estimating Support Behind the Bid',
    body: 'Bidding software fixes the assembly problem. It does not price a package nobody had time to estimate. When the estimate itself is the constraint, estimators working in this same platform will measure and price the scope and hand it straight into your bid — typically in 24 to 72 hours.',
    href: '/construction-estimating-services',
    label: 'Construction Estimating Services',
  },
  related: [
    'ai-bidding-software',
    'federal-bidding-software',
    'construction-estimating-software',
    'construction-takeoff-software',
    'quantity-takeoff-software',
    'concrete-estimating-software',
    'electrical-estimating-software',
    'drywall-estimating-software',
  ],
  cta: {
    h2: 'Run a Bid Day You Have Already Survived',
    lead: 'Bring the quotes from a bid you submitted. Levelling them line against line is usually the moment it becomes obvious.',
  },
},

/* ══════════════════ AI BIDDING SOFTWARE ══════════════════ */
{
  slug: 'ai-bidding-software',
  name: 'AI Bidding Software',
  h1: 'AI Bidding Software That Shows You Where Every Number Came From',
  title: 'AI Bidding Software for Construction | BidcoreAI',
  description: 'AI bidding software for contractors: AI reads the documents, measures the drawings, prices the scope and drafts the proposal — with a citation on every item.',
  keywords: 'ai bidding software, ai construction bidding, artificial intelligence bidding software, ai bid management, ai proposal software construction, automated bidding software',
  eyebrow: 'AI for bidding',
  eyebrowIcon: 'ic-brain',
  heroLead: 'AI bidding software for construction. The AI reads the specification, finds the scope, measures the drawings, prices against your cost data, reads the quotes that come back and drafts the proposal — and every item it produces cites the page it came from, so an estimator reviews the work instead of trusting it.',
  pills: [
    { icon: 'ic-brain', text: 'Cited, not asserted' },
    { icon: 'ic-check', text: 'Human sign-off' },
    { icon: 'ic-db',    text: 'Your data, your costs' },
  ],
  card: {
    eyebrow: 'How the AI is used here',
    headline: 'Proposals, not pronouncements',
    sub: 'Everything the model produces is presented for confirmation with its evidence attached',
    items: [
      'Scope extracted with a page citation per item',
      'Quantities proposed on the sheet you can see',
      'Pricing from your cost database, not a model guess',
      'Quotes read for inclusions and exclusions',
      'Proposal drafted from numbers you approved',
    ],
  },
  intro: {
    eyebrow: 'What it is',
    h2: 'What AI Is Genuinely Good At in a Bid — and What It Is Not',
    paras: [
      'There are two ways to build AI into bidding. One is to ask a model for a number and put it in the bid. The other is to use AI for the work that is slow, repetitive and mechanical — reading four hundred pages of specification, finding every instance of a symbol across a plan set, extracting what a subcontractor\'s quote excluded — and to leave the judgement to the estimator. The first approach demonstrates well and cannot be defended in a scope meeting. BidcoreAI is built on the second.',
      'Concretely: the AI reads the specification book and drawing set and returns the scope it found, each item citing the section or sheet it came from. It measures the drawings and proposes quantities, each shown on the sheet at the scale it was measured. It reads incoming subcontractor quotes and extracts inclusions, exclusions, substitutions and alternates. It drafts the proposal from the estimate that was actually priced. At every one of those steps a person confirms, corrects or rejects the output before it moves downstream.',
      'The pricing itself is deliberately not a model output. Costs come from your own historical unit rates, or a regional benchmark where you have no history — a database lookup, not a prediction. This matters because an invented price is indistinguishable from a real one until the job is running, and because your own costs are more predictive of your costs than any model trained on somebody else\'s.',
      'What this buys is speed with an audit trail. The slow parts of a bid — reading, measuring, comparing — compress dramatically. The parts that require judgement, and the parts you will have to defend later, stay with the estimator and stay traceable. That is a narrower claim than "AI writes your bid", and it is the one that holds up when a number is challenged six months after award.',
    ],
  },
  measures: {
    eyebrow: 'Where AI is applied',
    icon: 'ic-brain',
    h2: 'The Five Places AI Does Real Work',
    lead: 'Each one is a task that is mechanical, verifiable and enormously time-consuming by hand.',
    cards: [
      {
        icon: 'ic-file', title: 'Reading the Documents',
        desc: 'Specification books, drawings and addenda read end to end, with scope returned as a checkable list.',
        items: ['Scope items with page citations', 'Every specification section covered', 'Addenda differences identified', 'Requirements you would skim past'],
      },
      {
        icon: 'ic-scan', title: 'Measuring the Drawings',
        desc: 'Repeating conditions found and measured across the whole set, then presented for review.',
        items: ['Symbols counted across every sheet', 'Wall types, areas and runs measured', 'Each quantity shown on its sheet', 'Nothing priced until confirmed'],
      },
      {
        icon: 'ic-shield', title: 'Finding the Risk',
        desc: 'Contract and specification terms that change what a job is worth, extracted with citations.',
        items: ['Liquidated damages and schedule terms', 'Insurance, bonding and indemnity limits', 'Unusual or onerous clauses flagged', 'Page reference on every finding'],
      },
      {
        icon: 'ic-layers', title: 'Reading the Quotes',
        desc: 'Subcontractor quotes parsed for what they actually cover, which is rarely what the total suggests.',
        items: ['Inclusions and exclusions extracted', 'Substitutions and alternates identified', 'Scope gaps against the package sent', 'Comparable numbers for levelling'],
      },
      {
        icon: 'ic-send', title: 'Drafting the Proposal',
        desc: 'Written from the priced estimate, in the structure the client or solicitation requires.',
        items: ['Drafted from approved numbers', 'Assumptions and exclusions carried across', 'Evaluation-criteria structure supported', 'Edited by you before it goes out'],
      },
      {
        icon: 'ic-check', title: 'Human Review at Every Step',
        desc: 'The part that makes the rest defensible, and the part most AI demos leave out.',
        items: ['Confirm, correct or reject each item', 'Evidence attached to every proposal', 'Change history by person', 'Nothing moves downstream unreviewed'],
      },
    ],
  },
  features: {
    eyebrow: 'Features',
    h2: 'AI Features, and What Each One Actually Does',
    lead: 'Stated as specifically as possible, because vagueness is how AI claims usually get made.',
    cards: [
      { icon: 'ic-brain',  title: 'Document Analysis', desc: 'The full specification and drawing set read, with scope returned as a list where every item cites its page.' },
      { icon: 'ic-scan',   title: 'Quantity Proposals', desc: 'Measurements proposed across the set and displayed on the drawing, at the scale used, for confirmation.' },
      { icon: 'ic-sched',  title: 'Schedule Extraction', desc: 'Door, fixture, equipment, finish and bar schedules parsed into structured data and reconciled against the plans.' },
      { icon: 'ic-refresh',title: 'Addendum Comparison', desc: 'A re-issued set compared against the previous one, with the differences listed rather than left to be spotted.' },
      { icon: 'ic-shield', title: 'Risk Extraction', desc: 'Clause-level contract and compliance risk pulled out with citations, so the review is checking rather than reading.' },
      { icon: 'ic-layers', title: 'Quote Parsing', desc: 'Incoming subcontractor quotes read for inclusions, exclusions, substitutions and coverage against the package sent.' },
      { icon: 'ic-file',   title: 'Proposal Drafting', desc: 'A first draft written from the priced estimate in the required structure, which you then edit rather than write.' },
      { icon: 'ic-db',     title: 'Pricing From Your Data', desc: 'Costs looked up in your database, never generated. An invented price is the one output that cannot be reviewed.' },
      { icon: 'ic-check',  title: 'Review Workflow', desc: 'Every AI output has a confirm, correct or reject step, recorded against the person who made it.' },
      { icon: 'ic-report', title: 'Citations Throughout', desc: 'Sheet, section and page references carried from extraction all the way into the Excel export.' },
      { icon: 'ic-users',  title: 'Team Oversight', desc: 'A second estimator can review AI-proposed quantities before they are priced, with the changes recorded.' },
      { icon: 'ic-lock',   title: 'Your Project Data', desc: 'Your drawings, costs and estimates are your data. Cost history is used to price your jobs, not to train a public model.' },
    ],
  },
  csi: {
    eyebrow: 'Documents it reads',
    icon: 'ic-file',
    h2: 'What the AI Reads on a Typical Bid',
    lead: 'The reading list an estimator is supposed to get through in the week before a bid is due.',
    rows: [
      { n: 'Drawings', l: 'Architectural, structural, MEP and civil plan sets' },
      { n: 'Specifications', l: 'Full MasterFormat specification books, section by section' },
      { n: 'Schedules', l: 'Door, window, finish, fixture, equipment and bar schedules' },
      { n: 'Addenda', l: 'Every issue, compared against the set it supersedes' },
      { n: 'Contracts', l: 'Agreement forms, general and supplementary conditions' },
      { n: 'Quotes', l: 'Subcontractor and supplier quotes, for scope and exclusions' },
      { n: 'Solicitations', l: 'Federal solicitations, SOWs and evaluation criteria' },
      { n: 'Geotech', l: 'Soils reports and existing conditions surveys' },
      { n: 'Bid forms', l: 'Bid forms, unit price schedules and alternates' },
    ],
  },
  projectsLead: 'The document load is what scales with project size — and it is exactly the part AI removes.',
  workflow: {
    h2: 'How an AI-Assisted Bid Runs',
    lead: 'Every step produces something a person then checks.',
    steps: [
      { t: 'Upload everything', s: 'Drawings, specifications, addenda, contract documents and bid forms. The AI reads all of it rather than the parts somebody had time for.' },
      { t: 'Scope returned with citations', s: 'The scope it found comes back as a list, each item referencing the sheet or specification section, so review means checking a claim rather than re-reading a book.' },
      { t: 'Quantities proposed', s: 'Measurements are proposed across the set and shown on the drawings at the scale used. The estimator confirms, corrects or adds what only a person would catch.' },
      { t: 'Risk surfaced', s: 'Liquidated damages, insurance limits, schedule terms and onerous clauses are extracted with page references before any commitment is made.' },
      { t: 'Priced from your database', s: 'Confirmed quantities are priced against your own unit costs — a lookup, not a prediction — with material, labor and equipment separated.' },
      { t: 'Quotes read and levelled', s: 'Incoming subcontractor quotes are parsed for inclusions, exclusions and coverage, and levelled against the package that was sent.' },
      { t: 'Proposal drafted, then edited', s: 'A draft proposal is written from the approved estimate in the required structure. You edit it. The AI does not send anything.' },
    ],
  },
  benefits: {
    eyebrow: 'Benefits',
    h2: 'What AI Changes, Stated Honestly',
    lead: 'Large gains in the mechanical work, no change in who is accountable for the number.',
    cards: [
      { icon: 'ic-zap',     title: 'The Reading Stops Being the Constraint', desc: 'A specification book that takes two days to read properly is read in full every time, including on the bids where nobody would otherwise have had the hours.' },
      { icon: 'ic-scan',    title: 'Measuring Becomes Reviewing', desc: 'Confirming a proposed quantity on the sheet is faster and more accurate than producing it from scratch at eleven at night.' },
      { icon: 'ic-check',   title: 'Defensible Six Months Later', desc: 'Citations on every scope item and sheet references on every quantity mean a challenged number can be shown rather than argued.' },
      { icon: 'ic-shield',  title: 'Risk Read Every Time', desc: 'Contract review that used to happen only on the big pursuits happens on all of them, because it costs minutes rather than an afternoon.' },
      { icon: 'ic-trending',title: 'More Pursuits per Estimator', desc: 'The binding constraint is estimator hours. Compressing the mechanical work is what turns three properly bid jobs a week into eight.' },
      { icon: 'ic-db',      title: 'No Invented Numbers', desc: 'Pricing stays a database lookup. It is the one place where an AI answer would be unverifiable, so it is the one place AI is not used.' },
    ],
  },
  why: {
    h2: 'Why This Approach to AI',
    lead: 'Because a bid is a commitment, and commitments have to be checkable.',
    items: [
      { icon: 'ic-report', t: 'Citations, always', s: 'Every extracted scope item and every measurement carries the page or sheet it came from, right through to the export.' },
      { icon: 'ic-check',  t: 'A person signs off', s: 'Confirm, correct or reject at every step. Nothing reaches a price without somebody accepting it.' },
      { icon: 'ic-db',     t: 'Costs are looked up', s: 'Pricing comes from your database rather than from a model, because a generated price cannot be reviewed.' },
      { icon: 'ic-lock',   t: 'Your data stays yours', s: 'Your drawings, costs and estimates are used to run your projects, not to train a public model.' },
      { icon: 'ic-flag',   t: 'Federal work included', s: 'Solicitations, FAR-aware risk review and evaluation-criteria proposals — see <a href="/software/federal-bidding-software">federal bidding software</a>.' },
      { icon: 'ic-users',  t: 'People still available', s: 'Where you want finished work rather than assistance, <a href="/construction-estimating-services">estimating services</a> run in this same platform.' },
    ],
  },
  faqs: [
    { q: 'What is AI bidding software?', a: 'AI bidding software applies machine reading and measurement to the mechanical parts of a bid: reading specifications and drawings, extracting scope, measuring quantities, parsing subcontractor quotes and drafting proposals. In BidcoreAI every one of those outputs is presented with the page or sheet it came from and confirmed by an estimator before it moves downstream.' },
    { q: 'Does the AI decide the price?', a: 'No, deliberately. Pricing is a lookup in your own cost database, or a regional benchmark where you have no history — never a model prediction. An invented price is indistinguishable from a real one until the job is running, which makes it the one output that cannot be reviewed, so it is the one place AI is not used.' },
    { q: 'How accurate is AI takeoff and scope extraction?', a: 'Consistently strong on repeating, clearly drawn conditions and on text that is present in the documents. Weaker on scope that is implied by a detail, a note or trade convention rather than stated. That is precisely why every proposal is reviewed on the drawing or against the specification before it is priced — the AI compresses the work, it does not own the result.' },
    { q: 'How do I check what the AI produced?', a: 'Every scope item cites its specification section or sheet, and every quantity is displayed on the drawing at the scale it was measured. Review is therefore checking a claim against its source rather than reproducing the work, which is both faster and more reliable than doing it from scratch.' },
    { q: 'Can AI write my proposal?', a: 'It writes a first draft from the estimate you approved, following the structure the client or solicitation requires, with the assumptions and exclusions carried across. You edit it before it goes anywhere. Nothing is submitted automatically.' },
    { q: 'Does it read subcontractor quotes?', a: 'Yes — for inclusions, exclusions, substitutions, alternates and coverage against the package you sent. The extraction is confirmed by an estimator before it feeds a comparison, because a misread exclusion is exactly the error that must not be automated away quietly.' },
    { q: 'What happens to my drawings and cost data?', a: 'They stay your data. Your cost history is used to price your projects, not to train a public model, and your project documents remain within your account.' },
    { q: 'Will AI replace my estimators?', a: 'No. It removes the reading, counting and comparing, which is where most estimating hours currently go, and leaves the judgement calls — scope interpretation, productivity, risk, what to carry and what to exclude — with the people accountable for the number. The practical effect is more pursuits per estimator rather than fewer estimators.' },
    { q: 'How is this different from ordinary bidding software?', a: 'The workflow is the same as <a href="/software/construction-bidding-software">construction bidding software</a> — packages, ITBs, coverage, levelling, proposals. The difference is that the reading, measuring and quote-parsing inside that workflow are done by AI and reviewed by a person, rather than done by a person from a blank page.' },
    { q: 'Does it work for federal bids?', a: 'Yes, and the document load there is larger, so the gain is bigger. Solicitations, statements of work, FAR clauses and evaluation criteria are all read the same way. See <a href="/software/federal-bidding-software">federal bidding software</a> and the free <a href="/go-no-go">Go/No-Go Analyzer</a>.' },
  ],
  service: {
    h2: 'Or Have People Do It, in the Same Platform',
    body: 'AI assistance changes what one estimator can cover. It does not help on a week where the capacity simply is not there. Estimators working in this same platform will measure and price a package for you and hand it straight into your bid, typically within 24 to 72 hours.',
    href: '/quantity-takeoff-estimating-services',
    label: 'Takeoff &amp; Estimating Services',
  },
  related: [
    'construction-bidding-software',
    'federal-bidding-software',
    'construction-estimating-software',
    'construction-takeoff-software',
    'quantity-takeoff-software',
    'electrical-estimating-software',
    'hvac-estimating-software',
    'concrete-estimating-software',
  ],
  cta: {
    h2: 'Point It at a Bid You Already Know',
    lead: 'Bring a set you have priced. The useful question is not whether it is fast — it is what it found that you did not.',
  },
},

/* ══════════════════ FEDERAL BIDDING SOFTWARE ══════════════════ */
{
  slug: 'federal-bidding-software',
  name: 'Federal Bidding Software',
  h1: 'Federal Bidding Software for SAM.gov Solicitations and Proposals',
  title: 'Federal Bidding Software for Contractors | BidcoreAI',
  description: 'Federal construction bidding software: qualify SAM.gov opportunities, read solicitations and FAR clauses, price the work and write to the evaluation criteria.',
  keywords: 'federal bidding software, government bidding software, sam.gov software, federal construction estimating software, far compliance software, government proposal software',
  eyebrow: 'Federal contracting',
  eyebrowIcon: 'ic-flag',
  heroLead: 'Federal bidding software for construction contractors. Qualify SAM.gov opportunities before you spend a week on them, read the solicitation and its FAR clauses with citations, price the work against your own cost data, and write a proposal that answers the evaluation criteria in the order they are written.',
  pills: [
    { icon: 'ic-check',  text: 'Free Go/No-Go Analyzer' },
    { icon: 'ic-shield', text: 'FAR-aware risk review' },
    { icon: 'ic-file',   text: 'Evaluation-criteria proposals' },
  ],
  card: {
    eyebrow: 'The federal problem',
    headline: 'Qualify before you commit',
    sub: 'A federal pursuit costs a week. Deciding not to bid is the highest-return decision you make',
    items: [
      'Twelve-criterion Go/No-Go scoring, free to use',
      'Set-aside, NAICS and size standard checked',
      'Bonding capacity against contract value',
      'Wage determination and compliance load surfaced',
      'Evaluation criteria extracted before you write',
    ],
  },
  intro: {
    eyebrow: 'What it is',
    h2: 'Federal Bidding Is a Different Sport',
    paras: [
      'A commercial hard bid asks one question: what is your number. A federal solicitation asks a hundred, and getting any of them wrong can make the rest irrelevant. Is the work set aside for a socioeconomic category you hold? Is your NAICS code and size standard right? Can you bond it? Have you registered in SAM and is the registration current? Did you acknowledge every amendment? Does your proposal answer Section M in the order Section M asks, or does it answer the questions you wished had been asked?',
      'BidcoreAI treats that as a qualification problem before it treats it as an estimating problem. The free <a href="/go-no-go">Go/No-Go Analyzer</a> — connect your own SAM.gov API key and it costs nothing — scores an opportunity across twelve criteria: set-aside match, NAICS and size standard, contract value against your bonding capacity, geography, past performance relevance, competition profile, schedule feasibility and the compliance load the solicitation carries. Pursuing the wrong federal job costs a week of estimator time and the pursuit you did not make instead, so a fast, honest no is worth more than most tools sold on their yes.',
      'For the opportunities you do pursue, the platform reads the solicitation the way it reads any other document set — completely, with citations. Statement of work, drawings, specifications, wage determinations, FAR and agency-supplement clauses, and the evaluation criteria in Sections L and M. Liquidated damages, insurance and bonding requirements, schedule constraints and unusual clauses come out with page references, so your risk position is written down before you commit rather than discovered at award.',
      'Estimating and bidding then run as they do for any project: quantities measured off the drawings, priced against your own cost data, packaged to subcontractors, levelled. What is different is the output. A federal proposal is graded against stated criteria by evaluators who read many of them, and the proposal generator drafts to that structure — answering the criteria in order, carrying the assumptions from the priced estimate, and keeping the technical narrative and the price consistent with each other.',
    ],
  },
  measures: {
    eyebrow: 'Coverage',
    icon: 'ic-flag',
    h2: 'What the Platform Handles on a Federal Pursuit',
    lead: 'From an opportunity notice you have not read yet to a submitted proposal.',
    cards: [
      {
        icon: 'ic-check', title: 'Go/No-Go Qualification',
        desc: 'A twelve-criterion score on an opportunity, free, before any estimating time is spent.',
        items: ['Set-aside and socioeconomic match', 'NAICS code and size standard', 'Value against bonding capacity', 'Geography, competition and schedule'],
      },
      {
        icon: 'ic-scan', title: 'Solicitation Reading',
        desc: 'The whole package read, not the parts there was time for.',
        items: ['Statement of work and specifications', 'Sections L and M evaluation criteria', 'Amendments and their differences', 'Submission requirements and deadlines'],
      },
      {
        icon: 'ic-shield', title: 'FAR and Compliance Risk',
        desc: 'Clause-level review with citations, because the clauses are the contract.',
        items: ['FAR and agency supplement clauses', 'Liquidated damages and schedule terms', 'Bonding, insurance and indemnity', 'Flow-down obligations to subs'],
      },
      {
        icon: 'ic-users', title: 'Labor and Wage Compliance',
        desc: 'The requirements that change your cost base rather than your paperwork.',
        items: ['Davis-Bacon wage determinations', 'Classification and fringe rates', 'Certified payroll obligations', 'Apprenticeship and hiring requirements'],
      },
      {
        icon: 'ic-calc', title: 'Estimating and Takeoff',
        desc: 'The same measurement and pricing engine the rest of the platform runs on.',
        items: ['AI quantity takeoff on the drawings', 'CSI-coded estimate on your cost data', 'Government estimate comparison', 'Alternates and unit price schedules'],
      },
      {
        icon: 'ic-file', title: 'Proposal Development',
        desc: 'Written to the evaluation criteria, in the order the solicitation states them.',
        items: ['Technical volume to Section M', 'Past performance and staffing sections', 'Price volume consistent with the estimate', 'Compliance matrix and submission checklist'],
      },
    ],
  },
  features: {
    eyebrow: 'Features',
    h2: 'Federal Bidding Features',
    lead: 'Everything commercial bidding needs, plus the parts that only exist in federal work.',
    cards: [
      { icon: 'ic-check',  title: 'Free Go/No-Go Analyzer', desc: 'Twelve-criterion opportunity scoring using your own SAM.gov API key, with no card and no account tier required.' },
      { icon: 'ic-db',     title: 'SAM.gov Opportunity Data', desc: 'Opportunity notices, attachments and amendments pulled in and analysed rather than downloaded and skimmed.' },
      { icon: 'ic-shield', title: 'FAR Clause Review', desc: 'Clause-level extraction of risk and compliance obligations with a page citation on every finding.' },
      { icon: 'ic-report', title: 'Evaluation Criteria Extraction', desc: 'Sections L and M parsed into a structure the proposal is then written against, criterion by criterion.' },
      { icon: 'ic-refresh',title: 'Amendment Tracking', desc: 'Each amendment compared against the previous package, with changes listed and acknowledgement tracked.' },
      { icon: 'ic-users',  title: 'Wage Determination Handling', desc: 'Davis-Bacon classifications and fringe rates applied to the labor in the estimate, not bolted on afterwards.' },
      { icon: 'ic-scan',   title: 'AI Quantity Takeoff', desc: 'The same takeoff engine as the rest of the platform, measuring the solicitation drawing set.' },
      { icon: 'ic-calc',   title: 'CSI Cost Estimating', desc: 'Estimates on your own cost data, coded to CSI divisions, in the format federal price volumes expect.' },
      { icon: 'ic-pkg',    title: 'Subcontractor Packages', desc: 'Packages and ITBs with flow-down requirements attached, plus small-business participation tracking.' },
      { icon: 'ic-file',   title: 'Proposal Generation', desc: 'Technical and price volumes drafted from the estimate, answering the evaluation criteria in stated order.' },
      { icon: 'ic-lock',   title: 'Compliance Checklist', desc: 'Submission requirements, formats, page limits and deadlines tracked as a checklist rather than remembered.' },
      { icon: 'ic-dl',     title: 'Excel Export', desc: 'Estimates, unit price schedules and comparisons exported in the formats agency bid forms ask for.' },
    ],
  },
  csi: {
    eyebrow: 'Solicitation structure',
    icon: 'ic-flag',
    h2: 'The Parts of a Solicitation It Reads',
    lead: 'The uniform contract format, read in full — including the sections that decide how you are scored.',
    rows: [
      { n: 'Section B', l: 'Supplies or services and prices — the bid schedule' },
      { n: 'Section C', l: 'Description, specifications and statement of work' },
      { n: 'Section E', l: 'Inspection and acceptance' },
      { n: 'Section F', l: 'Deliveries, performance period and milestones' },
      { n: 'Section H', l: 'Special contract requirements' },
      { n: 'Section I', l: 'Contract clauses — FAR and agency supplements' },
      { n: 'Section J', l: 'List of attachments, drawings and wage determinations' },
      { n: 'Section L', l: 'Instructions, conditions and notices to offerors' },
      { n: 'Section M', l: 'Evaluation factors for award' },
    ],
  },
  projectsH2: 'Federal Work It Is Used On',
  projectsLead: 'Barracks, VA facilities, base infrastructure, federal buildings and civil works.',
  workflow: {
    h2: 'From Opportunity Notice to Submitted Proposal',
    lead: 'The first step is the one that saves the most money, and it is free.',
    steps: [
      { t: 'Score the opportunity', s: 'Run the free Go/No-Go Analyzer with your own SAM.gov key: set-aside match, NAICS and size standard, value against bonding, geography, competition and schedule, scored across twelve criteria.' },
      { t: 'Decide before you commit', s: 'A federal pursuit costs a week of estimator time. The decision worth making well is whether to spend it, and it is better made from a score than from enthusiasm.' },
      { t: 'Read the solicitation', s: 'Statement of work, specifications, drawings, wage determinations and clauses are read in full, with the evaluation criteria in Sections L and M extracted into a structure.' },
      { t: 'Surface the risk', s: 'FAR and agency clauses, liquidated damages, bonding, insurance and flow-down obligations come out with page citations, so the risk position is explicit before you bid.' },
      { t: 'Measure and price', s: 'Quantities measured off the solicitation drawings and priced against your own cost data, with Davis-Bacon classifications and fringe rates applied to the labor.' },
      { t: 'Package the subcontract scope', s: 'Bid packages issued with flow-down requirements attached, coverage tracked by trade, and small-business participation recorded where the solicitation requires it.' },
      { t: 'Write to the criteria and submit', s: 'Technical and price volumes drafted against Section M in the order it states, with a compliance checklist covering formats, page limits and deadlines.' },
    ],
  },
  benefits: {
    eyebrow: 'Benefits',
    h2: 'What Changes on Federal Work',
    lead: 'The biggest gain is in the pursuits you decide not to make.',
    cards: [
      { icon: 'ic-check',   title: 'Better No Decisions', desc: 'Qualifying an opportunity in an hour instead of pursuing it for a week is the highest-return change available to a federal bidder, and it is the one nobody sells.' },
      { icon: 'ic-shield',  title: 'Clauses Read Every Time', desc: 'Clause-level review that used to happen on the large pursuits happens on all of them, because it now costs minutes.' },
      { icon: 'ic-report',  title: 'Proposals That Score', desc: 'Answering Section M in the order it is written is unglamorous and is what separates a scored proposal from a well-written one that lost.' },
      { icon: 'ic-users',   title: 'Wage Rates in the Estimate', desc: 'Applying Davis-Bacon classifications to the labor lines rather than adjusting at the end is what makes the price volume defensible.' },
      { icon: 'ic-refresh', title: 'Amendments Under Control', desc: 'Every amendment compared and acknowledged, so nothing is priced against a superseded package and no acknowledgement is missed.' },
      { icon: 'ic-trending',title: 'A Real Pipeline', desc: 'Scoring opportunities consistently turns federal work from an occasional gamble into a portfolio you can actually manage.' },
    ],
  },
  why: {
    h2: 'Why Federal Contractors Use BidcoreAI',
    lead: 'Most estimating software treats federal work as commercial work with more paperwork. It is not.',
    items: [
      { icon: 'ic-check',  t: 'Qualification comes first', s: 'The <a href="/go-no-go">Go/No-Go Analyzer</a> is free and needs no card, because the no-bid decision should not be behind a paywall.' },
      { icon: 'ic-shield', t: 'Clauses read with citations', s: 'FAR and agency clauses extracted with page references, so risk is a written position rather than a memory of reading it.' },
      { icon: 'ic-report', t: 'Written to Section M', s: 'Proposals drafted against the stated evaluation criteria in order, which is how they are actually graded.' },
      { icon: 'ic-users',  t: 'Wage determinations applied', s: 'Davis-Bacon classifications and fringes carried into the labor lines rather than added as an adjustment.' },
      { icon: 'ic-db',     t: 'Your cost data', s: 'Priced from your own history, in the CSI structure federal price volumes and government estimates use.' },
      { icon: 'ic-file',   t: 'Guidance included', s: 'The <a href="/guide">federal bidding guide</a> and the <a href="/blog/category/federal-bidding">federal bidding articles</a> cover the process end to end.' },
    ],
  },
  faqs: [
    { q: 'What is federal bidding software?', a: 'Federal bidding software supports the parts of government contracting that commercial bidding tools ignore: qualifying SAM.gov opportunities against set-asides, NAICS codes and bonding capacity; reading solicitations including FAR clauses and evaluation criteria; applying wage determinations to labor; tracking amendments and acknowledgements; and writing proposals that answer the stated evaluation factors in order.' },
    { q: 'Is the Go/No-Go Analyzer really free?', a: 'Yes. Connect your own SAM.gov API key and score an opportunity across twelve criteria at no cost and with no card. It is free deliberately: the highest-value decision in federal contracting is usually the decision not to pursue something, and putting that behind a paywall would be backwards. Try it at <a href="/go-no-go">the Go/No-Go Analyzer</a>.' },
    { q: 'What does the Go/No-Go score assess?', a: 'Twelve criteria covering set-aside and socioeconomic match, NAICS code and size standard, contract value against your bonding capacity, geography and mobilisation, past performance relevance, likely competition, schedule feasibility and the compliance burden the solicitation carries. The result is a score with the reasoning shown, not a verdict.' },
    { q: 'Does it read FAR clauses?', a: 'Yes, at clause level, with a page citation on every finding. FAR and agency supplement clauses, liquidated damages, bonding and insurance requirements, schedule constraints, flow-down obligations and unusual terms are extracted so your risk position is written down before you commit rather than discovered at award.' },
    { q: 'Does it handle Davis-Bacon wage determinations?', a: 'Yes. Classifications and fringe rates from the applicable wage determination are applied to the labor in the estimate, rather than adjusted at the end. That is what makes the price volume internally consistent and defensible if it is examined.' },
    { q: 'Can it write the proposal?', a: 'It drafts technical and price volumes from the priced estimate, structured against the evaluation criteria in Section M in the order they are stated, with the assumptions from the estimate carried through. You edit and submit. Writing to the criteria in order is unglamorous and is the difference between a proposal that scores and one that merely reads well.' },
    { q: 'How are amendments handled?', a: 'Each amendment is compared against the previous package with the changes listed, distributed to affected subcontractors, and acknowledgement tracked. A missed acknowledgement can make an otherwise strong offer non-responsive, so it is tracked rather than remembered.' },
    { q: 'Does it do the estimating as well?', a: 'Yes — the same AI takeoff and CSI cost estimating engine as the rest of the platform, measuring the solicitation drawings and pricing against your own cost data. See <a href="/software/construction-estimating-software">construction estimating software</a> for how the estimating side works.' },
    { q: 'Is it useful for subcontractors on federal work?', a: 'Yes. Subcontractors use it to qualify prime opportunities, understand the flow-down obligations they are being asked to accept, price their scope against wage determinations and produce a quote whose inclusions and exclusions are explicit — which matters more on federal work than anywhere else.' },
    { q: 'Where do I learn the federal bidding process itself?', a: 'The <a href="/guide">federal bidding guide</a> covers it start to finish, and the <a href="/blog/category/federal-bidding">federal bidding articles</a> go deeper on specific questions — <a href="/blog/reading-a-sam-gov-solicitation">reading a SAM.gov solicitation</a>, <a href="/blog/set-aside-certifications-explained">set-aside certifications</a>, <a href="/blog/bonding-capacity-portfolio-decision">bonding capacity</a> and <a href="/blog/federal-proposal-writing">proposal writing</a>.' },
  ],
  service: {
    h2: 'Estimating Support for Federal Pursuits',
    body: 'Federal sets are large and the deadlines are fixed. Estimators working in this same platform will measure the solicitation drawings, price the work against your cost data and Davis-Bacon rates, and return a priced estimate with a marked-up set and a written basis of estimate.',
    href: '/construction-estimating-services',
    label: 'Construction Estimating Services',
  },
  related: [
    'construction-bidding-software',
    'ai-bidding-software',
    'construction-estimating-software',
    'construction-takeoff-software',
    'quantity-takeoff-software',
    'concrete-estimating-software',
    'electrical-estimating-software',
    'earthwork-estimating-software',
  ],
  cta: {
    h2: 'Score an Opportunity Before You Bid It',
    lead: 'The Go/No-Go Analyzer is free and takes minutes. Run it on the solicitation currently sitting in your inbox.',
  },
},

];
