/**
 * The three head-term pages: estimating, takeoff, quantity takeoff.
 *
 * These are the pages the trade pages link up to, so they carry the general
 * argument — what the software does, where the numbers come from, what it
 * costs you to keep doing it in a spreadsheet — and leave the trade detail to
 * the pages below them.
 */
module.exports = [

/* ══════════════════════════════════════════════════════════════════════════
   CONSTRUCTION ESTIMATING SOFTWARE
══════════════════════════════════════════════════════════════════════════ */
{
  slug: 'construction-estimating-software',
  name: 'Construction Estimating Software',
  h1: 'Construction Estimating Software That Prices the Drawings, Not a Guess',
  title: 'Construction Estimating Software for Contractors | BidcoreAI',
  description: 'AI construction estimating software for contractors: takeoff, CSI-coded cost estimates, bid packages and proposals in one workspace. Book a live demo.',
  keywords: 'construction estimating software, ai construction estimating software, commercial construction estimating software, general contractor estimating software, cost estimating software for contractors, preconstruction software',
  eyebrow: 'Estimating platform',
  eyebrowIcon: 'ic-calc',
  heroLead: 'BidcoreAI is AI-powered construction estimating software for general contractors, subcontractors and preconstruction teams. Upload a drawing set and specifications, and the platform reads the scope, measures the quantities, prices them against your own cost data, and hands back a CSI-coded estimate you can defend line by line.',
  pills: [
    { icon: 'ic-scan',  text: 'AI takeoff built in' },
    { icon: 'ic-db',    text: 'Your cost database' },
    { icon: 'ic-cloud', text: 'Runs in the browser' },
  ],
  card: {
    eyebrow: 'What comes out the other end',
    headline: 'A defensible estimate',
    sub: 'Not a total — a priced, coded, traceable estimate with the assumptions written down',
    items: [
      'Line items coded to CSI MasterFormat divisions',
      'Material, labor, equipment and subcontract split out',
      'Every quantity traceable to the sheet it came from',
      'Markup, overhead and profit applied by your own rules',
      'Exported to Excel or CSV, or kept live in the project',
    ],
  },
  intro: {
    eyebrow: 'What it is',
    h2: 'What Construction Estimating Software Actually Has to Do',
    paras: [
      'Construction estimating software is the system a contractor uses to turn a set of drawings and specifications into a priced bid. That means four jobs, not one: read the scope out of the documents, measure the quantities off the drawings, apply costs to those quantities, and assemble the result into something a client, an owner or a contracting officer will accept. Tools that only do the last step are pricing spreadsheets with a nicer interface — the estimator still does the reading and the measuring by hand, which is where both the hours and the errors live.',
      'BidcoreAI covers all four. The AI document analysis reads every sheet, schedule and specification section and returns the scope it found, with a page reference for each item. The takeoff workspace measures the drawings — counts, lengths, areas and volumes — in the browser, with no separate takeoff licence to buy. The cost engine prices those quantities against your own historical costs or a regional benchmark database, coded to CSI MasterFormat. And the <a href="/software/construction-bidding-software">bid tools</a> package the scope for subcontractors, level what comes back, and draft the proposal from the estimate you just built — including on <a href="/software/federal-bidding-software">federal solicitations</a>, which most estimating software ignores entirely.',
      'The important detail is that these are not four products stitched together with exports. A quantity measured in the takeoff workspace is the same object the cost engine prices and the bid package references. When a revised drawing set arrives — and it always does — the platform compares it against the previous version, shows what changed, and updates the affected quantities instead of asking you to re-measure a floor because a door schedule moved.',
      'That matters most in the last week before a bid is due. The common failure in estimating is not arithmetic; it is a scope item that never made it out of the specification and onto the estimate at all. A missed fire-stopping section, an addendum that changed a slab thickness, a finish schedule nobody cross-checked against the room list. Software that reads the documents and keeps quantities tied to their source is software that makes those omissions visible while there is still time to price them.',
    ],
  },
  measures: {
    eyebrow: 'Coverage',
    icon: 'ic-layers',
    h2: 'What the Platform Estimates',
    lead: 'A whole project or a single trade — the same workspace, scoped to whatever you are actually bidding.',
    cards: [
      {
        icon: 'ic-building', title: 'Whole-Project Estimates',
        desc: 'General contractors pricing a complete building, from sitework through finishes and MEP, coded across all CSI divisions.',
        items: ['All-division estimate structure', 'Self-perform and subcontract split', 'General conditions and requirements', 'Escalation and contingency lines'],
      },
      {
        icon: 'ic-tool', title: 'Trade-Scoped Estimates',
        desc: 'Subcontractors pricing only their own scope, with the takeoff limited to the sheets and details that concern them.',
        items: ['Single-division or multi-division scope', 'Trade-specific units and waste factors', 'Crew-based labor productivity', 'Scope inclusions and exclusions'],
      },
      {
        icon: 'ic-db', title: 'Cost Database Estimating',
        desc: 'Unit costs from your own completed jobs, an imported cost book, or a regional benchmark when you have no history for a line item.',
        items: ['Import your existing cost library', 'Regional benchmark fallback', 'Crew, productivity and unit-rate models', 'Cost code mapping to your accounting system'],
      },
      {
        icon: 'ic-percent', title: 'Markup, Overhead and Profit',
        desc: 'Applied by rule rather than typed in at the end, so the same job priced twice comes out the same way twice.',
        items: ['Rules by division, trade or line type', 'Bonding, insurance and permit loading', 'Sales tax by jurisdiction', 'Fee structures for CM and design-build'],
      },
      {
        icon: 'ic-pkg', title: 'Bid Packages and Leveling',
        desc: 'The estimate splits into subcontractor packages, and the quotes that come back are compared against the scope you sent out.',
        items: ['Scope packages generated from the estimate', 'ITB tracking and coverage by trade', 'Side-by-side quote leveling', 'Gaps and inclusions flagged automatically'],
      },
      {
        icon: 'ic-file', title: 'Proposals and Submittals',
        desc: 'The proposal is drafted from the estimate that was actually priced, so the narrative and the numbers do not drift apart.',
        items: ['Proposal drafted from the priced estimate', 'Assumptions and exclusions carried through', 'Federal proposal structure supported', 'Export to Word, PDF or Excel'],
      },
    ],
  },
  features: {
    eyebrow: 'Features',
    h2: 'Everything in One Estimating Workspace',
    lead: 'The capabilities contractors normally buy from three or four separate vendors, connected rather than exported between.',
    cards: [
      { icon: 'ic-brain',  title: 'AI Document Analysis', desc: 'Specifications, drawings and addenda read end to end, with the scope returned as a list you can check against the documents.' },
      { icon: 'ic-scan',   title: 'AI Quantity Takeoff', desc: 'Counts, lengths, areas and volumes measured on PDF drawings in the browser, with AI proposing the measurements and you confirming them.' },
      { icon: 'ic-calc',   title: 'Cost Estimation', desc: 'Quantities priced against your own cost library, coded to CSI MasterFormat, with material, labor and equipment separated.' },
      { icon: 'ic-db',     title: 'Cost Database', desc: 'Your historical unit costs stored, versioned and reused, so the second estimate of a building type is faster than the first.' },
      { icon: 'ic-layers', title: 'Multi-Sheet Takeoff', desc: 'Measure across an entire plan set at once — every level, every detail sheet — instead of one page at a time.' },
      { icon: 'ic-refresh',title: 'Revision Comparison', desc: 'A new drawing set is compared against the last one, so an addendum shows you what changed instead of what is different.' },
      { icon: 'ic-shield', title: 'Risk and Compliance Analysis', desc: 'Contract clauses, liquidated damages, insurance limits and schedule risk pulled out of the documents with page citations.' },
      { icon: 'ic-pkg',    title: 'Bid Packages', desc: 'Scope split into subcontractor packages straight from the estimate, with the drawings and spec sections attached.' },
      { icon: 'ic-chart',  title: 'Bid Leveling', desc: 'Subcontractor quotes compared line against line, with what each one included and left out made explicit.' },
      { icon: 'ic-file',   title: 'Proposal Generation', desc: 'A proposal drafted from the estimate, following the structure the solicitation or the client asked for.' },
      { icon: 'ic-dl',     title: 'Excel and CSV Export', desc: 'Every estimate, quantity sheet and comparison exports to a spreadsheet anyone can open without a licence.' },
      { icon: 'ic-users',  title: 'Team Collaboration', desc: 'Several estimators in the same project at once, with a record of who changed which number and when.' },
    ],
  },
  csi: {
    h2: 'Estimates Structured to CSI MasterFormat',
    lead: 'Line items land in the divisions your cost codes, subcontractors and accounting system already use.',
    rows: [
      { n: 'Division 01', l: 'General requirements and general conditions' },
      { n: 'Division 02', l: 'Existing conditions, demolition and abatement' },
      { n: 'Division 03', l: 'Concrete — forming, reinforcing, cast-in-place' },
      { n: 'Division 04–05', l: 'Masonry and metals' },
      { n: 'Division 06–07', l: 'Wood, plastics, thermal and moisture protection' },
      { n: 'Division 08–09', l: 'Openings and finishes' },
      { n: 'Division 21–23', l: 'Fire suppression, plumbing and HVAC' },
      { n: 'Division 26–28', l: 'Electrical, communications and safety systems' },
      { n: 'Division 31–33', l: 'Earthwork, exterior improvements and utilities' },
    ],
  },
  projectsLead: 'The same estimating workspace, whether you build hospitals, warehouses or federal barracks.',
  workflow: {
    h2: 'From Drawing Set to Submitted Bid',
    lead: 'Seven steps, and the estimate stays connected to the drawings the whole way through.',
    steps: [
      { t: 'Upload the drawings and specifications', s: 'Drop in the plan set, specification book, addenda and any bid forms. PDFs are the normal case; large sets can come in as a Drive, Dropbox or WeTransfer link.' },
      { t: 'The AI reads the documents', s: 'Every sheet, schedule and specification section is analysed and the scope is returned as a list, each item citing the page it came from so you can check it rather than trust it.' },
      { t: 'Quantities are measured', s: 'The takeoff workspace measures counts, lengths, areas and volumes across the whole set. AI proposes the measurements; the estimator confirms, corrects or adds to them.' },
      { t: 'Review the measurements', s: 'Every quantity is shown on the sheet it came from, at the scale it was measured at, so a reviewer can verify a number without re-measuring it from scratch.' },
      { t: 'Apply your costs', s: 'Quantities are priced against your own cost library or a regional benchmark, with crew productivity, waste factors and equipment rates carried through to the line item.' },
      { t: 'Package and level the bid', s: 'The estimate splits into subcontractor packages, ITBs go out with the right sheets attached, and the quotes that come back are levelled against the scope you sent.' },
      { t: 'Export or submit', s: 'Export the estimate to Excel or CSV for your own bid form, or generate the proposal from the priced estimate and submit it with the assumptions attached.' },
    ],
  },
  benefits: {
    eyebrow: 'Benefits',
    h2: 'What Changes When the Estimate Comes Out of One System',
    lead: 'The gains are not mainly about typing speed. They are about what stops falling through the gaps.',
    cards: [
      { icon: 'ic-zap',     title: 'Faster Estimating', desc: 'Measuring is the slow part of any bid, and AI-proposed quantities across a whole plan set remove most of it. Estimators spend their time on judgement calls, not on clicking around a floor plan.' },
      { icon: 'ic-check',   title: 'Higher Bid Accuracy', desc: 'Quantities that stay tied to their sheet can be checked. Scope pulled out of the specifications with page citations can be argued about. Both are harder to get wrong than a number typed into a cell.' },
      { icon: 'ic-trending',title: 'More Bids per Estimator', desc: 'The constraint on most contractors is not opportunity, it is estimator hours. Cutting takeoff time is what lets a team pursue ten invitations to bid instead of properly pricing three.' },
      { icon: 'ic-db',      title: 'Costs That Compound', desc: 'Every estimate feeds the cost database. After a season of bidding, your unit costs reflect what your crews actually achieved on your projects, not what a national average says they should.' },
      { icon: 'ic-shield',  title: 'Fewer Scope Surprises', desc: 'Missed scope is the expensive kind of error — it survives into the contract. Reading the specifications systematically catches the sections a hurried estimator skims past.' },
      { icon: 'ic-users',   title: 'Work That Survives Turnover', desc: 'When the estimate, the measurements, the assumptions and the correspondence live in one project rather than on one person\'s desktop, a departure stops being a crisis.' },
    ],
  },
  why: {
    h2: 'Why Contractors Choose BidcoreAI',
    lead: 'Built for how US contractors actually bid — including the federal side, which most estimating tools ignore.',
    items: [
      { icon: 'ic-brain',  t: 'AI that shows its work', s: 'Every scope item and every measurement cites the sheet or specification section it came from. You are reviewing the AI, not taking its word.' },
      { icon: 'ic-db',     t: 'Your costs, not a black box', s: 'Pricing runs on your own historical unit costs. A benchmark database is there for the line items you have no history for, not as the default.' },
      { icon: 'ic-flag',   t: 'Federal bidding supported', s: 'SAM.gov opportunities, the free Go/No-Go Analyzer, FAR-aware risk review and proposal structures that match how solicitations are evaluated.' },
      { icon: 'ic-layers', t: 'Every trade in one place', s: 'Concrete, steel, MEP, finishes and sitework in the same project, so a general contractor is not reconciling six trade tools.' },
      { icon: 'ic-cloud',  t: 'Nothing to install', s: 'Runs in the browser on Windows, macOS, iPad or a jobsite laptop. No workstation licences, no plugin versions to keep aligned.' },
      { icon: 'ic-users',  t: 'Estimators behind it', s: 'If a bid is due Friday and you are short-handed, the same platform backs onto a professional estimating service that works in it with you.' },
    ],
  },
  faqs: [
    { q: 'What is construction estimating software?', a: 'Construction estimating software is the system a contractor uses to turn drawings and specifications into a priced bid. A complete one performs four jobs: extracting the scope from the documents, measuring quantities off the drawings, applying unit costs to those quantities, and assembling the result into a bid or proposal. BidcoreAI covers all four in one workspace, which is what separates it from a pricing spreadsheet where the reading and measuring are still done by hand.' },
    { q: 'How does AI estimate construction costs?', a: 'It does not invent prices. The AI reads the drawing set and specification book to identify scope, then proposes quantity measurements on each sheet — counts, lengths, areas and volumes. Those quantities are priced against your own cost database, or a regional benchmark where you have no history. The estimator reviews and corrects the AI output before anything is priced, and every quantity remains linked to the sheet it was measured on, so a reviewer can check it.' },
    { q: 'Can I use my own cost database?', a: 'Yes, and it is the intended way to run the platform. You can import an existing cost library from Excel or CSV, build one from your completed projects, or map line items to the cost codes your accounting system already uses. A regional benchmark database is available for scope you have never priced before, but it is a fallback rather than the default.' },
    { q: 'Does BidcoreAI do quantity takeoff as well as estimating?', a: 'Yes. Quantity takeoff is built into the platform rather than sold as a separate product, so there is no second licence and no export step between measuring and pricing. Measure the drawings in the browser, and the quantities are immediately available to the cost engine. See the <a href="/software/construction-takeoff-software">construction takeoff software</a> page for how the measurement side works.' },
    { q: 'Can I export estimates to Excel?', a: 'Yes. Estimates, quantity sheets, bid comparisons and material summaries all export to Excel or CSV. That matters because most contractors have a bid form, a client template or an accounting import that expects a spreadsheet, and because anyone downstream can open the file without a licence.' },
    { q: 'Is it suitable for general contractors, subcontractors, or both?', a: 'Both. A general contractor uses it to price a whole project across every division, split the scope into subcontractor packages and level the quotes that come back. A subcontractor uses it to price a single trade quickly across many invitations to bid. The workspace is the same; the scope you point it at is different.' },
    { q: 'What file formats can I upload?', a: 'PDF drawing sets are the normal case, including scanned and vector plans, along with specification books, addenda and bid forms. Large sets can be shared as a Google Drive, Dropbox or WeTransfer link rather than uploaded. Cost libraries import from Excel or CSV.' },
    { q: 'Is BidcoreAI cloud-based?', a: 'Yes. It runs in the browser on Windows, macOS, iPad and Android tablets, with nothing to install and no per-workstation licence. Projects, drawings and cost data live in the account, so an estimator on the road opens the same project as the one at the office.' },
    { q: 'Can my team work on the same estimate at once?', a: 'Yes. Several estimators can work in one project simultaneously — one on structural quantities, another on MEP — and the platform records who changed which number and when. Team seats are included from the Pro plan upward; see <a href="/pricing">pricing</a> for what each tier includes.' },
    { q: 'How is this different from hiring an estimating service?', a: 'Software gives you capacity you control and a cost database that compounds with every job you bid. A service gives you finished work without hiring. Most contractors end up wanting both at different moments, which is why BidcoreAI offers <a href="/construction-estimating-services">construction estimating services</a> staffed by estimators working in this same platform — use the software normally, and hand off the weeks where three bids land at once.' },
  ],
  service: {
    h2: 'Construction Estimating Services, Staffed by Estimators',
    body: 'Some weeks the bottleneck is not the tool, it is that four bids are due on the same Thursday. BidcoreAI also runs a professional estimating service: send the drawing set, and estimators working in this same platform return a priced estimate, a marked-up drawing set and a written basis of estimate — typically in 24 to 72 hours.',
    href: '/construction-estimating-services',
    label: 'Construction Estimating Services',
  },
  related: [
    'construction-takeoff-software',
    'quantity-takeoff-software',
    'construction-bidding-software',
    'ai-bidding-software',
    'federal-bidding-software',
    'concrete-estimating-software',
    'electrical-estimating-software',
    'hvac-estimating-software',
    'plumbing-estimating-software',
    'drywall-estimating-software',
  ],
  cta: {
    h2: 'See It Priced on Your Own Drawings',
    lead: 'Bring a set you have already bid. The fastest way to judge estimating software is to watch it price a job whose real numbers you know.',
  },
},

/* ══════════════════════════════════════════════════════════════════════════
   CONSTRUCTION TAKEOFF SOFTWARE
══════════════════════════════════════════════════════════════════════════ */
{
  slug: 'construction-takeoff-software',
  name: 'Construction Takeoff Software',
  h1: 'Construction Takeoff Software That Measures the Whole Plan Set',
  title: 'Construction Takeoff Software — AI PDF Takeoff | BidcoreAI',
  description: 'AI construction takeoff software: measure PDF drawings in the browser, across every sheet at once, and price the quantities in the same workspace.',
  keywords: 'construction takeoff software, pdf takeoff software, digital takeoff software, ai takeoff software, plan takeoff software, drawing measurement software',
  eyebrow: 'Takeoff platform',
  eyebrowIcon: 'ic-scan',
  heroLead: 'Measure construction drawings in the browser — counts, linear feet, square feet and cubic yards — with AI proposing quantities across every sheet and an estimator confirming them. No plugin, no workstation licence, and no export step between the takeoff and the estimate that uses it.',
  pills: [
    { icon: 'ic-layers', text: 'Multi-sheet measurement' },
    { icon: 'ic-brain',  text: 'AI-proposed quantities' },
    { icon: 'ic-refresh',text: 'Revision comparison' },
  ],
  card: {
    eyebrow: 'What a takeoff produces',
    headline: 'Quantities you can audit',
    sub: 'Every measurement stays attached to the sheet, the scale and the person who confirmed it',
    items: [
      'Counts, lengths, areas and volumes by scope item',
      'Colour-coded overlays on the drawing itself',
      'Scale and calibration recorded per sheet',
      'Waste factors applied and visible, not buried',
      'Straight into the estimate, or out to Excel',
    ],
  },
  intro: {
    eyebrow: 'What it is',
    h2: 'What Takeoff Software Is For',
    paras: [
      'A construction takeoff is the measurement stage of a bid: reading the drawings and recording how much of everything the project requires. Counts of doors and fixtures. Linear feet of wall, pipe and conduit. Square feet of drywall, roofing and flooring. Cubic yards of concrete and excavation. Takeoff software replaces the printed set, the scale rule and the highlighter with a digital plan set where every measurement is recorded, adjustable and attached to the place it was taken.',
      'The reason to care is that takeoff is where estimating time goes. On a mid-size commercial project an estimator can spend days measuring before a single price is applied, and the work is both tedious and unforgiving — miss a wing of a floor plan and the error propagates silently into the bid. Digital takeoff cuts the tedium; AI-assisted takeoff cuts it further by proposing the measurements and leaving the estimator to review them.',
      'BidcoreAI runs takeoff on PDF drawing sets in the browser. Set the scale on a sheet, and the platform measures across the whole set rather than page by page — every level, every enlarged plan, every detail. Quantities are grouped by scope item, carry their own waste factors, and stay linked to the sheet and coordinates where they were measured, so a reviewer can click a number and land on the drawing that produced it.',
      'Because the takeoff and the estimate are the same system, there is no export in the middle. Confirmed quantities are immediately available for pricing against your cost database, for splitting into subcontractor bid packages, and for the material summaries a supplier needs. And when a revised set lands, the platform compares it against the previous version and flags the sheets that changed, so an addendum costs you an afternoon of checking rather than a full re-measure.',
    ],
  },
  measures: {
    eyebrow: 'Measurement types',
    icon: 'ic-scan',
    h2: 'What the Takeoff Workspace Measures',
    lead: 'Every measurement type a construction takeoff needs, on the same plan set, in the same units your suppliers quote in.',
    cards: [
      {
        icon: 'ic-plus', title: 'Counts',
        desc: 'Symbol counts for anything that repeats — the measurement type most vulnerable to a tired estimator losing their place.',
        items: ['Doors, windows and openings', 'Fixtures, devices and diffusers', 'Columns, footings and piers', 'Search a symbol and count the whole set'],
      },
      {
        icon: 'ic-layout', title: 'Linear Measurements',
        desc: 'Lengths traced on the drawing, with segment breaks kept so a run can be split by type or by level.',
        items: ['Wall, partition and footing lengths', 'Pipe, duct and conduit runs', 'Curb, kerb and fence lengths', 'Perimeter and edge conditions'],
      },
      {
        icon: 'ic-layers', title: 'Area Measurements',
        desc: 'Polygon areas with deductions, because gross area and net area are not the same number and the difference is money.',
        items: ['Floor, roof and ceiling areas', 'Wall areas with opening deductions', 'Paving, slab and finish areas', 'Room-by-room breakdown'],
      },
      {
        icon: 'ic-db', title: 'Volume Measurements',
        desc: 'Depth or thickness applied to an area, so volumes come from the sections rather than from a plan-area shortcut.',
        items: ['Concrete volume by element', 'Excavation, cut and fill', 'Base course and fill layers', 'Volumes reported in cubic yards'],
      },
      {
        icon: 'ic-sched', title: 'Schedule-Driven Takeoff',
        desc: 'Door, window, fixture and finish schedules read directly, then reconciled against what was counted on the plans.',
        items: ['Door and window schedules', 'Room finish schedules', 'Equipment and fixture schedules', 'Mismatches flagged for an RFI'],
      },
      {
        icon: 'ic-refresh', title: 'Assemblies',
        desc: 'One measurement that generates several quantities — measure a partition once and get studs, track, board, tape and insulation.',
        items: ['Wall assemblies by type', 'Roof and floor build-ups', 'Reusable across projects', 'Editable component ratios'],
      },
    ],
  },
  features: {
    eyebrow: 'Features',
    h2: 'Takeoff Features That Matter on a Real Set',
    lead: 'The ones that decide whether a 400-sheet bid set takes two days or two weeks.',
    cards: [
      { icon: 'ic-brain',  title: 'AI-Proposed Quantities', desc: 'The platform finds and measures repeating conditions across the set, then presents them for confirmation rather than applying them silently.' },
      { icon: 'ic-layers', title: 'Multi-Sheet Takeoff', desc: 'Measure across the whole plan set at once — every level and detail sheet — instead of opening and calibrating one page at a time.' },
      { icon: 'ic-file',   title: 'PDF Drawing Support', desc: 'Vector and scanned PDF plan sets, including hand-marked and photocopied drawings that older tools refuse to calibrate.' },
      { icon: 'ic-tool',   title: 'Scale and Calibration', desc: 'Set the scale once per sheet, verified against a known dimension, with the calibration recorded so a reviewer can confirm it.' },
      { icon: 'ic-refresh',title: 'Revision Comparison', desc: 'A new issue is overlaid on the previous one and the differences highlighted, so an addendum means checking what changed, not re-measuring.' },
      { icon: 'ic-filter', title: 'Deductions and Openings', desc: 'Subtract openings, penetrations and excluded zones from an area rather than measuring around them by hand.' },
      { icon: 'ic-tag',    title: 'Scope Grouping', desc: 'Quantities grouped by trade, level, phase, room or bid package, and reported however you need to hand them on.' },
      { icon: 'ic-percent',title: 'Waste and Conversion Factors', desc: 'Waste, laps and conversion factors applied per item and shown as applied, so nobody has to guess whether 10% is already in there.' },
      { icon: 'ic-scan',   title: 'Marked-Up Drawing Output', desc: 'A colour-coded PDF of the measured set, so a client or reviewer sees exactly what was counted and what was not.' },
      { icon: 'ic-dl',     title: 'Excel Quantity Sheets', desc: 'Quantity sheets export to Excel or CSV with the sheet reference on every line, ready for a bid form or a supplier request.' },
      { icon: 'ic-users',  title: 'Shared Takeoffs', desc: 'Two estimators can split a set — one takes structural, one takes finishes — and the quantities merge into one project.' },
      { icon: 'ic-calc',   title: 'Priced in the Same Workspace', desc: 'Confirmed quantities flow straight into cost estimating, with no export, re-key or version mismatch in between.' },
    ],
  },
  csi: {
    h2: 'Takeoff Across Every Division',
    lead: 'One plan set, measured for whichever divisions you are responsible for.',
    rows: [
      { n: 'Division 02', l: 'Demolition and existing conditions' },
      { n: 'Division 03', l: 'Concrete — volume, rebar and formwork' },
      { n: 'Division 04', l: 'Masonry — CMU, brick and stone' },
      { n: 'Division 05', l: 'Structural and miscellaneous metals' },
      { n: 'Division 06', l: 'Wood framing and carpentry' },
      { n: 'Division 07–08', l: 'Roofing, insulation, doors and glazing' },
      { n: 'Division 09', l: 'Drywall, paint, flooring and ceilings' },
      { n: 'Division 21–23', l: 'Sprinkler, plumbing and HVAC' },
      { n: 'Division 26', l: 'Electrical — devices, feeders and lighting' },
      { n: 'Division 31–32', l: 'Earthwork, paving and site improvements' },
    ],
  },
  projectsLead: 'From a tenant fit-out to a hospital tower — the measurement types are the same, the volume is not.',
  workflow: {
    h2: 'How a Takeoff Runs',
    lead: 'Upload, calibrate, measure, review, price. The review step is the one nobody should skip.',
    steps: [
      { t: 'Upload the plan set', s: 'Drop the PDF drawing set into the project, along with specifications and addenda. Sheets are indexed by number and discipline so navigation is by sheet name, not page number.' },
      { t: 'Set the scale', s: 'Calibrate each sheet against a known dimension. The scale is stored with the sheet, so every later measurement on that page inherits it and a reviewer can verify it.' },
      { t: 'AI measures the set', s: 'The platform detects repeating conditions across the drawings — symbols, wall types, hatched areas — and proposes quantities for each, sheet by sheet.' },
      { t: 'Review and correct', s: 'Work through the proposals, adjust what the AI got wrong, and add anything only a human would catch from a detail or a note. Nothing is priced until it is confirmed.' },
      { t: 'Group and apply factors', s: 'Assign quantities to scope items, levels or bid packages, and apply waste, lap and conversion factors where the trade requires them.' },
      { t: 'Generate the estimate', s: 'Confirmed quantities are priced against your cost database in the same project — no export, no re-keying, no chance of pricing last week\'s numbers.' },
      { t: 'Export the deliverables', s: 'Marked-up drawing PDFs, Excel quantity sheets and material summaries, each carrying the sheet reference the quantity came from.' },
    ],
  },
  benefits: {
    eyebrow: 'Benefits',
    h2: 'What Digital Takeoff Changes',
    lead: 'Speed is the obvious gain. Auditability is the one that saves a job.',
    cards: [
      { icon: 'ic-zap',    title: 'Days Back on Every Bid', desc: 'Measuring is the largest single block of estimating time. AI-proposed quantities across the whole set turn most of it into review, which is faster and considerably less error-prone.' },
      { icon: 'ic-check',  title: 'Measurements You Can Defend', desc: 'Every quantity records its sheet, scale and author. When a number is questioned — by a client, a partner or your own PM after award — you can show where it came from.' },
      { icon: 'ic-refresh',title: 'Addenda Stop Hurting', desc: 'Revision comparison turns a re-issued set from a full re-measure into an afternoon of checking the sheets that actually changed.' },
      { icon: 'ic-layers', title: 'Nothing Skipped', desc: 'Working across the whole set rather than page by page is what stops a mezzanine or an enlarged plan being left out — the classic quiet omission in a manual takeoff.' },
      { icon: 'ic-cloud',  title: 'No Workstation Lock-In', desc: 'Browser-based takeoff means a laptop, an iPad or a hotel room works as well as the office desktop, and a new estimator needs an invitation rather than an install.' },
      { icon: 'ic-calc',   title: 'One Step to Pricing', desc: 'Because the quantities are already in the estimating workspace, there is no export, no re-key and no risk of pricing a superseded takeoff.' },
    ],
  },
  why: {
    h2: 'Why Estimators Use BidcoreAI for Takeoff',
    lead: 'Most takeoff tools stop at the measurement. This one is the front half of a bid.',
    items: [
      { icon: 'ic-brain',  t: 'AI you supervise', s: 'Quantities are proposed with their evidence and confirmed by a person. The measurement is auditable, which a black-box number never is.' },
      { icon: 'ic-layers', t: 'Whole-set measurement', s: 'The set is measured as a set. Levels, enlarged plans and details are handled together rather than as a sequence of unrelated pages.' },
      { icon: 'ic-calc',   t: 'Takeoff and estimate together', s: 'No export step. Confirmed quantities are already in the estimating workspace and already coded to CSI divisions.' },
      { icon: 'ic-cloud',  t: 'Runs anywhere', s: 'Browser-based, on Windows, macOS or an iPad on site. No plugin versions, no licence server, no install ticket.' },
      { icon: 'ic-dl',     t: 'Deliverables people can open', s: 'Marked-up PDFs and Excel quantity sheets — the two formats a client, a supplier or a subcontractor will actually accept.' },
      { icon: 'ic-users',  t: 'Estimators on call', s: 'When the volume spikes, the same platform backs onto a takeoff service that works inside your project rather than beside it.' },
    ],
  },
  faqs: [
    { q: 'What is construction takeoff software?', a: 'Construction takeoff software is the tool an estimator uses to measure quantities off drawings: counts, linear feet, square feet and cubic yards. It replaces the printed plan set, scale rule and highlighter with a digital set where every measurement is recorded, adjustable and linked to the sheet it was taken from. Those quantities then become the basis of the cost estimate.' },
    { q: 'How does AI takeoff work?', a: 'The platform analyses each sheet, recognises repeating conditions — symbols, wall types, hatched areas, schedules — and proposes measurements for them across the whole set. The estimator reviews each proposal on the drawing, corrects what is wrong and adds what only a person would catch from a detail or a general note. Nothing is priced until it has been confirmed, so the AI accelerates the work without owning the result.' },
    { q: 'Can I upload PDF drawings?', a: 'Yes. PDF plan sets are the primary input, including both vector drawings exported from CAD or Revit and scanned or photocopied sheets. You set the scale against a known dimension on each sheet, and that calibration is stored with the sheet for every later measurement.' },
    { q: 'Can it measure across multiple sheets at once?', a: 'Yes, and this is the main advantage over page-by-page tools. The plan set is treated as a set: measurements run across every level, enlarged plan and detail sheet, and quantities are grouped by scope rather than by page. It is also what stops a whole wing or a mezzanine being left out of a bid.' },
    { q: 'What happens when a revised drawing set arrives?', a: 'Upload the new issue and the platform compares it against the previous one, highlighting the sheets and areas that changed. You review the affected quantities rather than re-measuring the project. On a set that is re-issued twice during a bid period, this is usually the single biggest time saving in the tool.' },
    { q: 'Can I export takeoff quantities to Excel?', a: 'Yes. Quantity sheets export to Excel or CSV with the sheet reference on every line, and the measured set exports as a colour-coded marked-up PDF. Material summaries can be exported separately for supplier pricing requests.' },
    { q: 'Do I need to install anything?', a: 'No. Takeoff runs in the browser on Windows, macOS, iPad and Android tablets. There is no plugin, no CAD licence and no per-workstation install, so adding an estimator during a busy bid week is an invitation rather than an IT ticket.' },
    { q: 'Does the takeoff connect to cost estimating?', a: 'Directly. Confirmed quantities are immediately available to the cost engine in the same project, already coded to CSI divisions. There is no export, no re-keying and no possibility of pricing a superseded version of the takeoff. See <a href="/software/construction-estimating-software">construction estimating software</a> for the pricing side.' },
    { q: 'Can two estimators work on the same takeoff?', a: 'Yes. A set can be split — one estimator on structural, another on finishes and MEP — with the quantities merging into a single project. The platform records who measured what, which matters when a number is queried weeks later.' },
    { q: 'Can I have someone else do the takeoff?', a: 'Yes. BidcoreAI runs a professional <a href="/takeoff-services">takeoff service</a> staffed by estimators working in this same platform. Send the drawing set and you get back measured quantities, a marked-up drawing set and a written list of assumptions — typically within 24 to 72 hours.' },
  ],
  service: {
    h2: 'Takeoff Services When the Volume Spikes',
    body: 'Software fixes the per-bid cost of measuring. It does not create hours in a week where five sets land at once. BidcoreAI also provides professional takeoff services: send the plan set and estimators working in this platform return measured quantities, a marked-up drawing set and a written assumptions list, normally in 24 to 72 hours.',
    href: '/takeoff-services',
    label: 'Professional Takeoff Services',
  },
  related: [
    'quantity-takeoff-software',
    'construction-estimating-software',
    'ai-bidding-software',
    'construction-bidding-software',
    'concrete-estimating-software',
    'drywall-estimating-software',
    'earthwork-estimating-software',
    'structural-steel-estimating-software',
    'roofing-estimating-software',
  ],
  cta: {
    h2: 'Watch It Measure a Set You Know',
    lead: 'Bring a plan set you have already taken off by hand. Comparing the two is the only demo worth sitting through.',
  },
},

/* ══════════════════════════════════════════════════════════════════════════
   QUANTITY TAKEOFF SOFTWARE
══════════════════════════════════════════════════════════════════════════ */
{
  slug: 'quantity-takeoff-software',
  name: 'Quantity Takeoff Software',
  h1: 'Quantity Takeoff Software for Counts, Lengths, Areas and Volumes',
  title: 'Quantity Takeoff Software for Estimators | BidcoreAI',
  description: 'Quantity takeoff software for contractors and estimators — AI-measured counts, lengths, areas and volumes from PDF plans, exported to Excel or priced.',
  keywords: 'quantity takeoff software, material takeoff software, quantity surveying software, takeoff and estimating software, digital quantity takeoff, construction quantity software',
  eyebrow: 'Quantity measurement',
  eyebrowIcon: 'ic-layers',
  heroLead: 'Quantity takeoff software that produces the numbers a bid is built on: how many, how long, how much area, how much volume. Measured on PDF drawings with AI assistance, checked by an estimator, reported in the units your suppliers and subcontractors quote in.',
  pills: [
    { icon: 'ic-calc',   text: 'Counts · LF · SF · CY' },
    { icon: 'ic-percent',text: 'Waste factors applied' },
    { icon: 'ic-dl',     text: 'Excel quantity sheets' },
  ],
  card: {
    eyebrow: 'The deliverable',
    headline: 'A quantity sheet',
    sub: 'Every line carries its unit, its sheet reference and the factor applied to it',
    items: [
      'Grouped by scope item, level or bid package',
      'Units matched to how the trade is bought',
      'Waste, lap and conversion factors shown separately',
      'Marked-up drawings backing every quantity',
      'Excel and CSV, or priced in the same project',
    ],
  },
  intro: {
    eyebrow: 'What it is',
    h2: 'Quantity Takeoff, and Why the Units Decide Everything',
    paras: [
      'Quantity takeoff is the measurement of what a project physically requires, expressed in the units it is bought and installed in. Concrete in cubic yards. Formwork in square feet of contact area. Rebar in tons. Drywall in sheets or square feet. Conduit in linear feet by size. Doors in each. The list is the skeleton of the estimate — every cost line hangs off a quantity, and a quantity in the wrong unit is worse than a missing one, because it prices out to a plausible number nobody questions.',
      'That is why quantity takeoff software is not just a measuring tool. It has to know that a wall area needs its openings deducted but its corners counted once, that pipe is bought in lengths and priced per foot, that a 10% waste factor on flooring is normal and a 10% waste factor on structural steel is not. BidcoreAI carries units, deductions and factors per scope item, and shows the factor as applied rather than baking it into the number.',
      'The measuring itself runs on the PDF plan set in the browser. AI proposes quantities for repeating conditions across every sheet; an estimator reviews them against the drawings and the specifications. Quantities can be grouped by scope, by level, by phase or by bid package, so the same takeoff produces a supplier material list, a subcontractor package and an estimate structure without being measured three times.',
      'Everything stays traceable. Each quantity records the sheet, the scale and the person who confirmed it, and exports to Excel with those references intact. Whether the number ends up in a bid form, a purchase order or a schedule of values, someone can follow it back to a line on a drawing — which is the whole point of doing a takeoff instead of estimating by square-foot rule of thumb.',
    ],
  },
  measures: {
    eyebrow: 'Units',
    icon: 'ic-calc',
    h2: 'Quantities in the Units the Trade Buys In',
    lead: 'Measured once, reported in whichever unit the supplier, the subcontractor and the estimate each need.',
    cards: [
      {
        icon: 'ic-plus', title: 'Count Quantities (EA)',
        desc: 'Anything discrete and repeating, counted across the whole set rather than one sheet at a time.',
        items: ['Doors, windows, fixtures, devices', 'Equipment, diffusers and sprinkler heads', 'Footings, columns and piers', 'Reconciled against the schedules'],
      },
      {
        icon: 'ic-layout', title: 'Linear Quantities (LF)',
        desc: 'Runs traced on the drawing, split by size, type or level so they can be bought and priced correctly.',
        items: ['Walls, partitions and footings', 'Pipe and conduit by diameter', 'Duct by size and gauge', 'Trim, base, curb and edging'],
      },
      {
        icon: 'ic-layers', title: 'Area Quantities (SF / SY)',
        desc: 'Areas with deductions handled explicitly, because gross and net are different numbers with different uses.',
        items: ['Floor, wall, ceiling and roof areas', 'Openings deducted or retained by rule', 'Paving in SF or SY', 'Formwork contact area'],
      },
      {
        icon: 'ic-db', title: 'Volume Quantities (CY / CF)',
        desc: 'Depth taken from the sections and details, never inferred from plan area alone.',
        items: ['Concrete by element and mix', 'Excavation, cut, fill and haul', 'Aggregate base and subbase', 'Topsoil strip and respread'],
      },
      {
        icon: 'ic-chart', title: 'Weight Quantities (LB / TON)',
        desc: 'Weights calculated off schedules and section properties rather than assumed as a ratio of another quantity.',
        items: ['Rebar by bar size and length', 'Structural steel by section', 'Ductwork by gauge and area', 'Miscellaneous metals'],
      },
      {
        icon: 'ic-pkg', title: 'Material Quantities',
        desc: 'Measured quantities converted into what actually gets ordered — sheets, rolls, bags, sticks and pallets.',
        items: ['Board and sheet counts', 'Rolls, bundles and pallets', 'Bags, gallons and cartridges', 'Rounded to purchase units'],
      },
    ],
  },
  features: {
    eyebrow: 'Features',
    h2: 'Features Built Around Quantities, Not Drawings',
    lead: 'A takeoff tool measures. A quantity takeoff tool has to produce numbers you can buy from.',
    cards: [
      { icon: 'ic-brain',  title: 'AI Quantity Detection', desc: 'Repeating conditions found and measured across the set, presented as proposals with the drawing evidence attached.' },
      { icon: 'ic-tag',    title: 'Unit Management', desc: 'Each scope item carries its own unit and conversion, so a linear measurement can report as LF, as sticks, or as both.' },
      { icon: 'ic-percent',title: 'Waste and Lap Factors', desc: 'Factors set per item and displayed as applied, so nobody double-counts a 10% allowance that was already in the number.' },
      { icon: 'ic-filter', title: 'Deduction Rules', desc: 'Openings, penetrations and excluded zones deducted by rule, with gross and net both retained for different downstream uses.' },
      { icon: 'ic-sched',  title: 'Schedule Reconciliation', desc: 'Counted quantities checked against door, window, fixture and finish schedules, with mismatches flagged as RFI candidates.' },
      { icon: 'ic-layers', title: 'Grouping and Breakdown', desc: 'The same quantities reported by trade, level, phase, room or bid package without re-measuring anything.' },
      { icon: 'ic-refresh',title: 'Assemblies', desc: 'One measurement yielding several quantities — measure a partition and get studs, track, board, tape, screws and insulation.' },
      { icon: 'ic-report', title: 'Material Summaries', desc: 'Purchase-ready summaries rounded to order units, suitable for sending straight to a supplier for pricing.' },
      { icon: 'ic-scan',   title: 'Traceability', desc: 'Sheet, scale, coordinates and author recorded on every quantity, and carried into the Excel export.' },
      { icon: 'ic-dl',     title: 'Excel and CSV Export', desc: 'Quantity sheets in the format bid forms and purchasing systems expect, with references intact.' },
      { icon: 'ic-calc',   title: 'Direct to Cost Estimate', desc: 'Confirmed quantities priced in the same workspace against your own unit costs, with no export in between.' },
      { icon: 'ic-users',  title: 'Review Workflow', desc: 'A second estimator can review and sign off quantities before they are priced, with the changes recorded.' },
    ],
  },
  csi: {
    h2: 'Quantities by Division',
    lead: 'The measurement types change by trade. The workspace does not.',
    rows: [
      { n: 'Division 03', l: 'Concrete — CY, SFCA, tons of reinforcement' },
      { n: 'Division 04', l: 'Masonry — units, SF of wall, CY of grout' },
      { n: 'Division 05', l: 'Metals — tons, LF, EA of connections' },
      { n: 'Division 06', l: 'Wood — board feet, LF, sheet counts' },
      { n: 'Division 07', l: 'Thermal and moisture — SF, squares, LF of flashing' },
      { n: 'Division 08', l: 'Openings — EA by type and hardware set' },
      { n: 'Division 09', l: 'Finishes — SF, boards, gallons, LF of base' },
      { n: 'Division 22–23', l: 'Plumbing and HVAC — EA, LF by size, lb of duct' },
      { n: 'Division 26', l: 'Electrical — EA, LF by size, homerun counts' },
      { n: 'Division 31', l: 'Earthwork — CY cut, fill, export and import' },
    ],
  },
  projectsLead: 'Quantity takeoff is the same discipline whether the job is a fit-out or a treatment plant.',
  workflow: {
    h2: 'From Plan Set to Quantity Sheet',
    lead: 'The sequence that keeps units, factors and references intact all the way to the export.',
    steps: [
      { t: 'Load the drawings and schedules', s: 'Upload the plan set with its specification book and schedules. Schedules matter here: they are what a counted quantity gets reconciled against.' },
      { t: 'Calibrate each sheet', s: 'Scale is set from a known dimension and stored per sheet, so measurements taken later inherit it and a reviewer can confirm what it was.' },
      { t: 'Define the scope items', s: 'Set up what you are measuring and in which units — wall type, pipe size, finish schedule item — with the deduction and waste rules each one needs.' },
      { t: 'Measure with AI assistance', s: 'The platform proposes quantities for repeating conditions across the set; the estimator confirms, corrects and adds what the drawings imply but do not draw.' },
      { t: 'Reconcile against schedules', s: 'Counts are compared to the door, window, fixture and finish schedules. A count that disagrees with the schedule is either a measurement error or an RFI — both worth knowing before bid day.' },
      { t: 'Apply factors and convert', s: 'Waste, lap and conversion factors are applied per item and shown as applied, then quantities are rounded to purchase units where a material summary needs it.' },
      { t: 'Export or price', s: 'Export the quantity sheet to Excel with its sheet references, send the material summary to suppliers, or price the quantities in the same project.' },
    ],
  },
  benefits: {
    eyebrow: 'Benefits',
    h2: 'Why Careful Quantities Pay for Themselves',
    lead: 'The quantity is the part of an estimate that survives contact with the field.',
    cards: [
      { icon: 'ic-check',   title: 'Right Units, Right Prices', desc: 'A quantity in the wrong unit prices out to a believable number that is quietly wrong. Carrying units per scope item is the cheapest protection against that class of error.' },
      { icon: 'ic-zap',     title: 'Measured Once, Used Everywhere', desc: 'The same takeoff produces the estimate structure, the subcontractor packages and the supplier material list — three deliverables from one measurement.' },
      { icon: 'ic-percent', title: 'Waste You Can See', desc: 'Factors shown as applied rather than baked in stop the double-counting that happens when one estimator adds waste to a quantity another already grossed up.' },
      { icon: 'ic-scan',    title: 'Numbers You Can Trace', desc: 'Sheet references on every line mean a quantity queried after award can be shown rather than argued about — and re-checked in minutes.' },
      { icon: 'ic-report',  title: 'Purchasing Gets a Head Start', desc: 'Material summaries rounded to order units let procurement price the job while the estimate is still being assembled.' },
      { icon: 'ic-trending',title: 'Better History', desc: 'Consistent units and factors across jobs make your historical quantities comparable, which is what turns a cost database into something worth pricing from.' },
    ],
  },
  why: {
    h2: 'Why BidcoreAI for Quantity Takeoff',
    lead: 'Built by people who have had to defend a quantity to a client six months after award.',
    items: [
      { icon: 'ic-calc',   t: 'Units are first-class', s: 'Every scope item carries its unit, conversion and rounding rule. Quantities come out ready to buy from, not ready to convert.' },
      { icon: 'ic-percent',t: 'Factors stay visible', s: 'Waste, laps and conversions are shown as applied, so two estimators never gross up the same number twice.' },
      { icon: 'ic-sched',  t: 'Schedules cross-checked', s: 'Counts are reconciled against the drawing schedules automatically, which is how most miscounts get caught before bid day.' },
      { icon: 'ic-brain',  t: 'AI with evidence', s: 'Every proposed quantity comes with the sheet and location it was taken from. You are reviewing measurements, not accepting outputs.' },
      { icon: 'ic-dl',     t: 'Exports people accept', s: 'Excel quantity sheets and marked-up PDFs — what a supplier, a client and an accounting system each need.' },
      { icon: 'ic-layers', t: 'Every trade, one workspace', s: 'Concrete volumes, steel tonnage, duct weight and finish areas measured in the same project on the same set.' },
    ],
  },
  faqs: [
    { q: 'What is quantity takeoff software?', a: 'Quantity takeoff software measures how much of everything a project requires, in the units it is bought and installed in — each, linear feet, square feet, cubic yards, tons. It is the measurement layer beneath a cost estimate: every price line hangs off a quantity, so the quantities have to be both accurate and correctly united before pricing means anything.' },
    { q: 'What is the difference between takeoff and estimating?', a: 'Takeoff is measurement; estimating is pricing. A takeoff says the project needs 4,200 square feet of 5/8" type X board and 1,140 linear feet of 3-5/8" metal stud. An estimate says what those cost, once labor productivity, waste, equipment, overhead and markup are applied. BidcoreAI does both in one workspace, which is why there is no export step between them.' },
    { q: 'What units does the software support?', a: 'Counts (EA), linear measurements (LF, LM), areas (SF, SY, squares), volumes (CY, CF), weights (LB, TON) and material purchase units such as sheets, rolls, bundles, bags and gallons. Each scope item carries its own unit and conversion rule, so one measurement can report in several units without being taken twice.' },
    { q: 'How are waste factors handled?', a: 'Waste, lap and conversion factors are set per scope item and displayed as applied, alongside the raw measured quantity. That visibility is deliberate: the most common waste error is not the factor being wrong, it is two people applying it to the same number.' },
    { q: 'Does it deduct openings from wall and floor areas?', a: 'Yes, by rule per scope item. You decide whether a scope deducts openings and above what size — painting and drywall commonly treat small openings differently — and both the gross and net area are retained, because different downstream uses need different ones.' },
    { q: 'Can it generate a material list for suppliers?', a: 'Yes. Measured quantities convert into purchase units and export as a material summary — sheets, rolls, bags, sticks, pallets — rounded the way an order is placed. It can go to suppliers for pricing while the estimate is still being assembled.' },
    { q: 'Can I export quantities to Excel?', a: 'Yes. Quantity sheets export to Excel or CSV with the unit, factor and sheet reference on every line, so the export is auditable rather than just a column of numbers. Marked-up drawing PDFs export alongside them.' },
    { q: 'How accurate is AI quantity takeoff?', a: 'Accuracy depends on drawing quality and on the review step. The AI is consistently good at repeating, clearly drawn conditions and less good at scope that is implied by a note, a detail or the specification rather than drawn. That is exactly why every proposed quantity is reviewed by an estimator on the drawing before it can be priced.' },
    { q: 'Can quantities be grouped by phase or bid package?', a: 'Yes. The same quantities can be reported by trade, level, phase, room or bid package without re-measuring. A single takeoff therefore produces the estimate structure, the subcontractor packages and the procurement list.' },
    { q: 'Can BidcoreAI do the takeoff for me?', a: 'Yes — <a href="/quantity-takeoff-estimating-services">quantity takeoff and estimating services</a> are staffed by estimators working in this platform. You send the drawing set; you get back a quantity sheet, a marked-up drawing set and a written assumptions list, typically in 24 to 72 hours.' },
  ],
  service: {
    h2: 'Quantity Takeoff and Estimating Services',
    body: 'If what you need this week is finished quantities rather than a tool to produce them, the service side handles it. Estimators working in this same platform measure the set, reconcile it against the schedules and return a quantity sheet with the marked-up drawings and assumptions behind it.',
    href: '/quantity-takeoff-estimating-services',
    label: 'Takeoff &amp; Estimating Services',
  },
  related: [
    'construction-takeoff-software',
    'construction-estimating-software',
    'construction-bidding-software',
    'concrete-estimating-software',
    'masonry-estimating-software',
    'metal-framing-estimating-software',
    'painting-estimating-software',
    'earthwork-estimating-software',
    'doors-hardware-estimating-software',
  ],
  cta: {
    h2: 'Put a Plan Set in Front of It',
    lead: 'Bring a set with quantities you already know. Comparing them line for line is the only test that settles anything.',
  },
},

];
