/**
 * Finishes and envelope: drywall, painting, flooring, roofing, doors and
 * hardware.
 *
 * These trades share one problem — the quantity is an area or a count that
 * looks obvious on a plan, and the cost sits in the schedules, the details and
 * the transitions nobody measures. The copy keeps pointing at that.
 */
module.exports = [

/* ══════════════════ DRYWALL ══════════════════ */
{
  slug: 'drywall-estimating-software',
  name: 'Drywall Estimating Software',
  h1: 'Drywall Estimating Software for Board, Framing and Finish',
  title: 'Drywall Estimating Software for Contractors | BidcoreAI',
  description: 'Drywall estimating software: board area by wall type and layer count, framing, tape, insulation and finish levels measured from one pass over the plans.',
  keywords: 'drywall estimating software, drywall takeoff software, gypsum board estimating, sheetrock takeoff software, drywall bid software, interior finish estimating software',
  eyebrow: 'CSI Division 09 · Gypsum board',
  eyebrowIcon: 'ic-layers',
  heroLead: 'Drywall estimating software for drywall and interior contractors. Wall areas measured by type with layer count, board type and finish level carried per assembly — so a one-hour rated shaft wall with two layers each side is not priced as a single-layer office partition of the same length.',
  pills: [
    { icon: 'ic-layers', text: 'Layers by assembly' },
    { icon: 'ic-check',  text: 'Finish levels priced' },
    { icon: 'ic-layout', text: 'Framing in the same pass' },
  ],
  card: {
    eyebrow: 'What a drywall estimate needs',
    headline: 'Area × layers × finish',
    sub: 'Three multipliers, all of them living in the wall type legend rather than on the floor plan',
    items: [
      'Board area by type, thickness and layer count',
      'Framing quantities from the same measurement',
      'Tape, compound and corner bead by condition',
      'Finish level per surface, per the specification',
      'Insulation, firestopping and acoustic sealant',
    ],
  },
  intro: {
    eyebrow: 'What it is',
    h2: 'Why Drywall Is Priced Per Square Foot and Lost Per Assembly',
    paras: [
      'Drywall estimating looks like an area problem and behaves like a multiplication problem. The plan gives you wall length; the wall type legend gives you everything that matters. How many layers of board on each side. What thickness and type — regular, type X, mould-resistant, abuse-resistant, glass-mat. Whether the assembly is rated, and therefore how it must be detailed and firestopped. What finish level the specification requires on that surface. Multiply length by height and you get an area; multiply that by the wrong assembly and you get a number that is confidently wrong by a factor.',
      'BidcoreAI measures interiors by wall type, taking the assembly definition from the legend. A measured run of wall converts to board area with the layer count applied per side, board type carried per layer, and openings deducted by rule — the rule being one you set, since drywall commonly ignores small openings that a painting estimate would deduct.',
      'Finish level is treated as a cost driver rather than a note. Level 3, level 4 and level 5 differ substantially in labor and material, and level 5 across a large gloss-painted lobby is an entirely different proposition from level 4 in a back-of-house corridor. The specification usually says which applies where, and reading it is part of the takeoff rather than an optional refinement.',
      'Because framing and board share the same wall, both come out of one measurement. Studs at spacing, track, headers and backing on one side; board, tape, compound, corner bead, insulation, acoustic sealant and firestopping on the other. Ceilings, soffits, bulkheads, shafts and column wraps are measured as their own quantities, which matters because ceiling and soffit work runs at a different productivity from flat wall and gets under-carried whenever it is priced as though it were the same thing.',
    ],
  },
  measures: {
    eyebrow: 'Scope',
    icon: 'ic-layers',
    h2: 'What the Software Takes Off on a Drywall Package',
    lead: 'Floor plans, wall type legend, reflected ceiling plans, interior elevations and finish schedules.',
    cards: [
      {
        icon: 'ic-layout', title: 'Partitions',
        desc: 'Measured by wall type with layers, board type and rating carried per assembly.',
        items: ['Wall area by type and height', 'Layers per side and board type', 'Rated and acoustic assemblies', 'Openings deducted by rule'],
      },
      {
        icon: 'ic-layers', title: 'Ceilings and Soffits',
        desc: 'Measured separately because they run at their own productivity and get under-carried.',
        items: ['Gypsum ceilings and bulkheads', 'Soffits, coves and drops', 'Curved and radiused work', 'Access panels and openings'],
      },
      {
        icon: 'ic-building', title: 'Shafts and Special Assemblies',
        desc: 'Shaft wall, area separation and column wraps taken off with their own details.',
        items: ['Shaft wall by liner and stud size', 'Area separation and demising walls', 'Column and beam wraps', 'Chase and duct enclosures'],
      },
      {
        icon: 'ic-check', title: 'Finishing',
        desc: 'Tape, compound and bead by condition, with the specified finish level applied per surface.',
        items: ['Tape and compound by joint length', 'Corner bead, L-bead and reveals', 'Finish levels 3, 4 and 5', 'Skim coat and texture where specified'],
      },
      {
        icon: 'ic-shield', title: 'Rated and Acoustic Scope',
        desc: 'The work a rating requires, priced rather than assumed to come free with the board.',
        items: ['Firestopping at penetrations', 'Head-of-wall and joint systems', 'Acoustic sealant and putty pads', 'UL assembly compliance detail'],
      },
      {
        icon: 'ic-layout', title: 'Framing and Insulation',
        desc: 'Produced from the same measurement, so the interior package is measured once.',
        items: ['Studs, track and opening framing', 'Bridging, bracing and backing', 'Batt and mineral wool insulation', 'Furring, channel and clips'],
      },
    ],
  },
  features: {
    eyebrow: 'Features',
    h2: 'Drywall Estimating Features',
    lead: 'The wall type legend is the price list. This reads it.',
    cards: [
      { icon: 'ic-brain',  title: 'AI Wall Type Takeoff', desc: 'Wall types recognised from the legend and measured across every level, with each run shown on its sheet for confirmation.' },
      { icon: 'ic-layers', title: 'Layer Count Handling', desc: 'Board area calculated per side with layer counts applied, so a two-layer rated assembly is twice the board and not the same rate.' },
      { icon: 'ic-tag',    title: 'Board Type Tracking', desc: 'Regular, type X, mould-resistant, abuse-resistant and glass-mat carried per layer and priced accordingly.' },
      { icon: 'ic-check',  title: 'Finish Level Pricing', desc: 'Levels 3, 4 and 5 applied per surface from the specification, each with its own labor and compound quantity.' },
      { icon: 'ic-filter', title: 'Opening Deduction Rules', desc: 'Deduction thresholds you set per scope, because drywall and painting do not treat a small opening the same way.' },
      { icon: 'ic-layout', title: 'Framing From the Same Pass', desc: 'Studs, track, headers, bracing and backing produced from the same measurement as the board.' },
      { icon: 'ic-shield', title: 'Rated Assembly Detail', desc: 'UL assemblies tracked with the firestopping, head-of-wall systems and acoustic sealant they require.' },
      { icon: 'ic-percent',title: 'Waste by Board Size', desc: 'Waste calculated against actual board sizes and wall heights, since a 9-foot wall and 8-foot board is a different waste story.' },
      { icon: 'ic-report', title: 'Sheet Counts', desc: 'Board area converted to sheet counts by size and thickness for ordering, not just square feet for pricing.' },
      { icon: 'ic-users',  title: 'Productivity by Assembly', desc: 'Ceilings, soffits, shafts and high walls each carry their own hanging and finishing rates.' },
      { icon: 'ic-refresh',title: 'Revision Comparison', desc: 'A re-issued plan compared against the last, so a changed wall type is flagged rather than discovered on site.' },
      { icon: 'ic-dl',     title: 'Excel Export', desc: 'Quantities and priced estimates to Excel or CSV with wall type and sheet reference on every line.' },
    ],
  },
  csi: {
    h2: 'Drywall Spec Coverage',
    lead: 'Division 09 assemblies with the framing and firestopping sections they depend on.',
    rows: [
      { n: '09 21 16', l: 'Gypsum board assemblies' },
      { n: '09 22 16', l: 'Non-structural metal framing' },
      { n: '09 22 26', l: 'Suspension systems' },
      { n: '09 29 00', l: 'Gypsum board' },
      { n: '09 81 00', l: 'Acoustic insulation' },
      { n: '07 21 00', l: 'Thermal insulation' },
      { n: '07 84 00', l: 'Firestopping' },
      { n: '07 92 00', l: 'Joint sealants' },
      { n: '05 40 00', l: 'Cold-formed metal framing (interface)' },
    ],
  },
  projectsLead: 'Fit-outs, healthcare, hospitality, education and multifamily — anywhere the walls are stud and board.',
  workflow: {
    h2: 'How a Drywall Estimate Comes Together',
    lead: 'Legend, plans, ceilings, specification — in that order, because each one changes the next.',
    steps: [
      { t: 'Upload plans, legend and schedules', s: 'Floor plans, wall type legend, reflected ceiling plans, sections, interior elevations, finish schedules and the Division 09 specification sections.' },
      { t: 'Wall types read', s: 'Each type is extracted with its layers, board types, rating and stud spacing, and stored as a property that every measurement of that type inherits.' },
      { t: 'Partitions measured', s: 'Wall runs measured per type across each level, heights taken from the sections, openings deducted by your rule rather than a default someone else chose.' },
      { t: 'Ceilings and soffits measured', s: 'Reflected ceiling plans measured for gypsum ceilings, soffits and bulkheads, which are kept separate because they run at different productivity.' },
      { t: 'Board and finishing calculated', s: 'Areas convert to board area by layer, then to sheet counts by size, with tape, compound and bead quantified by joint and corner length.' },
      { t: 'Finish levels applied', s: 'The specification is read for finish level by surface, and levels 3, 4 and 5 are applied with their own labor and material rather than one blended finishing rate.' },
      { t: 'Priced and delivered', s: 'Framing, board, finishing, insulation and firestopping priced against your own rates and exported to Excel with a marked-up plan set behind every quantity.' },
    ],
  },
  benefits: {
    eyebrow: 'Benefits',
    h2: 'What Changes on a Drywall Bid',
    lead: 'The assembly stops being a footnote and becomes the unit of pricing.',
    cards: [
      { icon: 'ic-layers', title: 'Layers Counted', desc: 'Two-layer rated assemblies are twice the board and more than twice the finishing. Carrying the layer count per side is the difference between a bid and a guess.' },
      { icon: 'ic-check',  title: 'Finish Levels Priced', desc: 'Level 5 across a lobby is a materially different job from level 4 in a corridor, and the specification says which is where. Reading it is part of the takeoff.' },
      { icon: 'ic-layout', title: 'One Pass, Two Packages', desc: 'Framing and board from the same measurement removes a duplicate takeoff from every interior bid you price.' },
      { icon: 'ic-shield', title: 'Rated Work Carried', desc: 'Firestopping, head-of-wall systems and acoustic sealant are scope. Assuming they come free with a rated wall is a reliable way to donate margin.' },
      { icon: 'ic-report', title: 'Sheets, Not Just Square Feet', desc: 'Converting to board counts by size and thickness is what makes the delivery match the wall heights on site.' },
      { icon: 'ic-users',  title: 'Ceilings Priced Properly', desc: 'Ceiling and soffit work at flat-wall productivity is a standing under-bid. Separate rates fix it without anyone having to remember.' },
    ],
  },
  why: {
    h2: 'Why Drywall Contractors Use BidcoreAI',
    lead: 'Because everything that decides the price is in the legend and the specification, not the plan.',
    items: [
      { icon: 'ic-layers', t: 'Assemblies are the unit', s: 'Layers, board type, rating and finish level are properties of the wall type, so quantities and rates follow automatically.' },
      { icon: 'ic-check',  t: 'Finish levels read', s: 'The specification is parsed for finish level by surface, and each level carries its own labor and compound.' },
      { icon: 'ic-layout', t: 'Framing included', s: 'Studs, track, openings and backing come from the same measurement, so the interior package is measured once.' },
      { icon: 'ic-report', t: 'Board counts for ordering', s: 'Sheets by size and thickness, calculated against real wall heights rather than square feet divided by 32.' },
      { icon: 'ic-cloud',  t: 'Browser-based', s: 'No workstation licence; the marked-up plan set opens on a tablet in the field.' },
      { icon: 'ic-users',  t: 'Estimators available', s: 'Whole interior packages can be measured for you through <a href="/drywall-estimating-services">drywall estimating services</a>.' },
    ],
  },
  faqs: [
    { q: 'What is drywall estimating software?', a: 'Drywall estimating software measures interior walls and ceilings by assembly type and converts them into board area, sheet counts, framing, finishing materials and labor. The important part is that it works from the wall type — layers, board type, rating and finish level — rather than from wall length alone, because those are what actually determine the cost of a square foot of partition.' },
    { q: 'How does it handle multi-layer assemblies?', a: 'Layer count is carried per side on the wall type, so a rated assembly with two layers each side produces four times the board area of a single-layer partition of the same size, plus the additional taping and screw-off. Applying one board rate to every wall is the most common reason a rated corridor is under-bid.' },
    { q: 'Does it price finish levels?', a: 'Yes. Levels 3, 4 and 5 are applied per surface as read from the specification, each with its own labor and compound quantity. Level 5 with a skim coat across large flat surfaces under critical lighting is a substantially different cost from level 4, and the difference is usually specified rather than optional.' },
    { q: 'Does it estimate the framing too?', a: 'Yes, from the same measurement — studs at the specified spacing, track, opening framing, bridging and backing. Interior contractors bid framing and board together, so measuring the walls twice is pure waste. See <a href="/software/metal-framing-estimating-software">metal framing estimating software</a> for the framing detail.' },
    { q: 'How are openings handled?', a: 'By a deduction rule you set per scope, including a size threshold. Drywall commonly ignores small openings that a painting takeoff would deduct, and the two scopes need different treatment of the same wall. Both gross and net areas are retained.' },
    { q: 'Does it calculate sheet counts for ordering?', a: 'Yes. Board area converts to sheets by size and thickness against actual wall heights, so a job with 9-foot walls is ordered in the right board length rather than in 8-foot sheets with an implied waste factor nobody checked.' },
    { q: 'Does it include firestopping and acoustic sealant?', a: 'Yes. Rated assemblies carry their firestopping at penetrations, head-of-wall systems, acoustic sealant and putty pads as quantified scope. These are frequently assumed to come free with a rated wall, and they do not.' },
    { q: 'Are ceilings and soffits measured separately?', a: 'Yes, from the reflected ceiling plans, and priced at their own productivity. Gypsum ceilings, soffits, bulkheads and curved work are slower than flat wall by a wide margin, and pricing them at wall rates is a standing source of loss on fit-outs.' },
    { q: 'Can I use my own labor rates?', a: 'Yes. Hanging and finishing productivity by assembly type, wall height and finish level come from your own history, with a starting base available for scope you have no data on.' },
    { q: 'Can BidcoreAI estimate the drywall package for me?', a: 'Yes. <a href="/drywall-estimating-services">Drywall estimating services</a> are staffed by estimators working in this platform, returning board, framing and finishing quantities, a priced estimate and a marked-up plan set with every wall type identified.' },
  ],
  service: {
    h2: 'Drywall and Interior Estimating Services',
    body: 'Send the floor plans, wall type legend and reflected ceiling plans, and have the interior package measured for you — board by assembly and layer, framing from the same pass, finishing by specified level, plus insulation and firestopping — priced against your own rates.',
    href: '/drywall-estimating-services',
    label: 'Drywall Estimating Services',
  },
  related: [
    'metal-framing-estimating-software',
    'painting-estimating-software',
    'flooring-estimating-software',
    'doors-hardware-estimating-software',
    'construction-estimating-software',
    'quantity-takeoff-software',
    'construction-takeoff-software',
    'masonry-estimating-software',
  ],
  cta: {
    h2: 'Price an Interior Package Once',
    lead: 'Bring a floor plan with a wall type legend. Compare the board area, the sheet count and the finishing hours against your last bid.',
  },
},

/* ══════════════════ PAINTING ══════════════════ */
{
  slug: 'painting-estimating-software',
  name: 'Painting Estimating Software',
  h1: 'Painting Estimating Software for Surface Area and Coats',
  title: 'Painting Estimating Software for Contractors | BidcoreAI',
  description: 'Painting estimating software: paintable surface area by substrate, coats and prep from the finish schedule, gallons and labor priced from your own rates.',
  keywords: 'painting estimating software, painting takeoff software, paint contractor estimating software, commercial painting estimating, coating estimating software, painting bid software',
  eyebrow: 'CSI Division 09 · Painting',
  eyebrowIcon: 'ic-sparkle',
  heroLead: 'Painting estimating software for commercial painting contractors. Paintable surface area measured by substrate and room, coats and prep read from the finish schedule, and gallons calculated at real spread rates — so the estimate matches what the crew actually has to cover.',
  pills: [
    { icon: 'ic-layers', text: 'Area by substrate' },
    { icon: 'ic-refresh',text: 'Coats from the schedule' },
    { icon: 'ic-db',     text: 'Gallons at spread rate' },
  ],
  card: {
    eyebrow: 'What a painting estimate needs',
    headline: 'Surfaces, coats, access',
    sub: 'The same square foot costs three different amounts depending on substrate, coats and how you reach it',
    items: [
      'Paintable area by substrate and room',
      'Coat count and system from the schedule',
      'Prep, priming and patching as its own scope',
      'Gallons at manufacturer spread rates',
      'Access, masking and protection priced',
    ],
  },
  intro: {
    eyebrow: 'What it is',
    h2: 'Painting Is Measured in Square Feet and Priced in Everything Else',
    paras: [
      'A painting bid starts as an area measurement and immediately stops being one. The same 1,000 square feet of surface can be one coat of flat latex over new drywall, or three coats of epoxy over block with a fill coat, or two coats over previously painted plaster that needs washing, patching and spot priming first. The area is identical; the cost is not close. Painting estimating software has to carry substrate, system, coat count and preparation alongside the number, or it is producing an area report rather than an estimate.',
      'BidcoreAI measures paintable surface area by room and substrate, reading the finish schedule to determine what system goes where. Walls, ceilings, doors and frames, trim, exposed structure, ductwork and railings are each measured on their own terms — doors and frames counted by leaf and side rather than converted into a nominal square footage that no painter thinks in.',
      'Coats and preparation come from the specification and the finish schedule rather than an assumption. Surface preparation is treated as scope in its own right: washing, sanding, patching, filling block, spot priming, removing failed coatings. On a repaint or a renovation this frequently exceeds the cost of the paint and the application combined, and it is the item most often left out when a bid is put together quickly.',
      'Gallons are calculated at manufacturer spread rates by product and substrate, not at a single rule-of-thumb coverage figure. Porous block, primed drywall and smooth metal absorb differently, and a bid that assumes 400 square feet per gallon everywhere will be short on exactly the surfaces that are slowest to paint. Access is priced too — ladders, lifts and scaffold — along with masking, protection and the containment a renovation in an occupied building demands.',
    ],
  },
  measures: {
    eyebrow: 'Scope',
    icon: 'ic-sparkle',
    h2: 'What the Software Takes Off on a Painting Package',
    lead: 'Floor plans, reflected ceiling plans, interior elevations, door schedules and the finish schedule.',
    cards: [
      {
        icon: 'ic-layout', title: 'Wall Surfaces',
        desc: 'Measured by room and substrate, with openings deducted at a threshold you set.',
        items: ['Wall area by room and substrate', 'Drywall, block, plaster and concrete', 'Openings deducted by rule', 'Wall height from the sections'],
      },
      {
        icon: 'ic-layers', title: 'Ceilings and Structure',
        desc: 'Ceilings and exposed structure measured separately because they are slower to paint.',
        items: ['Gypsum and plaster ceilings', 'Exposed deck and structure', 'Exposed duct, pipe and conduit', 'Soffits and bulkheads'],
      },
      {
        icon: 'ic-file', title: 'Doors, Frames and Trim',
        desc: 'Counted by leaf and side, which is how painters price them, not converted to area.',
        items: ['Door leaves by side and finish', 'Frames and casings', 'Base, trim and millwork', 'Shop-primed versus field-finished'],
      },
      {
        icon: 'ic-refresh', title: 'Preparation',
        desc: 'Its own scope, and on renovation work often the largest part of the bid.',
        items: ['Washing, sanding and degreasing', 'Patching and filling', 'Block filler on CMU', 'Spot priming and stain blocking'],
      },
      {
        icon: 'ic-db', title: 'Systems and Materials',
        desc: 'Coats and products from the finish schedule, with gallons at real spread rates.',
        items: ['Coat count by system', 'Primer, intermediate and finish coats', 'Epoxy, urethane and specialty coatings', 'Gallons by product and substrate'],
      },
      {
        icon: 'ic-tool', title: 'Access and Protection',
        desc: 'How the crew reaches the surface, and what has to be covered to keep working.',
        items: ['Ladders, lifts and scaffold', 'Masking and floor protection', 'Containment in occupied areas', 'Night and phased work'],
      },
    ],
  },
  features: {
    eyebrow: 'Features',
    h2: 'Painting Estimating Features',
    lead: 'Substrate, system and access carried per surface — not applied as one rate at the end.',
    cards: [
      { icon: 'ic-brain',  title: 'AI Surface Takeoff', desc: 'Rooms and surfaces measured across the plan set with substrate identified from the wall types and finish schedule.' },
      { icon: 'ic-sched',  title: 'Finish Schedule Reading', desc: 'The finish schedule is parsed to map system, colour and coat count to each room and surface automatically.' },
      { icon: 'ic-filter', title: 'Deduction Thresholds', desc: 'Opening deductions set by size threshold per scope, since painting and drywall treat a small opening differently.' },
      { icon: 'ic-db',     title: 'Spread Rate Calculation', desc: 'Gallons calculated per product and substrate at manufacturer spread rates rather than a single coverage assumption.' },
      { icon: 'ic-refresh',title: 'Preparation Scope', desc: 'Washing, patching, block filling and spot priming quantified as their own lines with their own productivity.' },
      { icon: 'ic-plus',   title: 'Door and Frame Counting', desc: 'Doors counted by leaf and side from the door schedule, with shop-primed and field-finished separated.' },
      { icon: 'ic-tool',   title: 'Access Pricing', desc: 'Ladder, lift and scaffold requirements driven by ceiling height rather than remembered at the end of the estimate.' },
      { icon: 'ic-users',  title: 'Productivity by Condition', desc: 'Spray, roll and brush application, occupied buildings and night work each carry their own rate.' },
      { icon: 'ic-tag',    title: 'Colour Change Tracking', desc: 'Colour counts tracked by area, because a job with 14 accent colours costs more to cut in than one with two.' },
      { icon: 'ic-shield', title: 'Specialty Coatings', desc: 'Epoxy, urethane, intumescent and high-performance systems carried with their own prep and recoat windows.' },
      { icon: 'ic-report', title: 'Material Summaries', desc: 'Gallons by product and colour, rounded to order units for a supplier quote.' },
      { icon: 'ic-dl',     title: 'Excel Export', desc: 'Room-by-room surface schedules and priced estimates exported with sheet references intact.' },
    ],
  },
  csi: {
    h2: 'Painting Spec Coverage',
    lead: 'Division 09 painting sections plus the coatings that get bid with them.',
    rows: [
      { n: '09 91 00', l: 'Painting' },
      { n: '09 91 13', l: 'Exterior painting' },
      { n: '09 91 23', l: 'Interior painting' },
      { n: '09 93 00', l: 'Staining and transparent finishing' },
      { n: '09 96 00', l: 'High-performance coatings' },
      { n: '09 96 46', l: 'Intumescent painting' },
      { n: '09 97 13', l: 'Steel coatings' },
      { n: '09 67 00', l: 'Fluid-applied flooring (interface)' },
      { n: '09 29 00', l: 'Gypsum board finish level (interface)' },
    ],
  },
  projectsLead: 'Offices, schools, hospitals, hotels and industrial repaints — where the finish schedule is longer than the floor plan.',
  workflow: {
    h2: 'How a Painting Estimate Comes Together',
    lead: 'Schedule first, then surfaces, then the preparation that decides whether the job makes money.',
    steps: [
      { t: 'Upload plans and schedules', s: 'Floor plans, reflected ceiling plans, interior elevations, door and finish schedules, and the Division 09 painting specification sections.' },
      { t: 'Finish schedule mapped', s: 'The finish schedule is read and each room and surface is mapped to its system, coat count and colour, with the schedule reference retained on every line.' },
      { t: 'Surfaces measured by substrate', s: 'Wall, ceiling and structure areas are measured by room and substrate, with openings deducted at the threshold you set and heights taken from the sections.' },
      { t: 'Doors, frames and trim counted', s: 'Counted by leaf and side from the door schedule, with shop-primed and field-finished items separated so nothing is painted twice in the estimate.' },
      { t: 'Preparation quantified', s: 'Washing, sanding, patching, block filling and spot priming are measured as their own scope at their own productivity, which on renovation work is where the hours are.' },
      { t: 'Gallons calculated', s: 'Material is calculated at manufacturer spread rates by product and substrate, then rounded to order units by product and colour for supplier pricing.' },
      { t: 'Priced and delivered', s: 'Labor by application method and condition, access equipment priced separately, exported to Excel with a room-by-room surface schedule and a marked-up set.' },
    ],
  },
  benefits: {
    eyebrow: 'Benefits',
    h2: 'What Changes on a Painting Bid',
    lead: 'Substrate and prep stop being adjectives and become line items.',
    cards: [
      { icon: 'ic-refresh',title: 'Preparation Is Priced', desc: 'On renovation work prep routinely exceeds application. Quantifying it separately is what turns a repaint bid from optimism into a plan.' },
      { icon: 'ic-db',     title: 'Gallons That Match', desc: 'Spread rates by substrate mean the material order reflects porous block and smooth drywall differently — as the field already does.' },
      { icon: 'ic-plus',   title: 'Doors Counted as Doors', desc: 'Leaf-and-side counts match how painters think and how subcontract quotes are written, instead of a square footage nobody uses.' },
      { icon: 'ic-tool',   title: 'Access Not Forgotten', desc: 'Ceiling height driving lift and scaffold requirements catches the atrium and the warehouse before they catch you.' },
      { icon: 'ic-tag',    title: 'Colour Complexity Visible', desc: 'Fourteen accent colours is a cutting-in cost and a mobilisation cost. Counting colours makes that difference explicit.' },
      { icon: 'ic-sched',  title: 'Schedule-Driven Accuracy', desc: 'Reading the finish schedule directly is what stops a corridor being priced as flat latex when the specification called for epoxy.' },
    ],
  },
  why: {
    h2: 'Why Painting Contractors Use BidcoreAI',
    lead: 'Because the finish schedule is the estimate, and most tools never open it.',
    items: [
      { icon: 'ic-sched',  t: 'Finish schedule parsed', s: 'System, coats and colour mapped per room and surface automatically, with the schedule reference on every line.' },
      { icon: 'ic-refresh',t: 'Prep as its own scope', s: 'Washing, patching, block filler and spot priming measured and priced separately at their own productivity.' },
      { icon: 'ic-db',     t: 'Real spread rates', s: 'Gallons by product and substrate, not one coverage figure applied to every surface in the building.' },
      { icon: 'ic-tool',   t: 'Access priced', s: 'Lifts and scaffold driven by measured ceiling height rather than added as an afterthought.' },
      { icon: 'ic-cloud',  t: 'Browser-based', s: 'Measure and price from anywhere, with the marked-up set available on a tablet in the field.' },
      { icon: 'ic-users',  t: 'Estimators available', s: 'Painting packages can be measured for you through <a href="/takeoff-services">professional takeoff services</a>.' },
    ],
  },
  faqs: [
    { q: 'What is painting estimating software?', a: 'Painting estimating software measures paintable surface area by room and substrate, applies the coating system and coat count from the finish schedule, quantifies surface preparation, calculates material at real spread rates and prices labor by application method and access condition. Area alone is not an estimate: the same square foot varies several times over in cost depending on substrate, system and prep.' },
    { q: 'How does it calculate paintable surface area?', a: 'Wall, ceiling and structure areas are measured by room from the plans and sections, with substrate taken from the wall types and finish schedule. Openings are deducted at a size threshold you set, since painting typically deducts differently from drywall, and both gross and net areas are retained.' },
    { q: 'Does it read the finish schedule?', a: 'Yes. The finish schedule is parsed and each room and surface is mapped to its coating system, coat count and colour, with the schedule reference kept on the line item. This is what stops a corridor being priced as flat latex when the specification called for an epoxy system.' },
    { q: 'How are gallons calculated?', a: 'At manufacturer spread rates per product and substrate rather than a single coverage assumption. Porous block, primed drywall and smooth metal absorb very differently, and a uniform coverage figure is short exactly where the surfaces are slowest and most expensive to paint.' },
    { q: 'Does it estimate surface preparation?', a: 'Yes, as its own scope with its own productivity: washing, sanding, degreasing, patching, filling block, spot priming and stain blocking. On renovation and repaint work preparation frequently costs more than the paint and its application combined, and it is the first thing to be omitted from a hurried bid.' },
    { q: 'How are doors and frames handled?', a: 'Counted by leaf and side from the door schedule, with shop-primed and field-finished items separated. This matches how painters price and how subcontract quotes are written, rather than converting doors into a square footage that nobody in the trade uses.' },
    { q: 'Does it account for access equipment?', a: 'Yes. Ceiling and wall heights drive the ladder, lift or scaffold requirement, and access is priced as its own line. Atriums, warehouses and high stairwells are where an area-based bid quietly loses money.' },
    { q: 'Can it handle specialty and high-performance coatings?', a: 'Yes. Epoxy, urethane, intumescent and other high-performance systems carry their own preparation requirements, recoat windows and application conditions, all of which change the labor as much as the material.' },
    { q: 'Can I use my own production rates?', a: 'Yes. Spray, roll and brush productivity, occupied-building and night-work factors and crew rates all come from your own history, with a starting base available where you have no data.' },
    { q: 'Can BidcoreAI estimate the painting package for me?', a: 'Yes. <a href="/takeoff-services">Professional takeoff and estimating services</a> are staffed by estimators working in this platform, returning a room-by-room surface schedule, material quantities and a priced estimate with the marked-up drawings behind it.' },
  ],
  service: {
    h2: 'Painting Takeoff and Estimating Services',
    body: 'Send the plans and the finish schedule and have the package measured for you: surface area by room and substrate, coats and systems mapped from the schedule, preparation quantified separately, and gallons calculated at real spread rates.',
    href: '/takeoff-services',
    label: 'Takeoff &amp; Estimating Services',
  },
  related: [
    'drywall-estimating-software',
    'flooring-estimating-software',
    'doors-hardware-estimating-software',
    'metal-framing-estimating-software',
    'construction-estimating-software',
    'quantity-takeoff-software',
    'construction-takeoff-software',
    'masonry-estimating-software',
  ],
  cta: {
    h2: 'Measure a Finish Schedule You Know',
    lead: 'Compare the surface areas, the gallons and the preparation hours against the job you last painted.',
  },
},

/* ══════════════════ FLOORING ══════════════════ */
{
  slug: 'flooring-estimating-software',
  name: 'Flooring Estimating Software',
  h1: 'Flooring Estimating Software for Area, Transitions and Prep',
  title: 'Flooring Estimating Software for Contractors | BidcoreAI',
  description: 'Flooring estimating software: floor area by finish type from the schedule, base and transitions by length, prep and levelling quantified, priced per your rates.',
  keywords: 'flooring estimating software, flooring takeoff software, tile estimating software, carpet takeoff software, resilient flooring estimating, floor covering estimating software',
  eyebrow: 'CSI Division 09 · Flooring',
  eyebrowIcon: 'ic-layout',
  heroLead: 'Flooring estimating software for flooring contractors and interior trades. Floor areas measured room by room against the finish schedule, base and transitions measured by length, substrate preparation quantified as its own scope, and material calculated with real waste by pattern and roll width.',
  pills: [
    { icon: 'ic-layers', text: 'Area by finish type' },
    { icon: 'ic-layout', text: 'Base and transitions' },
    { icon: 'ic-percent',text: 'Waste by pattern' },
  ],
  card: {
    eyebrow: 'What a flooring estimate needs',
    headline: 'Room by room, not floor by floor',
    sub: 'The finish schedule decides the material; the perimeter decides half the labor',
    items: [
      'Floor area by room and finish type',
      'Base by room perimeter with the right material',
      'Transitions and thresholds counted by type',
      'Substrate prep, levelling and moisture testing',
      'Waste calculated by pattern and roll width',
    ],
  },
  intro: {
    eyebrow: 'What it is',
    h2: 'Floor Area Is the Start of a Flooring Estimate, Not the End',
    paras: [
      'Flooring is deceptively simple to measure and easy to under-price. The floor plan gives an area; the finish schedule gives eleven different materials spread across it; and the cost per square foot varies by a factor of ten between broadloom carpet in an open office and quarry tile with an epoxy grout in a kitchen. Then there is everything that is not floor area at all: base, transitions, thresholds, stair nosings, substrate preparation and the moisture testing without which the manufacturer\'s warranty does not exist.',
      'BidcoreAI measures flooring room by room and maps each room to its finish from the schedule. That structure matters — a room is the unit of installation, the unit of base measurement and the unit the finish schedule is written in. Area is measured net of walls and fixed elements, and the perimeter is captured at the same time, since base length is a perimeter problem that most area-based takeoffs never answer.',
      'Material is calculated with waste that reflects reality. Broadloom carpet from a 12-foot roll in an irregular room wastes very differently from carpet tile, which wastes differently from a plank floor laid diagonally, which wastes differently again from a tile with a pattern repeat and a 45-degree layout. Applying a flat 10% to all of them is fast and wrong in both directions.',
      'Preparation is treated as scope. Grinding, patching, self-levelling, moisture vapour testing, adhesive removal and old floor demolition are quantified separately, because on renovation work they routinely exceed the installed cost of the new floor and are the most common omission in a quick bid. Transitions, thresholds, reducers and stair treatment are counted by type rather than assumed proportional to area.',
    ],
  },
  measures: {
    eyebrow: 'Scope',
    icon: 'ic-layout',
    h2: 'What the Software Takes Off on a Flooring Package',
    lead: 'Floor plans, the finish schedule, floor transitions plan and interior elevations.',
    cards: [
      {
        icon: 'ic-layers', title: 'Floor Areas',
        desc: 'Measured room by room and mapped to the finish schedule rather than as one floor plate.',
        items: ['Net area by room and finish type', 'Deductions for fixed elements', 'Pattern direction and layout', 'Level and zone grouping'],
      },
      {
        icon: 'ic-layout', title: 'Base and Perimeter',
        desc: 'Perimeter captured with the area, because base length is a different measurement entirely.',
        items: ['Base length by room and material', 'Rubber, vinyl, wood and tile base', 'Corners, ends and returns', 'Coved base at wet areas'],
      },
      {
        icon: 'ic-tag', title: 'Transitions',
        desc: 'Counted by type where finishes meet, which is where the fussy labor lives.',
        items: ['Thresholds and reducers by type', 'Transition strips and edge trim', 'Expansion and movement joints', 'Door-line transitions'],
      },
      {
        icon: 'ic-refresh', title: 'Substrate Preparation',
        desc: 'Its own scope, and on a renovation typically the difference between profit and loss.',
        items: ['Grinding, patching and skim', 'Self-levelling by area and depth', 'Moisture vapour testing', 'Adhesive removal and demolition'],
      },
      {
        icon: 'ic-building', title: 'Stairs and Specials',
        desc: 'Measured per tread and riser, since a stair is not a square-foot problem.',
        items: ['Treads, risers and landings', 'Stringers and nosings', 'Ramps and sloped areas', 'Access floor and raised systems'],
      },
      {
        icon: 'ic-db', title: 'Material and Waste',
        desc: 'Calculated by product form, roll width and pattern repeat rather than a flat percentage.',
        items: ['Roll goods by width and seam plan', 'Tile and plank by carton', 'Pattern repeat and diagonal layout', 'Adhesive, grout, setting materials'],
      },
    ],
  },
  features: {
    eyebrow: 'Features',
    h2: 'Flooring Estimating Features',
    lead: 'Room-based measurement, schedule-driven materials, honest waste.',
    cards: [
      { icon: 'ic-brain',  title: 'AI Room Takeoff', desc: 'Rooms detected and measured across the plan set with area and perimeter captured together in one pass.' },
      { icon: 'ic-sched',  title: 'Finish Schedule Mapping', desc: 'Each room mapped to its floor finish, base and transition from the schedule, with the reference kept on the line.' },
      { icon: 'ic-layout', title: 'Perimeter for Base', desc: 'Base length taken from the measured room perimeter, with door openings and returns handled correctly.' },
      { icon: 'ic-percent',title: 'Waste by Product Form', desc: 'Roll width, seam layout, pattern repeat and diagonal installation each drive their own waste calculation.' },
      { icon: 'ic-refresh',title: 'Preparation Quantities', desc: 'Grinding, patching, self-levelling and adhesive removal measured by area and depth as separate scope.' },
      { icon: 'ic-tag',    title: 'Transition Counting', desc: 'Transitions and thresholds counted by type at every finish change and door line, not estimated as a percentage.' },
      { icon: 'ic-building',title: 'Stair Measurement', desc: 'Treads, risers, landings and nosings counted individually, because stairs are priced per unit and not per square foot.' },
      { icon: 'ic-report', title: 'Cartons and Rolls', desc: 'Material converted to purchase units — cartons, rolls, boxes, pails — with attic stock carried where specified.' },
      { icon: 'ic-users',  title: 'Installation Productivity', desc: 'Rates by material, room size and layout complexity, since small rooms and diagonal patterns are slower per foot.' },
      { icon: 'ic-shield', title: 'Moisture and Warranty Scope', desc: 'Moisture vapour testing and mitigation carried as scope where the specification or manufacturer requires it.' },
      { icon: 'ic-refresh',title: 'Revision Comparison', desc: 'A re-issued finish schedule compared against the previous one so changed room finishes are flagged.' },
      { icon: 'ic-dl',     title: 'Excel Export', desc: 'Room-by-room schedules with area, perimeter, finish and material exported to Excel or CSV.' },
    ],
  },
  csi: {
    h2: 'Flooring Spec Coverage',
    lead: 'Division 09 flooring sections plus the preparation work that precedes them.',
    rows: [
      { n: '09 05 61', l: 'Common work results for flooring preparation' },
      { n: '09 30 00', l: 'Tiling' },
      { n: '09 62 00', l: 'Specialty flooring' },
      { n: '09 64 00', l: 'Wood flooring' },
      { n: '09 65 00', l: 'Resilient flooring' },
      { n: '09 66 00', l: 'Terrazzo flooring' },
      { n: '09 67 00', l: 'Fluid-applied flooring' },
      { n: '09 68 00', l: 'Carpeting' },
      { n: '09 69 00', l: 'Access flooring' },
    ],
  },
  projectsLead: 'Offices, healthcare, education, hospitality and retail — anywhere the finish schedule runs to several pages.',
  workflow: {
    h2: 'How a Flooring Estimate Comes Together',
    lead: 'Rooms, then finishes, then everything that is not floor area.',
    steps: [
      { t: 'Upload plans and the finish schedule', s: 'Floor plans, the room finish schedule, transition details, interior elevations and the Division 09 flooring specification sections.' },
      { t: 'Rooms measured', s: 'Each room is measured for net area and perimeter in the same pass, with fixed elements deducted and the room name and number retained.' },
      { t: 'Finishes mapped', s: 'Rooms are mapped to their floor finish, base and transitions from the schedule, so the material follows the specification rather than an assumption.' },
      { t: 'Base and transitions quantified', s: 'Base length comes from the measured perimeter with door openings handled, and transitions are counted by type at every finish change and door line.' },
      { t: 'Preparation measured', s: 'Grinding, patching, self-levelling, moisture testing and existing floor removal are quantified by area and depth as their own scope.' },
      { t: 'Material calculated with real waste', s: 'Roll width, seam layout, pattern repeat and installation angle drive the waste calculation, and quantities convert to cartons, rolls and pails.' },
      { t: 'Priced and delivered', s: 'Installation priced by material and room complexity against your own rates, exported to Excel as a room-by-room schedule with the marked-up plans behind it.' },
    ],
  },
  benefits: {
    eyebrow: 'Benefits',
    h2: 'What Changes on a Flooring Bid',
    lead: 'The perimeter and the substrate stop being invisible.',
    cards: [
      { icon: 'ic-layout', title: 'Base Actually Measured', desc: 'Perimeter captured with area means base is a measured quantity rather than a guess derived from square footage, which is never right in irregular plans.' },
      { icon: 'ic-refresh',title: 'Prep Priced Up Front', desc: 'Self-levelling, grinding and adhesive removal on a renovation can exceed the new floor. Measuring them is the difference between a bid and a hope.' },
      { icon: 'ic-percent',title: 'Waste That Reflects Layout', desc: 'A diagonal plank layout in small rooms wastes nothing like carpet tile in open plan. Per-product waste stops one subsidising the other.' },
      { icon: 'ic-tag',    title: 'Transitions Counted', desc: 'Every finish change is a piece of trim and a slow ten minutes. Counting them is how a fit-out with 40 rooms gets priced honestly.' },
      { icon: 'ic-sched',  title: 'Schedule-Accurate Materials', desc: 'Mapping rooms to the finish schedule catches the areas where the specification changed and the plan did not.' },
      { icon: 'ic-report', title: 'Orders in Purchase Units', desc: 'Cartons, rolls and pails with attic stock included means the order matches the job rather than the estimate.' },
    ],
  },
  why: {
    h2: 'Why Flooring Contractors Use BidcoreAI',
    lead: 'Because the room is the unit, and most takeoff tools only know the floor plate.',
    items: [
      { icon: 'ic-layers', t: 'Room-based measurement', s: 'Area and perimeter measured together per room, which is how flooring is installed, scheduled and billed.' },
      { icon: 'ic-sched',  t: 'Finish schedule driven', s: 'Materials follow the schedule automatically, with the reference retained on every line for checking.' },
      { icon: 'ic-percent',t: 'Waste by product form', s: 'Roll width, pattern repeat and layout angle each drive their own waste rather than a flat percentage.' },
      { icon: 'ic-refresh',t: 'Preparation quantified', s: 'The scope that decides renovation profitability is measured rather than allowed for.' },
      { icon: 'ic-cloud',  t: 'Browser-based', s: 'Measure and price from anywhere; the marked-up room plan opens on a tablet on site.' },
      { icon: 'ic-users',  t: 'Estimators available', s: 'Flooring packages can be measured for you through <a href="/takeoff-services">professional takeoff services</a>.' },
    ],
  },
  faqs: [
    { q: 'What is flooring estimating software?', a: 'Flooring estimating software measures floor areas room by room, maps each room to its finish from the schedule, measures base and transitions, quantifies substrate preparation and calculates material with waste appropriate to the product form. Measuring a floor plate and multiplying by a rate misses base, transitions and preparation, which together are frequently a third of the bid.' },
    { q: 'How does it measure base and transitions?', a: 'Room perimeter is captured in the same pass as the area, so base length is measured rather than inferred, with door openings and returns handled. Transitions and thresholds are counted by type at every finish change and door line, which is where the slow, fussy labor actually sits.' },
    { q: 'How is waste calculated?', a: 'By product form. Broadloom carpet from a 12-foot roll in irregular rooms, carpet tile, plank laid diagonally and tile with a pattern repeat all waste differently, and each gets its own calculation including seam layout where roll goods are involved. A flat percentage across all of them is wrong in both directions at once.' },
    { q: 'Does it estimate floor preparation?', a: 'Yes, as separate scope: grinding, patching, skim coating, self-levelling by area and depth, moisture vapour testing, adhesive removal and existing floor demolition. On renovation work this frequently costs more than installing the new floor, and it is the most common omission in a fast bid.' },
    { q: 'Does it read the room finish schedule?', a: 'Yes. Each room is mapped to its floor finish, base type and transitions from the schedule, with the schedule reference retained on the line item. This catches rooms where the finish was revised in the schedule but the plan hatching was not updated.' },
    { q: 'How are stairs handled?', a: 'Per tread, riser, landing and nosing rather than by square footage, because stairs are quoted and installed as units and the labor per square foot bears no relationship to flat floor.' },
    { q: 'Does it produce material quantities in purchase units?', a: 'Yes. Quantities convert to cartons, rolls, boxes and pails by product, including adhesive, grout and setting materials, with attic stock carried where the specification requires it.' },
    { q: 'Does it handle moisture testing requirements?', a: 'Yes. Moisture vapour testing and mitigation are carried as scope where the specification or the flooring manufacturer requires them — an item that is inexpensive to include at bid and extremely expensive to discover after the slab fails a test.' },
    { q: 'Can I use my own installation rates?', a: 'Yes. Productivity by material, room size and layout complexity comes from your own history. Small rooms and diagonal or patterned installations are meaningfully slower per foot, and carrying that distinction is what keeps a fit-out bid honest.' },
    { q: 'Can BidcoreAI estimate the flooring package for me?', a: 'Yes. <a href="/takeoff-services">Professional takeoff and estimating services</a> are staffed by estimators working in this platform, returning a room-by-room schedule with areas, perimeters, materials and a priced estimate.' },
  ],
  service: {
    h2: 'Flooring Takeoff and Estimating Services',
    body: 'Send the floor plans and the finish schedule and have the package measured for you — room by room area and perimeter, materials mapped from the schedule, transitions counted, preparation quantified and waste calculated by product form.',
    href: '/takeoff-services',
    label: 'Takeoff &amp; Estimating Services',
  },
  related: [
    'painting-estimating-software',
    'drywall-estimating-software',
    'doors-hardware-estimating-software',
    'demolition-estimating-software',
    'construction-estimating-software',
    'quantity-takeoff-software',
    'construction-takeoff-software',
    'concrete-estimating-software',
  ],
  cta: {
    h2: 'Take Off a Finish Schedule You Know',
    lead: 'Compare the base length, the transition count and the prep quantities against the job you last installed.',
  },
},

/* ══════════════════ ROOFING ══════════════════ */
{
  slug: 'roofing-estimating-software',
  name: 'Roofing Estimating Software',
  h1: 'Roofing Estimating Software for Area, Flashing and Details',
  title: 'Roofing Estimating Software for Contractors | BidcoreAI',
  description: 'Roofing estimating software: roof area by system and slope, perimeter and flashing by length, penetrations counted, insulation and tapered layouts quantified.',
  keywords: 'roofing estimating software, roofing takeoff software, commercial roofing estimating, roof area calculator software, tpo epdm estimating, roofing bid software',
  eyebrow: 'CSI Division 07 · Roofing',
  eyebrowIcon: 'ic-home',
  heroLead: 'Roofing estimating software for commercial and industrial roofing contractors. Roof areas measured by system and slope, perimeter and flashing measured by length, penetrations counted individually, and insulation quantified including tapered layouts — because the details are where a roofing bid is decided.',
  pills: [
    { icon: 'ic-layers', text: 'Area by system' },
    { icon: 'ic-layout', text: 'Flashing by length' },
    { icon: 'ic-plus',   text: 'Penetrations counted' },
  ],
  card: {
    eyebrow: 'What a roofing estimate needs',
    headline: 'Field, edge and penetration',
    sub: 'The field is the cheap part per square foot; the edges and the details are the bid',
    items: [
      'Roof area by system, slope and level',
      'Perimeter, edge metal and flashing by length',
      'Penetrations counted by type and size',
      'Insulation by layer, R-value and taper',
      'Tear-off, deck repair and disposal',
    ],
  },
  intro: {
    eyebrow: 'What it is',
    h2: 'Roofing Is Priced by the Square and Lost at the Edges',
    paras: [
      'A commercial roof estimate has an easy part and a hard part. The easy part is the field: measure the area, divide by a hundred, price it per square. The hard part is everything at a boundary — parapet flashing, edge metal, counterflashing, expansion joints, curbs, drains, vents, pipe penetrations, equipment supports and the walk pads that connect them. Two roofs of identical area can differ by 50% in cost depending on how many of those exist, and the drawing that shows them is usually the roof plan nobody measures carefully because the field area was so easy to get.',
      'BidcoreAI measures roof area by system, level and slope, then measures the perimeter and every flashing condition by length and type. Penetrations are counted individually by type and size from the roof plan and the mechanical drawings, which is where half of them actually are — a roof plan rarely shows every curb the mechanical schedule implies, and reconciling the two is part of the takeoff.',
      'Insulation is quantified by layer and R-value, including tapered systems. Tapered insulation is a genuinely difficult quantity — it is a volume problem disguised as an area problem, and the difference between an average thickness and a real layout can be a large number on a big roof. Cover board, vapour barrier and adhesive or fastener patterns are carried per layer, with fastening density taken from the wind uplift requirements rather than assumed.',
      'Tear-off is estimated as its own scope with its own disposal cost, by existing system and number of layers, along with deck inspection and repair allowances. On a re-roof this is frequently the largest single variable in the bid, and it is the one most exposed to what is found once the old roof comes off — which is why it belongs in the estimate as a stated assumption rather than a hopeful lump sum.',
    ],
  },
  measures: {
    eyebrow: 'Scope',
    icon: 'ic-home',
    h2: 'What the Software Takes Off on a Roofing Package',
    lead: 'Roof plans, roof details, sections, mechanical plans and the Division 07 specification.',
    cards: [
      {
        icon: 'ic-layers', title: 'Roof Areas',
        desc: 'Measured by system, level and slope, with each roof area kept separate rather than totalled.',
        items: ['Area by roofing system', 'Slope, crickets and saddles', 'Multiple levels and sections', 'Squares by area and system'],
      },
      {
        icon: 'ic-layout', title: 'Perimeter and Edge',
        desc: 'Measured by length and condition — the highest-labor linear feet on the roof.',
        items: ['Parapet and wall flashing', 'Edge metal, gravel stop and fascia', 'Coping and counterflashing', 'Expansion and control joints'],
      },
      {
        icon: 'ic-plus', title: 'Penetrations',
        desc: 'Counted by type and size, reconciled against the mechanical and plumbing drawings.',
        items: ['Curbs, hatches and skylights', 'Pipe, vent and conduit penetrations', 'Equipment supports and sleepers', 'Drains, scuppers and overflows'],
      },
      {
        icon: 'ic-db', title: 'Insulation',
        desc: 'By layer and R-value, including the tapered layouts that are a volume problem in disguise.',
        items: ['Base and cover layers by thickness', 'Tapered systems by layout', 'Cover board and vapour barrier', 'Fastening density from uplift'],
      },
      {
        icon: 'ic-refresh', title: 'Tear-Off and Deck',
        desc: 'Its own scope with its own disposal, and the largest variable on a re-roof.',
        items: ['Existing system and layer count', 'Disposal volume and dumpsters', 'Deck inspection and repair allowance', 'Temporary protection and night seals'],
      },
      {
        icon: 'ic-tool', title: 'Access and Safety',
        desc: 'How material gets up there, and what has to be in place before anyone works.',
        items: ['Crane, hoist and conveyor', 'Perimeter warning and guardrail', 'Occupied building protection', 'Phasing and weather contingency'],
      },
    ],
  },
  features: {
    eyebrow: 'Features',
    h2: 'Roofing Estimating Features',
    lead: 'Built around the details, because the field area was never the difficult number.',
    cards: [
      { icon: 'ic-brain',  title: 'AI Roof Plan Takeoff', desc: 'Roof areas, perimeters and penetrations detected from the roof plan and proposed for confirmation on the sheet.' },
      { icon: 'ic-layers', title: 'System-Based Areas', desc: 'Areas grouped by roofing system, level and slope, so a TPO field and a modified bitumen section are never averaged together.' },
      { icon: 'ic-layout', title: 'Flashing by Condition', desc: 'Perimeter measured by flashing condition and height, since parapet flashing and edge metal are different rates entirely.' },
      { icon: 'ic-plus',   title: 'Penetration Reconciliation', desc: 'Roof-plan penetrations cross-checked against the mechanical and plumbing drawings, where the rest of them usually are.' },
      { icon: 'ic-db',     title: 'Tapered Insulation', desc: 'Tapered layouts quantified by volume rather than an average thickness, which on a large roof is a significant number.' },
      { icon: 'ic-shield', title: 'Uplift Fastening Density', desc: 'Fastener and adhesive quantities driven by the wind uplift requirement in the specification, including perimeter and corner zones.' },
      { icon: 'ic-refresh',title: 'Tear-Off Quantification', desc: 'Existing system and layer count measured for removal, with disposal volume and dumpster counts calculated.' },
      { icon: 'ic-percent',title: 'Waste and Laps', desc: 'Membrane laps, seam allowance and waste calculated by roll width and sheet layout rather than a blanket factor.' },
      { icon: 'ic-tool',   title: 'Access and Logistics', desc: 'Crane, hoist and conveyor requirements priced explicitly, with occupied-building constraints carried into productivity.' },
      { icon: 'ic-users',  title: 'Crew Productivity', desc: 'Field, detail and flashing productivity kept separate, because detail work runs many times slower per foot than open field.' },
      { icon: 'ic-report', title: 'Material Summaries', desc: 'Membrane, insulation, fasteners, metal and sealant in order units, ready for a supplier quote.' },
      { icon: 'ic-dl',     title: 'Excel Export', desc: 'Roof-by-roof schedules and priced estimates exported with sheet references intact.' },
    ],
  },
  csi: {
    h2: 'Roofing Spec Coverage',
    lead: 'Division 07 systems with the sheet metal and accessory sections bid alongside them.',
    rows: [
      { n: '07 01 50', l: 'Maintenance of membrane roofing (re-roof)' },
      { n: '07 21 00', l: 'Thermal insulation' },
      { n: '07 22 00', l: 'Roof and deck insulation' },
      { n: '07 41 00', l: 'Roof panels' },
      { n: '07 52 00', l: 'Modified bituminous membrane roofing' },
      { n: '07 54 00', l: 'Thermoplastic membrane roofing — TPO and PVC' },
      { n: '07 55 00', l: 'Protected membrane roofing' },
      { n: '07 62 00', l: 'Sheet metal flashing and trim' },
      { n: '07 71 00', l: 'Roof specialties — copings and edge' },
      { n: '07 72 00', l: 'Roof accessories — hatches and curbs' },
    ],
  },
  projectsLead: 'Warehouses, schools, retail, healthcare and industrial re-roofs — where the penetration count decides the price.',
  workflow: {
    h2: 'How a Roofing Estimate Comes Together',
    lead: 'Field area first because it is quick, then the two thirds of the work that is not field area.',
    steps: [
      { t: 'Upload roof plans and details', s: 'Roof plans, roof details, sections, mechanical and plumbing plans for penetrations, and the Division 07 specification sections.' },
      { t: 'Areas measured by system', s: 'Each roof area is measured by system, level and slope and kept separate, with squares calculated per area rather than for the building as a whole.' },
      { t: 'Perimeter and flashing measured', s: 'Perimeter is measured by flashing condition and height — parapet, edge, wall, expansion joint — each carrying its own material and productivity.' },
      { t: 'Penetrations counted', s: 'Curbs, drains, vents, pipes, hatches and equipment supports counted by type and size, then reconciled against the mechanical and plumbing drawings.' },
      { t: 'Insulation quantified', s: 'Layers, thicknesses and R-values quantified including tapered layouts by volume, with cover board, vapour barrier and fastening density from the uplift requirement.' },
      { t: 'Tear-off and disposal', s: 'Existing system and layer count measured for removal, disposal volume and dumpster counts calculated, deck repair carried as a stated allowance.' },
      { t: 'Priced and delivered', s: 'Field, detail and flashing labor priced separately against your own rates, access and logistics priced explicitly, exported to Excel with the marked-up roof plan.' },
    ],
  },
  benefits: {
    eyebrow: 'Benefits',
    h2: 'What Changes on a Roofing Bid',
    lead: 'The details get counted before the job starts instead of after.',
    cards: [
      { icon: 'ic-plus',   title: 'Penetrations Actually Counted', desc: 'Reconciling the roof plan against the mechanical drawings finds the curbs that were never drawn on the roof — the classic roofing surprise.' },
      { icon: 'ic-layout', title: 'Flashing Priced by Condition', desc: 'Parapet, edge and wall flashing at their own rates stops a detail-heavy roof being bid as though it were an open field.' },
      { icon: 'ic-db',     title: 'Tapered Insulation Done Right', desc: 'Quantifying taper as volume rather than average thickness removes one of the larger silent errors on big-roof bids.' },
      { icon: 'ic-refresh',title: 'Tear-Off With Its Disposal', desc: 'Measuring the existing system and its layers gives a disposal number that reflects the roof rather than a lump sum guess.' },
      { icon: 'ic-shield', title: 'Fastening From Uplift', desc: 'Density taken from the specification, including perimeter and corner zones, means the attachment matches the warranty requirement.' },
      { icon: 'ic-users',  title: 'Detail Labor Separated', desc: 'Detail work runs several times slower per foot than field. Separate productivity is what makes the labor number reviewable.' },
    ],
  },
  why: {
    h2: 'Why Roofing Contractors Use BidcoreAI',
    lead: 'Because the roof plan is not the only drawing with roof scope on it.',
    items: [
      { icon: 'ic-plus',   t: 'Penetrations cross-checked', s: 'Roof plan counts reconciled against the mechanical and plumbing sets, where the missing curbs always are.' },
      { icon: 'ic-layout', t: 'Perimeter by condition', s: 'Flashing measured by type and height rather than as one perimeter length at one rate.' },
      { icon: 'ic-db',     t: 'Taper as volume', s: 'Tapered insulation quantified from the layout, not from an average thickness that flatters the estimate.' },
      { icon: 'ic-refresh',t: 'Tear-off measured', s: 'Existing layers and disposal volume quantified, with deck repair carried as a visible allowance.' },
      { icon: 'ic-cloud',  t: 'Browser-based', s: 'Measure and price from anywhere; the marked-up roof plan opens on a tablet on the roof.' },
      { icon: 'ic-users',  t: 'Estimators available', s: 'Roofing packages can be measured for you through <a href="/takeoff-services">professional takeoff services</a>.' },
    ],
  },
  faqs: [
    { q: 'What is roofing estimating software?', a: 'Roofing estimating software measures roof areas by system and slope, measures perimeter and flashing conditions by length, counts penetrations by type, quantifies insulation including tapered layouts, and prices tear-off and disposal. The field area is the straightforward part; the details at every edge and penetration are where two bids on the same roof diverge.' },
    { q: 'How does it handle penetrations?', a: 'They are counted individually by type and size from the roof plan and then reconciled against the mechanical and plumbing drawings. Roof plans routinely show fewer curbs than the mechanical schedule implies, and finding that discrepancy during the estimate rather than during installation is the single most valuable check in a roofing takeoff.' },
    { q: 'Can it quantify tapered insulation?', a: 'Yes, by volume from the tapered layout rather than by an average thickness applied to the area. On a large roof the difference between an assumed average and the real layout is a material number, and it is one of the more common quiet errors in commercial roofing bids.' },
    { q: 'Does it estimate tear-off and disposal?', a: 'Yes, as its own scope. The existing system and its number of layers are measured for removal, disposal volume and dumpster counts are calculated, and deck inspection and repair are carried as a stated allowance so the assumption is visible rather than buried.' },
    { q: 'How is flashing measured?', a: 'By length and condition — parapet flashing, edge metal, gravel stop, coping, counterflashing, expansion joints and wall terminations each measured separately with their own material and productivity. A single perimeter length at a single rate underprices detail-heavy roofs and overprices simple ones.' },
    { q: 'Does it account for wind uplift fastening requirements?', a: 'Yes. Fastener and adhesive quantities follow the uplift requirement in the specification, including the increased density in perimeter and corner zones. Getting this from the specification rather than from habit is what keeps the installed system inside its warranty.' },
    { q: 'Does it work for both new roofs and re-roofs?', a: 'Both. New construction skips the tear-off scope and carries deck preparation; a re-roof adds removal, disposal, deck repair allowances, temporary protection and night seals, all of which are measured rather than lumped.' },
    { q: 'Can it produce a material list?', a: 'Yes. Membrane by roll, insulation by board, fasteners, plates, adhesive, edge metal and sealant convert to order units and export for supplier pricing, with laps and seam allowances already applied.' },
    { q: 'Can I use my own production rates?', a: 'Yes. Field, detail and flashing productivity are kept separate and priced against your own history, along with access, occupied-building constraints and phasing factors that change how fast a crew can actually work.' },
    { q: 'Can BidcoreAI estimate the roofing package for me?', a: 'Yes. <a href="/takeoff-services">Professional takeoff and estimating services</a> are staffed by estimators working in this platform, returning roof-by-roof areas, flashing lengths, penetration counts and a priced estimate with the marked-up roof plan behind it.' },
  ],
  service: {
    h2: 'Roofing Takeoff and Estimating Services',
    body: 'Send the roof plans, details and mechanical drawings and have the package measured for you — areas by system, perimeter by flashing condition, penetrations counted and cross-checked, insulation including taper, and tear-off with its disposal.',
    href: '/takeoff-services',
    label: 'Takeoff &amp; Estimating Services',
  },
  related: [
    'structural-steel-estimating-software',
    'hvac-estimating-software',
    'demolition-estimating-software',
    'masonry-estimating-software',
    'construction-estimating-software',
    'quantity-takeoff-software',
    'construction-takeoff-software',
    'sitework-estimating-software',
  ],
  cta: {
    h2: 'Count the Details on a Roof You Have Bid',
    lead: 'Compare the penetration count and the flashing lengths against what you carried — then check the mechanical plan.',
  },
},

/* ══════════════════ DOORS & HARDWARE ══════════════════ */
{
  slug: 'doors-hardware-estimating-software',
  name: 'Doors &amp; Hardware Estimating Software',
  h1: 'Doors and Hardware Estimating Software From the Schedule',
  title: 'Doors and Hardware Estimating Software | BidcoreAI',
  description: 'Door and hardware estimating software: openings counted from the schedule, frames and doors by type, hardware sets priced, and plan conflicts flagged early.',
  keywords: 'door estimating software, hardware estimating software, door schedule takeoff, hollow metal estimating software, door and frame takeoff, openings estimating software',
  eyebrow: 'CSI Division 08 · Openings',
  eyebrowIcon: 'ic-file',
  heroLead: 'Door and hardware estimating software for door suppliers, installers and general contractors. Openings taken from the door schedule and reconciled against the plans, doors and frames priced by type and rating, and hardware priced by set — with schedule-versus-plan conflicts flagged before they become site problems.',
  pills: [
    { icon: 'ic-sched',  text: 'Schedule reconciled' },
    { icon: 'ic-lock',   text: 'Hardware sets priced' },
    { icon: 'ic-shield', text: 'Ratings tracked' },
  ],
  card: {
    eyebrow: 'What an openings estimate needs',
    headline: 'Every opening, once',
    sub: 'The door schedule and the floor plan rarely agree, and the difference is somebody\'s change order',
    items: [
      'Openings counted from schedule and plans',
      'Doors by material, type, size and rating',
      'Frames by material, profile and anchor type',
      'Hardware priced by set, not by average',
      'Conflicts between schedule and plan flagged',
    ],
  },
  intro: {
    eyebrow: 'What it is',
    h2: 'The Door Schedule Is a Bill of Materials That Disagrees With the Plans',
    paras: [
      'Doors and hardware is the one package where the quantity is written down for you. The door schedule lists every opening with its number, size, material, type, rating, frame and hardware set. It should be the easiest takeoff in the building. In practice it is one of the most error-prone, because the schedule and the floor plans disagree on almost every project — an opening exists on the plan but not the schedule, a schedule row references a hardware set that was deleted two addenda ago, or a rated corridor has doors listed with no rating at all.',
      'BidcoreAI reads the door schedule as structured data and reconciles it against the openings counted on the plans. Every mismatch is reported: openings on the plan with no schedule row, schedule rows with no opening, size and swing conflicts, and rated wall types with unrated doors in them. Each of those is either a takeoff correction or an RFI, and both are worth having before the bid rather than after award.',
      'Pricing follows the schedule structure. Doors are priced by material, type, size, core, finish and rating — hollow metal, wood veneer, aluminium, glass, coiling, lead-lined. Frames are priced by material, profile, throat depth, anchor type and the wall condition they sit in. Hardware is priced by set, with the hardware schedule read set by set, rather than by an average hardware allowance per opening that is inevitably too high on the storerooms and too low on the exits.',
      'The scope that surrounds an opening is carried too: access control interfaces and electrified hardware coordination, the framing and backing an opening requires, fire and smoke rating implications, and the installation labor, which varies substantially between a hollow metal frame set in masonry and a knock-down frame in an existing stud wall.',
    ],
  },
  measures: {
    eyebrow: 'Scope',
    icon: 'ic-file',
    h2: 'What the Software Takes Off on an Openings Package',
    lead: 'Door schedule, hardware schedule, floor plans, wall types and the Division 08 specification.',
    cards: [
      {
        icon: 'ic-sched', title: 'Openings',
        desc: 'Counted from the schedule and from the plans, then reconciled against each other.',
        items: ['Openings by number and location', 'Schedule versus plan conflicts', 'Size, swing and handing', 'Existing versus new openings'],
      },
      {
        icon: 'ic-file', title: 'Doors',
        desc: 'Priced by material, type and rating rather than as a single average per leaf.',
        items: ['Hollow metal, wood and aluminium', 'Glass, coiling and specialty doors', 'Cores, finishes and vision lites', 'Fire and smoke ratings'],
      },
      {
        icon: 'ic-layout', title: 'Frames',
        desc: 'By material, profile and the wall condition they are installed in.',
        items: ['Welded and knock-down frames', 'Throat depth and profile', 'Anchor type by wall condition', 'Sidelites, transoms and borrowed lites'],
      },
      {
        icon: 'ic-lock', title: 'Hardware Sets',
        desc: 'Priced set by set from the hardware schedule, not as an allowance per opening.',
        items: ['Hinges, locksets and closers', 'Exit devices and panic hardware', 'Thresholds, seals and sweeps', 'Set-by-set pricing and substitutions'],
      },
      {
        icon: 'ic-cpu', title: 'Electrified Hardware',
        desc: 'The access control interface, and the coordination scope that comes with it.',
        items: ['Electric strikes and mag locks', 'Card readers and REX devices', 'Power supplies and transfer hinges', 'Interface to electrical and security'],
      },
      {
        icon: 'ic-tool', title: 'Installation',
        desc: 'Labor by frame type and wall condition, which vary more than the material does.',
        items: ['Frame setting by wall type', 'Door hanging and hardware fitting', 'Field modification and prep', 'Adjustment, keying and punch'],
      },
    ],
  },
  features: {
    eyebrow: 'Features',
    h2: 'Doors and Hardware Estimating Features',
    lead: 'Schedule reading, plan reconciliation and set-level hardware pricing.',
    cards: [
      { icon: 'ic-sched',  title: 'Door Schedule Extraction', desc: 'The schedule is read as structured data — number, size, material, rating, frame and hardware set on every row.' },
      { icon: 'ic-scan',   title: 'Plan Reconciliation', desc: 'Openings counted on the plans are matched against schedule rows and every mismatch is reported as a correction or an RFI.' },
      { icon: 'ic-shield', title: 'Rating Cross-Check', desc: 'Door ratings checked against the rated wall types they sit in, which is the most common and most expensive schedule error.' },
      { icon: 'ic-lock',   title: 'Hardware Set Pricing', desc: 'Hardware priced set by set from the hardware schedule rather than as an average allowance per opening.' },
      { icon: 'ic-file',   title: 'Door Type Pricing', desc: 'Material, core, finish, vision lites and specialty types priced individually rather than averaged into one leaf price.' },
      { icon: 'ic-layout', title: 'Frame Conditions', desc: 'Frame anchors and installation labor driven by the wall type each frame sits in — masonry, stud, existing.' },
      { icon: 'ic-cpu',    title: 'Electrified Coordination', desc: 'Electrified hardware flagged with its power, pathway and access-control interfaces, along with who is carrying them.' },
      { icon: 'ic-refresh',title: 'Addendum Tracking', desc: 'A re-issued schedule is compared against the previous one, so changed sets and added openings are flagged automatically.' },
      { icon: 'ic-users',  title: 'Installation Labor', desc: 'Setting and hanging productivity by frame type and wall condition, from your own history.' },
      { icon: 'ic-report', title: 'Opening-by-Opening Output', desc: 'A schedule-format export listing every opening with its door, frame, hardware set and price.' },
      { icon: 'ic-tag',    title: 'Keying and Cylinders', desc: 'Keying scope, cylinders and core type carried as their own line rather than assumed inside the hardware set.' },
      { icon: 'ic-dl',     title: 'Excel Export', desc: 'The complete openings schedule exported to Excel or CSV for the supplier, the submittal and the estimate.' },
    ],
  },
  csi: {
    h2: 'Openings Spec Coverage',
    lead: 'Division 08, with the access control interface kept visible rather than assumed.',
    rows: [
      { n: '08 11 00', l: 'Metal doors and frames' },
      { n: '08 12 00', l: 'Metal frames' },
      { n: '08 14 00', l: 'Wood doors' },
      { n: '08 31 00', l: 'Access doors and panels' },
      { n: '08 33 00', l: 'Coiling doors and grilles' },
      { n: '08 41 00', l: 'Entrances and storefronts' },
      { n: '08 71 00', l: 'Door hardware' },
      { n: '08 71 13', l: 'Automatic door operators' },
      { n: '08 80 00', l: 'Glazing' },
      { n: '28 13 00', l: 'Access control (interface)' },
    ],
  },
  projectsLead: 'Healthcare, education, hospitality and commercial fit-outs — where the door schedule runs to hundreds of rows.',
  workflow: {
    h2: 'How an Openings Estimate Comes Together',
    lead: 'Read the schedule, count the plans, then argue with the difference.',
    steps: [
      { t: 'Upload plans and schedules', s: 'Floor plans, the door schedule, the hardware schedule, frame details, wall types and the Division 08 specification sections.' },
      { t: 'Schedule extracted', s: 'The door schedule is read as structured data — number, size, material, type, rating, frame and hardware set for every row, with the sheet reference retained.' },
      { t: 'Openings counted on the plans', s: 'Openings are counted independently on the floor plans so the two sources can be compared rather than one being trusted.' },
      { t: 'Conflicts reported', s: 'Openings without schedule rows, rows without openings, size and swing mismatches, and unrated doors in rated walls are each reported for correction or RFI.' },
      { t: 'Doors and frames priced', s: 'Each opening prices by door material, type, core, finish and rating, and by frame material, profile and anchor type for the wall condition it sits in.' },
      { t: 'Hardware priced by set', s: 'The hardware schedule is priced set by set, with keying, cylinders and electrified components carried as their own lines and their interfaces noted.' },
      { t: 'Delivered as a schedule', s: 'The output is an opening-by-opening schedule in Excel with door, frame, hardware set and price on every row — usable for the bid and for the submittal.' },
    ],
  },
  benefits: {
    eyebrow: 'Benefits',
    h2: 'What Changes on an Openings Bid',
    lead: 'The disagreement between the schedule and the plans becomes a document instead of a surprise.',
    cards: [
      { icon: 'ic-scan',   title: 'Conflicts Found Early', desc: 'Every project has openings the schedule missed. Finding them at bid time makes them an RFI; finding them later makes them a change order in someone else\'s favour.' },
      { icon: 'ic-shield', title: 'Rating Errors Caught', desc: 'Cross-checking door ratings against rated wall types catches the error that is cheapest to fix on paper and most expensive to fix after installation.' },
      { icon: 'ic-lock',   title: 'Hardware Priced by Set', desc: 'An average allowance per opening is too high on storerooms and too low on exits. Set-level pricing removes both errors at once.' },
      { icon: 'ic-layout', title: 'Installation Priced Honestly', desc: 'A welded frame in masonry and a knock-down in an existing stud wall are different jobs. Frame condition drives the labor rather than a single per-opening rate.' },
      { icon: 'ic-cpu',    title: 'Electrified Scope Coordinated', desc: 'Flagging electrified hardware with its power and pathway interfaces settles who is carrying what before the coordination meeting does it for you.' },
      { icon: 'ic-report', title: 'One Output, Three Uses', desc: 'An opening-by-opening schedule serves the estimate, the supplier quote and the submittal without being rebuilt each time.' },
    ],
  },
  why: {
    h2: 'Why Openings Estimators Use BidcoreAI',
    lead: 'Because the schedule is data, and it should be treated as data.',
    items: [
      { icon: 'ic-sched',  t: 'Schedules read structurally', s: 'Every row parsed into its fields rather than eyeballed, so nothing is skipped in a 300-row schedule at midnight.' },
      { icon: 'ic-scan',   t: 'Reconciled against the plans', s: 'Two independent counts compared, with the differences reported instead of quietly resolved by whichever one you looked at last.' },
      { icon: 'ic-lock',   t: 'Set-level hardware', s: 'Priced from the hardware schedule set by set, with keying and cylinders carried separately.' },
      { icon: 'ic-shield', t: 'Ratings cross-checked', s: 'Door ratings verified against the rated wall types they sit in, catching the error nobody wants to find on site.' },
      { icon: 'ic-cloud',  t: 'Browser-based', s: 'Measure, reconcile and price from anywhere, with no workstation licence.' },
      { icon: 'ic-users',  t: 'Estimators available', s: 'Openings packages can be measured for you through <a href="/takeoff-services">professional takeoff services</a>.' },
    ],
  },
  faqs: [
    { q: 'What is door and hardware estimating software?', a: 'It reads the door and hardware schedules as structured data, counts the openings on the floor plans, reconciles the two, and prices each opening by door type, frame type and hardware set. The reconciliation is the valuable part: door schedules and floor plans disagree on almost every project, and that disagreement is where the money is.' },
    { q: 'How does it reconcile the schedule against the plans?', a: 'Openings are counted independently on the plans and matched against the schedule rows. Openings with no schedule row, rows with no opening, and mismatches in size, swing or handing are each reported. Every item is then either a takeoff correction or an RFI, and both are far cheaper before the bid than after award.' },
    { q: 'Does it check fire ratings?', a: 'Yes. Door ratings from the schedule are cross-checked against the rated wall types the openings sit in. An unrated door in a rated corridor is one of the most common schedule errors and among the most expensive to correct after installation.' },
    { q: 'How is hardware priced?', a: 'Set by set from the hardware schedule, with each set priced from its actual components — hinges, locksets, closers, exit devices, thresholds, seals — rather than as an average allowance per opening. Averages are consistently too high on simple storeroom sets and too low on exit and access-controlled openings.' },
    { q: 'Does it handle electrified hardware and access control?', a: 'Yes. Electrified hardware is flagged with its power supply, pathway and access-control interfaces, and the estimate records which contractor is carrying each part. This boundary between the openings supplier, the electrician and the security contractor is a routine source of gaps.' },
    { q: 'Does it price installation as well as material?', a: 'Yes. Frame setting and door hanging productivity vary considerably by frame type and wall condition — a welded frame grouted into masonry is a different job from a knock-down frame in existing studs — and the labor follows the condition rather than a single per-opening rate.' },
    { q: 'What happens when an addendum revises the schedule?', a: 'The re-issued schedule is compared against the previous version and every change is flagged: added openings, deleted rows, changed hardware sets, revised ratings. On projects with several addenda this is usually the largest single source of estimating error, and comparison removes it.' },
    { q: 'Can it export an opening-by-opening schedule?', a: 'Yes. The output is a schedule-format export listing every opening with its door, frame, hardware set and price, in Excel or CSV. The same file serves the estimate, the supplier quote and the basis of the submittal.' },
    { q: 'Is it useful for general contractors as well as door suppliers?', a: 'Yes. A general contractor uses it to carry the openings package in a whole-project estimate and to check supplier quotes against the schedule — particularly whether a quote priced the hardware sets as specified or substituted them.' },
    { q: 'Can BidcoreAI estimate the openings package for me?', a: 'Yes. <a href="/takeoff-services">Professional takeoff and estimating services</a> are staffed by estimators working in this platform, returning a reconciled opening schedule, a conflict list and a priced estimate.' },
  ],
  service: {
    h2: 'Openings Takeoff and Estimating Services',
    body: 'Send the plans and the door and hardware schedules and have the package reconciled and priced for you — every opening matched between schedule and plan, conflicts listed, doors and frames priced by type, and hardware priced set by set.',
    href: '/takeoff-services',
    label: 'Takeoff &amp; Estimating Services',
  },
  related: [
    'drywall-estimating-software',
    'metal-framing-estimating-software',
    'painting-estimating-software',
    'flooring-estimating-software',
    'construction-estimating-software',
    'quantity-takeoff-software',
    'construction-takeoff-software',
    'electrical-estimating-software',
  ],
  cta: {
    h2: 'Reconcile a Door Schedule You Have Priced',
    lead: 'Bring a schedule and a floor plan. The interesting part is how many openings do not appear on both.',
  },
},

];
