/**
 * MEP trades: electrical, plumbing, HVAC, fire protection.
 *
 * These four are counted more than they are measured — devices, fixtures,
 * heads, diffusers — and the length that connects them is rarely drawn to
 * scale in three dimensions. The copy is honest about that: risers, drops and
 * routing allowances are estimating decisions, not measurements, and the
 * software's job is to make the assumption visible rather than to hide it.
 */
module.exports = [

/* ══════════════════ ELECTRICAL ══════════════════ */
{
  slug: 'electrical-estimating-software',
  name: 'Electrical Estimating Software',
  h1: 'Electrical Estimating Software for Devices, Feeders and Gear',
  title: 'Electrical Estimating Software for Contractors | BidcoreAI',
  description: 'Electrical estimating software: device and fixture counts, homerun and feeder lengths, gear from the one-line, priced against your own labor units.',
  keywords: 'electrical estimating software, electrical takeoff software, electrical bid software, conduit and wire estimating, lighting takeoff software, electrical contractor estimating software',
  eyebrow: 'CSI Division 26 · Electrical',
  eyebrowIcon: 'ic-cpu',
  heroLead: 'Electrical estimating software for electrical contractors and design-build teams. Devices, fixtures and equipment counted across every level, homeruns and feeders measured with routing allowances you can see, gear taken from the one-line, and everything priced against your own labor units.',
  pills: [
    { icon: 'ic-plus',   text: 'Device counts by type' },
    { icon: 'ic-layout', text: 'Feeders from the one-line' },
    { icon: 'ic-users',  text: 'Your labor units' },
  ],
  card: {
    eyebrow: 'What an electrical estimate needs',
    headline: 'Counts, runs and gear',
    sub: 'The counts are measurable, the runs are assumptions — the estimate should show which is which',
    items: [
      'Device, fixture and equipment counts by type',
      'Branch circuits with routing and drop allowances',
      'Feeder lengths and sizes from the one-line',
      'Panels, switchgear and distribution equipment',
      'Labor units per item, from your own history',
    ],
  },
  intro: {
    eyebrow: 'What it is',
    h2: 'Counting Is the Easy Half of an Electrical Estimate',
    paras: [
      'Electrical drawings show you what to count and almost nothing about what to buy. A lighting plan tells you there are 214 fixtures of six types. It does not tell you how much wire connects them, how the homeruns route, how far a drop falls from the deck to a device, or how much conduit gets bent around a duct that is not on your sheet. That gap between what is drawn and what is installed is where electrical estimates go wrong, and no amount of measuring precision closes it — only stated assumptions do.',
      'BidcoreAI counts what can be counted and makes the rest explicit. Devices, fixtures, equipment connections and junction boxes are counted by type across every level and reconciled against the fixture and panel schedules. Homeruns are measured to the panel with a routing factor and a drop allowance applied per area type, both shown as applied rather than folded into a rate. Feeders come off the one-line diagram by size and length, and the gear — panels, switchboards, transformers, disconnects — is taken from the schedules as counted equipment.',
      'Pricing runs on labor units, the way electrical estimating actually works. Each item carries an install unit — hours per device, per fixture, per hundred feet of conduit by size and method — from your own historical productivity or an industry base you adjust. Conditions that change productivity are applied as factors you can see: work above 15 feet, occupied buildings, after-hours work, exposed versus concealed, EMT versus rigid.',
      'The result is an estimate a reviewer can interrogate. If your number is 12% above the next bid, the conversation is about whether 214 fixtures is right, whether the drop allowance was 12 feet or 18, and whether the other bidder priced the feeder as aluminium — rather than about two totals that share no visible structure.',
    ],
  },
  measures: {
    eyebrow: 'Scope',
    icon: 'ic-cpu',
    h2: 'What the Software Takes Off on an Electrical Package',
    lead: 'Power plans, lighting plans, the one-line, panel schedules and fixture schedules, read together.',
    cards: [
      {
        icon: 'ic-plus', title: 'Devices and Outlets',
        desc: 'Counted by type and mounting from the power plans, reconciled against the symbol legend.',
        items: ['Receptacles by type and rating', 'Switches, dimmers and sensors', 'Data, AV and low-voltage outlets', 'Floor boxes and poke-throughs'],
      },
      {
        icon: 'ic-zap', title: 'Lighting',
        desc: 'Fixtures counted by type from the lighting plans and checked against the fixture schedule.',
        items: ['Fixtures by schedule type', 'Emergency and exit fixtures', 'Controls, sensors and drivers', 'Site and exterior lighting'],
      },
      {
        icon: 'ic-layout', title: 'Branch Circuits',
        desc: 'Homeruns measured to the panel with routing and drop allowances applied and visible.',
        items: ['Homeruns by circuit and panel', 'Conduit by size and type', 'Wire by size, with pull allowance', 'Boxes, fittings and supports'],
      },
      {
        icon: 'ic-chart', title: 'Feeders and Distribution',
        desc: 'Taken off the one-line by size and length rather than guessed from the floor plan.',
        items: ['Feeder runs by size and length', 'Conduit and cable tray routing', 'Grounding and bonding', 'Riser and vertical distribution'],
      },
      {
        icon: 'ic-db', title: 'Equipment and Gear',
        desc: 'Counted from the schedules and priced as equipment, with its own delivery and lead-time notes.',
        items: ['Panels and panelboards', 'Switchgear and switchboards', 'Transformers and disconnects', 'Generators, ATS and UPS'],
      },
      {
        icon: 'ic-shield', title: 'Systems and Specialties',
        desc: 'The Division 27 and 28 scope that lands on the electrical contractor whether or not it is drawn.',
        items: ['Fire alarm devices and wiring', 'Data cabling and racks', 'Security, access and CCTV', 'Equipment connections and hookups'],
      },
    ],
  },
  features: {
    eyebrow: 'Features',
    h2: 'Electrical Estimating Features',
    lead: 'Symbol counting, labor units and visible assumptions — the three things an electrical bid runs on.',
    cards: [
      { icon: 'ic-brain',  title: 'AI Symbol Counting', desc: 'Devices and fixtures recognised by symbol and counted across every sheet, then presented for confirmation against the legend.' },
      { icon: 'ic-sched',  title: 'Schedule Reconciliation', desc: 'Counted fixtures and equipment cross-checked against the fixture and panel schedules, with mismatches flagged as RFI candidates.' },
      { icon: 'ic-layout', title: 'Homerun Measurement', desc: 'Circuit runs measured to their panel, with routing factors and vertical drop allowances applied per area and shown as applied.' },
      { icon: 'ic-chart',  title: 'One-Line Feeder Takeoff', desc: 'Feeder sizes and lengths read from the one-line diagram, with conduit, conductors and grounding sized accordingly.' },
      { icon: 'ic-users',  title: 'Labor Units', desc: 'Install hours per device, fixture and hundred feet of conduit from your own history or an industry base you adjust.' },
      { icon: 'ic-percent',title: 'Condition Factors', desc: 'Height, occupancy, after-hours and exposed-versus-concealed applied as visible productivity factors rather than a gut adjustment at the end.' },
      { icon: 'ic-db',     title: 'Material Pricing', desc: 'Wire, conduit, fittings and gear priced from your supplier pricing, with volatile items flagged for a fresh quote before submission.' },
      { icon: 'ic-pkg',    title: 'Gear and Lead Times', desc: 'Distribution equipment tracked as counted items with lead-time notes, because switchgear delivery now decides schedules.' },
      { icon: 'ic-layers', title: 'Multi-Level Takeoff', desc: 'Every floor measured in one pass, with quantities grouped by level, panel or phase.' },
      { icon: 'ic-refresh',title: 'Revision Comparison', desc: 'A re-issued lighting or power plan is compared against the last, so added devices are flagged instead of found later.' },
      { icon: 'ic-dl',     title: 'Excel Export', desc: 'Counts, runs and priced estimates exported to Excel or CSV with sheet references on every line.' },
      { icon: 'ic-file',   title: 'Bid-Ready Proposals', desc: 'A proposal drafted from the priced estimate, carrying the inclusions, exclusions and allowances you actually assumed.' },
    ],
  },
  csi: {
    h2: 'Electrical Spec Coverage',
    lead: 'Division 26 with the 27 and 28 sections that usually arrive attached to it.',
    rows: [
      { n: '26 05 00', l: 'Common work results — conductors, raceway, boxes' },
      { n: '26 05 19', l: 'Low-voltage conductors and cables' },
      { n: '26 05 33', l: 'Raceways and boxes' },
      { n: '26 22 00', l: 'Low-voltage transformers' },
      { n: '26 24 00', l: 'Switchboards and panelboards' },
      { n: '26 27 00', l: 'Low-voltage distribution equipment' },
      { n: '26 32 00', l: 'Packaged generator assemblies' },
      { n: '26 51 00', l: 'Interior lighting' },
      { n: '27 10 00', l: 'Structured cabling' },
      { n: '28 31 00', l: 'Fire detection and alarm' },
    ],
  },
  projectsLead: 'Fit-outs, hospitals, schools, data halls and industrial plants — device counts scale, the method does not change.',
  workflow: {
    h2: 'How an Electrical Estimate Comes Together',
    lead: 'Count, connect, size, price — with the assumptions written down at each step.',
    steps: [
      { t: 'Upload the electrical set', s: 'Power and lighting plans, the one-line diagram, panel and fixture schedules, the symbol legend and the Division 26 specification sections.' },
      { t: 'Devices and fixtures counted', s: 'Symbols are recognised and counted by type across every level, then reconciled against the fixture schedule and the legend so a mismatch surfaces early.' },
      { t: 'Circuits measured', s: 'Homeruns are measured to their panels, with routing factors and drop allowances applied per area type and displayed rather than buried in a rate.' },
      { t: 'Feeders sized from the one-line', s: 'Feeder runs, sizes and lengths come off the one-line, with conduit, conductors, grounding and terminations sized to match.' },
      { t: 'Gear and systems added', s: 'Panels, switchgear, transformers and generators are counted from the schedules with lead times noted, along with fire alarm, data and security scope.' },
      { t: 'Labor units applied', s: 'Each item carries an install unit from your own productivity history, with condition factors for height, occupancy and after-hours work applied visibly.' },
      { t: 'Priced and delivered', s: 'Material priced against your supplier pricing, labor against your rates, exported to Excel with a marked-up drawing set behind every count.' },
    ],
  },
  benefits: {
    eyebrow: 'Benefits',
    h2: 'What Changes on an Electrical Bid',
    lead: 'The estimate stops being a total and becomes a set of statements you can defend.',
    cards: [
      { icon: 'ic-plus',   title: 'Counts That Match the Schedule', desc: 'Automatic reconciliation against the fixture and panel schedules catches the miscounts and drawing conflicts that otherwise surface after award.' },
      { icon: 'ic-percent',title: 'Assumptions in the Open', desc: 'Routing factors and drop allowances shown as applied mean a bid comparison can be about scope rather than about two opaque numbers.' },
      { icon: 'ic-users',  title: 'Labor Units That Are Yours', desc: 'Industry labor units are a starting point. Your crews\' actual productivity is the number that predicts your cost, and it belongs in the estimate.' },
      { icon: 'ic-pkg',    title: 'Gear Lead Times Visible', desc: 'Switchgear and transformer lead times now drive schedules more than installation does. Tracking them at bid time is a scheduling decision, not an afterthought.' },
      { icon: 'ic-zap',    title: 'Faster Counting', desc: 'Symbol recognition across a full set removes the slowest, most error-prone part of electrical takeoff — the part where an estimator loses their place at 11pm.' },
      { icon: 'ic-refresh',title: 'Addenda Handled', desc: 'A re-issued lighting plan is compared to the previous one, so twelve added fixtures are a flagged difference rather than a discovery on site.' },
    ],
  },
  why: {
    h2: 'Why Electrical Contractors Use BidcoreAI',
    lead: 'Because an electrical estimate is a stack of assumptions, and they should be legible.',
    items: [
      { icon: 'ic-brain',  t: 'Counting you can check', s: 'Every counted symbol is shown on its sheet and reconciled against the schedule. Reviewing is faster than counting, and far more accurate.' },
      { icon: 'ic-percent',t: 'Routing factors visible', s: 'Drop and routing allowances are inputs you set and see, not constants hidden inside a unit price.' },
      { icon: 'ic-users',  t: 'Labor units from your jobs', s: 'Install hours come from your own completed work, adjusted by condition factors you control.' },
      { icon: 'ic-chart',  t: 'One-line read properly', s: 'Feeders sized and measured from the one-line rather than approximated off the floor plan.' },
      { icon: 'ic-cloud',  t: 'Browser-based', s: 'No workstation licence, and the marked-up set opens on a tablet in the field.' },
      { icon: 'ic-users',  t: 'Estimators available', s: 'When the volume spikes, <a href="/electrical-estimating-services">electrical estimating services</a> run in this same platform.' },
    ],
  },
  faqs: [
    { q: 'What is electrical estimating software?', a: 'Electrical estimating software counts the devices, fixtures and equipment on the electrical drawings, measures the circuits and feeders that connect them, and applies labor units and material pricing to produce a bid. The counting is measurement; the wire and conduit quantities depend on routing assumptions, and good software makes those assumptions explicit rather than hiding them in a rate.' },
    { q: 'How does it count devices and fixtures?', a: 'Symbols are recognised across every sheet and counted by type, then reconciled against the fixture schedule, panel schedules and symbol legend. Each count is shown on its drawing for confirmation, and a count that disagrees with the schedule is flagged — usually the first sign of a drawing conflict worth an RFI.' },
    { q: 'How are conduit and wire quantities calculated?', a: 'Homeruns are measured to their panel on the plan, then adjusted by a routing factor and a vertical drop allowance set per area type. Both are shown as applied. This is honest about what is knowable: plan length is measurable, but the route through structure and above ceilings is an estimating judgement, and the number should say so.' },
    { q: 'Does it use labor units?', a: 'Yes. Every item carries an install unit — hours per device, per fixture, per hundred feet of conduit by size and installation method. You can start from an industry base and adjust it, or import your own productivity history, which is the better long-term answer because it reflects your crews rather than an average.' },
    { q: 'Can it take feeders off the one-line diagram?', a: 'Yes. Feeder runs, sizes and lengths are read from the one-line, and conduit, conductors, grounding and terminations are sized to match. Approximating feeders from the floor plan is one of the larger avoidable errors in electrical estimating, particularly on multi-storey risers.' },
    { q: 'Does it handle fire alarm, data and security?', a: 'Yes. Division 27 and 28 scope — fire alarm devices and wiring, structured cabling, racks, security, access control and CCTV — is counted and priced alongside Division 26, since it typically lands on the same contractor whether or not it was drawn on the same sheets.' },
    { q: 'Can I apply productivity factors for difficult conditions?', a: 'Yes, and they stay visible. Work above 15 feet, occupied buildings, after-hours shifts, exposed versus concealed installation and rigid versus EMT each apply as a factor you set, rather than as an unexplained adjustment made to the bottom line at the end.' },
    { q: 'Does it track equipment lead times?', a: 'Yes. Panels, switchgear, transformers and generators are counted from the schedules with lead-time notes attached. Given current delivery times on distribution equipment, knowing this at bid time is a scheduling input rather than a procurement detail.' },
    { q: 'Can I use my own supplier pricing?', a: 'Yes. Import your supplier pricing for wire, conduit, fittings and gear. Volatile items are flagged so they can be re-quoted before submission rather than carried at a price that was current three months ago.' },
    { q: 'Can BidcoreAI estimate the electrical package for me?', a: 'Yes. <a href="/electrical-estimating-services">Electrical estimating services</a> are staffed by estimators working in this same platform, returning counts, measured runs, a priced estimate and a marked-up drawing set, typically within 24 to 72 hours.' },
  ],
  service: {
    h2: 'Electrical Estimating Services',
    body: 'Send the power and lighting plans, the one-line and the schedules, and have the package counted and priced for you — devices and fixtures by type, homeruns and feeders with the routing assumptions stated, gear from the schedules, priced against your own labor units.',
    href: '/electrical-estimating-services',
    label: 'Electrical Estimating Services',
  },
  related: [
    'plumbing-estimating-software',
    'hvac-estimating-software',
    'fire-protection-estimating-software',
    'construction-estimating-software',
    'construction-takeoff-software',
    'quantity-takeoff-software',
    'drywall-estimating-software',
    'sitework-estimating-software',
  ],
  cta: {
    h2: 'Count a Set You Have Already Bid',
    lead: 'Compare the device counts, the feeder lengths and the labor hours against what you submitted.',
  },
},

/* ══════════════════ PLUMBING ══════════════════ */
{
  slug: 'plumbing-estimating-software',
  name: 'Plumbing Estimating Software',
  h1: 'Plumbing Estimating Software for Fixtures, Pipe and Underground',
  title: 'Plumbing Estimating Software for Contractors | BidcoreAI',
  description: 'Plumbing estimating software: fixture counts from the schedules, pipe by size and material, underground and above-ground separated, priced on your labor units.',
  keywords: 'plumbing estimating software, plumbing takeoff software, pipe takeoff software, plumbing bid software, mechanical plumbing estimating, plumbing contractor software',
  eyebrow: 'CSI Division 22 · Plumbing',
  eyebrowIcon: 'ic-filter',
  heroLead: 'Plumbing estimating software for plumbing and mechanical contractors. Fixtures counted from the schedules, pipe measured by size and material with fittings counted rather than factored, and underground kept separate from above-ground because they are different jobs with different crews.',
  pills: [
    { icon: 'ic-plus',   text: 'Fixtures from the schedule' },
    { icon: 'ic-layout', text: 'Pipe by size and material' },
    { icon: 'ic-db',     text: 'Underground separated' },
  ],
  card: {
    eyebrow: 'What a plumbing estimate needs',
    headline: 'Fixtures, systems, and depth',
    sub: 'Same fixture count, different site conditions — and the underground is where the money moves',
    items: [
      'Fixtures by type with rough-in and trim',
      'Pipe by system, size and material',
      'Fittings, valves and hangers counted',
      'Underground pipe with trench and bedding',
      'Equipment: heaters, pumps, interceptors',
    ],
  },
  intro: {
    eyebrow: 'What it is',
    h2: 'The Fixture Count Is Never the Risk',
    paras: [
      'Every plumbing estimator can count fixtures. The schedule says how many water closets, lavatories, sinks, showers and floor drains, and the plans say roughly where they go. If plumbing bids varied only by fixture count they would all land within a few per cent of each other. They do not, and the variation comes almost entirely from three places: how the pipe was measured, whether the fittings were counted or factored, and what was assumed about the underground.',
      'BidcoreAI treats those three as first-class. Pipe is measured by system, size and material — domestic hot, domestic cold, sanitary waste, vent, storm, gas — with the risers taken from the riser diagram rather than inferred from a floor plan that shows none of the vertical distance. Fittings are counted from the drawings where they are drawn and applied by a stated ratio where they are not, with which of the two happened visible on the line item. Hangers, supports, sleeves and firestopping are quantified rather than absorbed.',
      'Underground is estimated as its own scope because it is its own job. Below-slab sanitary and storm, trench depth, bedding, backfill, compaction, and the interface with the site utilities contractor are separated from the above-ground rough-in, with different crews and different productivity. Bidding underground at above-ground rates is one of the most reliable ways to lose money on a plumbing package, and it happens because the drawings make the two look like the same lines.',
      'Fixtures themselves carry their rough-in, carriers, trim and connection scope, so a wall-hung water closet is not priced like a floor-mounted one. Equipment — water heaters, booster pumps, grease interceptors, backflow preventers, mixing valves — is counted from the schedules with its connections and its lead times noted.',
    ],
  },
  measures: {
    eyebrow: 'Scope',
    icon: 'ic-filter',
    h2: 'What the Software Takes Off on a Plumbing Package',
    lead: 'Plumbing plans, riser diagrams, fixture and equipment schedules, and the underground plan.',
    cards: [
      {
        icon: 'ic-plus', title: 'Fixtures',
        desc: 'Counted by schedule type, with rough-in, carriers and trim carried per fixture.',
        items: ['Water closets, lavatories, sinks', 'Showers, tubs and drinking fountains', 'Floor drains, hub drains, cleanouts', 'Carriers, trim and connection scope'],
      },
      {
        icon: 'ic-layout', title: 'Above-Ground Piping',
        desc: 'Measured by system, size and material, with risers taken from the riser diagram.',
        items: ['Domestic hot and cold water', 'Sanitary waste and vent', 'Storm and roof drainage', 'Natural gas and compressed air'],
      },
      {
        icon: 'ic-db', title: 'Underground Piping',
        desc: 'Kept as separate scope with trench, bedding and backfill priced with it.',
        items: ['Below-slab sanitary and storm', 'Trench depth, bedding and backfill', 'Site utility connection points', 'Rock, dewatering and shoring risk'],
      },
      {
        icon: 'ic-pkg', title: 'Fittings and Valves',
        desc: 'Counted where drawn and applied by a stated ratio where not, with which one visible.',
        items: ['Elbows, tees, couplings and reducers', 'Isolation, balancing and check valves', 'Cleanouts and access points', 'Dielectric unions and expansion'],
      },
      {
        icon: 'ic-tool', title: 'Supports and Penetrations',
        desc: 'Quantified rather than absorbed, because on a tall building they are a real number.',
        items: ['Hangers, supports and seismic bracing', 'Sleeves and wall penetrations', 'Firestopping at rated assemblies', 'Insulation by system and thickness'],
      },
      {
        icon: 'ic-cpu', title: 'Equipment',
        desc: 'Counted from the schedules with connections, controls and lead times noted.',
        items: ['Water heaters and storage tanks', 'Booster and sump pumps', 'Grease and oil interceptors', 'Backflow preventers and mixing valves'],
      },
    ],
  },
  features: {
    eyebrow: 'Features',
    h2: 'Plumbing Estimating Features',
    lead: 'Systems, sizes and depth — carried as data rather than remembered by the estimator.',
    cards: [
      { icon: 'ic-brain',  title: 'AI Fixture Counting', desc: 'Fixtures recognised by symbol across every level and reconciled against the fixture schedule and legend.' },
      { icon: 'ic-layout', title: 'Pipe by System and Size', desc: 'Runs measured and grouped by system, size and material, so the estimate reflects what is actually purchased.' },
      { icon: 'ic-chart',  title: 'Riser Diagram Takeoff', desc: 'Vertical distribution measured from the riser diagram rather than inferred from plans that contain no height information.' },
      { icon: 'ic-db',     title: 'Underground Separation', desc: 'Below-slab work is its own scope with trench, bedding, backfill and compaction priced alongside the pipe.' },
      { icon: 'ic-pkg',    title: 'Fitting Counts', desc: 'Fittings counted where drawn and applied by a stated ratio where not, with the method visible on the line item.' },
      { icon: 'ic-tool',   title: 'Hangers and Supports', desc: 'Support spacing by pipe size and material, plus seismic bracing where the specification requires it.' },
      { icon: 'ic-shield', title: 'Firestopping and Sleeves', desc: 'Rated penetrations counted from the plans and the rated wall types, priced as the scope it is.' },
      { icon: 'ic-layers', title: 'Insulation Quantities', desc: 'Pipe insulation by system, size and thickness, calculated from the same measured runs rather than re-measured.' },
      { icon: 'ic-users',  title: 'Labor Units by System', desc: 'Install hours per fixture, per fitting and per hundred feet of pipe, from your own productivity history.' },
      { icon: 'ic-refresh',title: 'Revision Comparison', desc: 'A re-issued plumbing plan compared against the previous one, so an added restroom group is flagged not missed.' },
      { icon: 'ic-dl',     title: 'Excel Export', desc: 'Fixture counts, pipe schedules and priced estimates exported with sheet references intact.' },
      { icon: 'ic-report', title: 'Material Summaries', desc: 'Pipe by size and material, fittings, valves and hangers summarised in order units for a supplier quote.' },
    ],
  },
  csi: {
    h2: 'Plumbing Spec Coverage',
    lead: 'Division 22, with the Division 21 and 33 interfaces kept where you can see them.',
    rows: [
      { n: '22 05 00', l: 'Common work results for plumbing' },
      { n: '22 05 23', l: 'Valves for plumbing piping' },
      { n: '22 07 00', l: 'Plumbing insulation' },
      { n: '22 11 00', l: 'Facility water distribution' },
      { n: '22 13 00', l: 'Facility sanitary sewerage' },
      { n: '22 14 00', l: 'Facility storm drainage' },
      { n: '22 30 00', l: 'Plumbing equipment' },
      { n: '22 40 00', l: 'Plumbing fixtures' },
      { n: '33 10 00', l: 'Water utilities (interface)' },
      { n: '33 30 00', l: 'Sanitary sewerage utilities (interface)' },
    ],
  },
  projectsLead: 'Healthcare, education, multifamily, hospitality and industrial — fixture density changes everything except the method.',
  workflow: {
    h2: 'How a Plumbing Estimate Comes Together',
    lead: 'Fixtures, then systems, then the part that happens before the slab is poured.',
    steps: [
      { t: 'Upload the plumbing set', s: 'Plumbing plans by level, the underground plan, riser diagrams, fixture and equipment schedules and the Division 22 specification sections.' },
      { t: 'Fixtures counted and reconciled', s: 'Fixtures are counted by symbol across every level and checked against the fixture schedule, with rough-in, carriers and trim carried per fixture type.' },
      { t: 'Above-ground pipe measured', s: 'Runs are measured by system, size and material, with vertical distribution taken from the riser diagram rather than assumed from the plan.' },
      { t: 'Underground taken off separately', s: 'Below-slab sanitary and storm are measured as their own scope, with trench depth, bedding, backfill and compaction priced alongside the pipe.' },
      { t: 'Fittings, supports and penetrations', s: 'Fittings counted or applied by a stated ratio, hangers spaced by size and material, sleeves and firestopping counted at rated assemblies.' },
      { t: 'Equipment and insulation added', s: 'Equipment counted from the schedules with connections and lead times; insulation calculated by system, size and thickness off the measured runs.' },
      { t: 'Priced and delivered', s: 'Material from your supplier pricing, labor from your own units, exported to Excel with a marked-up set and a written assumptions list.' },
    ],
  },
  benefits: {
    eyebrow: 'Benefits',
    h2: 'What Changes on a Plumbing Bid',
    lead: 'The differences between two bids become visible, which is usually all anyone wanted.',
    cards: [
      { icon: 'ic-db',     title: 'Underground Priced as Underground', desc: 'Separating below-slab scope with its trench and backfill stops the single most expensive category error in plumbing bidding.' },
      { icon: 'ic-chart',  title: 'Risers From the Riser Diagram', desc: 'Vertical pipe measured where the height information actually is removes a systematic shortfall on every multi-storey job.' },
      { icon: 'ic-pkg',    title: 'Fittings Counted Honestly', desc: 'Showing whether fittings were counted or factored means a low bid can be examined rather than simply envied.' },
      { icon: 'ic-tool',   title: 'Supports Quantified', desc: 'Hangers, sleeves and firestopping add up to real money on a tall building, and they are the first things to vanish into a per-foot rate.' },
      { icon: 'ic-plus',   title: 'Fixtures With Their Scope', desc: 'Carriers, trim and rough-in carried per fixture type means a wall-hung group is not priced as though it were floor-mounted.' },
      { icon: 'ic-report', title: 'Orderable Material Lists', desc: 'Pipe by size and material with fittings and valves in order units, ready for supplier pricing while the estimate is still open.' },
    ],
  },
  why: {
    h2: 'Why Plumbing Contractors Use BidcoreAI',
    lead: 'Because the risk in a plumbing bid is never the fixture count.',
    items: [
      { icon: 'ic-db',     t: 'Underground is its own scope', s: 'Trench, bedding, backfill and compaction priced with the below-slab pipe, at below-slab productivity.' },
      { icon: 'ic-chart',  t: 'Riser diagrams read', s: 'Vertical distribution measured from the drawing that shows height, not estimated from one that does not.' },
      { icon: 'ic-pkg',    t: 'Fittings method visible', s: 'Counted or factored, the line item says which — so a reviewer can judge the number instead of trusting it.' },
      { icon: 'ic-users',  t: 'Your labor units', s: 'Install hours per fixture, fitting and hundred feet from your own completed jobs.' },
      { icon: 'ic-cloud',  t: 'Browser-based', s: 'No workstation licence; the marked-up set opens on a tablet in the field.' },
      { icon: 'ic-users',  t: 'Estimators available', s: 'Plumbing packages can be measured and priced for you through <a href="/mep-estimating-services">MEP estimating services</a>.' },
    ],
  },
  faqs: [
    { q: 'What is plumbing estimating software?', a: 'Plumbing estimating software counts fixtures and equipment, measures pipe by system, size and material, quantifies fittings, hangers and penetrations, and prices the result using labor units. A complete one keeps underground scope separate from above-ground, because they are performed by different crews at different productivities and priced from different assumptions.' },
    { q: 'How is pipe measured?', a: 'By system, size and material — domestic hot and cold, sanitary, vent, storm, gas — with horizontal runs measured on the plans and vertical distribution taken from the riser diagram. Measuring risers off a floor plan is a systematic underestimate on any multi-storey building, because the plan carries no height information at all.' },
    { q: 'Are fittings counted or factored?', a: 'Both, depending on the drawings, and the line item says which. Where fittings are drawn they are counted. Where they are not, a stated ratio is applied per system and size. Making the method visible is the point: it lets a reviewer judge whether a low number is efficiency or optimism.' },
    { q: 'Does it handle underground plumbing?', a: 'Yes, as separate scope. Below-slab sanitary and storm are measured on their own, and trench depth, bedding, backfill and compaction are priced alongside the pipe, along with the interface to the site utility contractor. Pricing underground at above-ground rates is one of the most common ways a plumbing package loses money.' },
    { q: 'Does it include hangers, sleeves and firestopping?', a: 'Yes. Hanger spacing follows pipe size and material, sleeves and penetrations are counted from the plans and the rated wall types, and firestopping is quantified at rated assemblies. On a tall building these are a meaningful cost that disappears entirely into a per-foot rate.' },
    { q: 'Can it estimate pipe insulation?', a: 'Yes, by system, size and thickness, calculated from the same measured runs rather than re-measured separately. Insulation on domestic hot water and storm piping is frequently under-carried because it is estimated as an afterthought.' },
    { q: 'How are fixtures priced?', a: 'By schedule type, with rough-in, carriers, trim and connection scope carried per type. A wall-hung water closet with a carrier is a materially different cost from a floor-mounted one, and the fixture schedule is what distinguishes them.' },
    { q: 'Can I use my own labor units?', a: 'Yes. Install hours per fixture, per fitting and per hundred feet of pipe come from your own productivity history, adjusted by condition factors for occupied buildings, height and after-hours work. An industry base is available where you have no history.' },
    { q: 'Does it produce a material list for suppliers?', a: 'Yes. Pipe by size and material, fittings, valves, hangers and insulation summarise in order units and export to Excel, ready to send for supplier pricing while the estimate is still being assembled.' },
    { q: 'Can BidcoreAI estimate the plumbing package for me?', a: 'Yes. <a href="/mep-estimating-services">MEP estimating services</a> cover plumbing packages, staffed by estimators working in this platform, returning counts, measured pipe, a priced estimate and a marked-up drawing set.' },
  ],
  service: {
    h2: 'Plumbing and MEP Estimating Services',
    body: 'Send the plumbing set, riser diagrams and schedules and have the package measured for you: fixtures by type with their rough-in, pipe by system and size, underground separated with its trench and backfill, and equipment counted with lead times noted.',
    href: '/mep-estimating-services',
    label: 'MEP Estimating Services',
  },
  related: [
    'hvac-estimating-software',
    'electrical-estimating-software',
    'fire-protection-estimating-software',
    'sitework-estimating-software',
    'earthwork-estimating-software',
    'construction-estimating-software',
    'quantity-takeoff-software',
    'construction-takeoff-software',
  ],
  cta: {
    h2: 'Take Off a Plumbing Set You Know',
    lead: 'Compare the pipe by size, the fitting counts and the underground line against the bid you submitted.',
  },
},

/* ══════════════════ HVAC ══════════════════ */
{
  slug: 'hvac-estimating-software',
  name: 'HVAC Estimating Software',
  h1: 'HVAC Estimating Software for Equipment, Duct and Piping',
  title: 'HVAC Estimating Software for Contractors | BidcoreAI',
  description: 'HVAC estimating software: equipment from the schedules, duct by size converted to pounds of metal, hydronic piping and controls, priced on your labor units.',
  keywords: 'hvac estimating software, ductwork takeoff software, mechanical estimating software, hvac takeoff software, sheet metal estimating software, hvac bid software',
  eyebrow: 'CSI Division 23 · HVAC',
  eyebrowIcon: 'ic-cloud',
  heroLead: 'HVAC estimating software for mechanical and sheet metal contractors. Equipment counted from the schedules with its connections, duct measured by size and converted to pounds of metal by gauge, hydronic and refrigerant piping measured by system, and controls priced as their own scope.',
  pills: [
    { icon: 'ic-chart', text: 'Duct in pounds by gauge' },
    { icon: 'ic-plus',  text: 'Equipment with hookups' },
    { icon: 'ic-tool',  text: 'Controls scoped' },
  ],
  card: {
    eyebrow: 'What an HVAC estimate needs',
    headline: 'Metal, machines and controls',
    sub: 'Duct is bought by weight, equipment by unit, and controls by point count — three different logics',
    items: [
      'Equipment by schedule tag with connections',
      'Duct by size, gauge, weight and liner',
      'Fittings counted, not carried as a percentage',
      'Hydronic and refrigerant piping by system',
      'Controls, dampers, test and balance',
    ],
  },
  intro: {
    eyebrow: 'What it is',
    h2: 'Three Different Estimates Wearing One Name',
    paras: [
      'An HVAC package is really three estimates sharing a cover sheet. The equipment is a counted list off the schedules with connection, rigging and start-up scope attached. The ductwork is a fabrication estimate priced by weight of metal, gauge, seam type and lining. The piping is a mechanical estimate priced by size, material and fitting count. Each has its own units and its own labor logic, and folding them into a single square-foot rate is how a mechanical bid ends up either uncompetitive or unprofitable, with no way to tell which until the job is running.',
      'BidcoreAI keeps them separate. Equipment — air handlers, rooftop units, VAV boxes, fan coils, pumps, chillers, boilers, exhaust fans — is counted from the schedules by tag, with electrical connection, structural support, curbs, rigging, start-up and commissioning carried per unit. Lead times are noted, because on current schedules a rooftop unit delivery is a project constraint rather than a procurement detail.',
      'Ductwork is measured by run and size, then converted to pounds of metal by gauge according to SMACNA construction class, with fittings counted rather than added as a blanket percentage. Liner and external insulation are calculated by surface area from the same measurement. That is what makes the number quotable by a fabrication shop, and comparable against a shop\'s own price, instead of being a linear-foot figure only the estimator can interpret.',
      'Piping is measured by system — chilled water, heating hot water, condenser, refrigerant, condensate — by size and material, with fittings, valves, hangers and insulation quantified. Controls are scoped separately by point count and device type, along with dampers, sensors, test and balance and commissioning, all of which are routinely under-carried because they appear on a different set of drawings than the ductwork does.',
    ],
  },
  measures: {
    eyebrow: 'Scope',
    icon: 'ic-cloud',
    h2: 'What the Software Takes Off on an HVAC Package',
    lead: 'Mechanical plans, equipment schedules, duct layouts, piping diagrams and the controls drawings.',
    cards: [
      {
        icon: 'ic-cpu', title: 'Equipment',
        desc: 'Counted by schedule tag, with the connection and start-up scope each unit brings with it.',
        items: ['AHUs, RTUs and split systems', 'VAV boxes, fan coils and unit heaters', 'Chillers, boilers and pumps', 'Curbs, rigging, start-up and lead times'],
      },
      {
        icon: 'ic-layers', title: 'Ductwork',
        desc: 'Measured by run and size, converted to pounds of metal by gauge and construction class.',
        items: ['Rectangular duct by size and gauge', 'Round and oval duct by diameter', 'Pounds of metal by construction class', 'Liner, wrap and external insulation'],
      },
      {
        icon: 'ic-pkg', title: 'Duct Fittings and Devices',
        desc: 'Counted individually, because a fitting-heavy layout costs far more than its linear feet suggest.',
        items: ['Elbows, transitions and takeoffs', 'Dampers, fire and smoke dampers', 'Diffusers, registers and grilles', 'Flex duct runs and connections'],
      },
      {
        icon: 'ic-layout', title: 'Hydronic Piping',
        desc: 'Measured by system, size and material with fittings, valves and specialties counted.',
        items: ['Chilled and heating hot water', 'Condenser and glycol systems', 'Refrigerant and condensate', 'Valves, specialties and hangers'],
      },
      {
        icon: 'ic-tool', title: 'Controls and BAS',
        desc: 'Scoped by point count and device type rather than carried as a percentage of the mechanical value.',
        items: ['Control points by device', 'Sensors, actuators and valves', 'Panels, wiring and integration', 'Sequences and graphics'],
      },
      {
        icon: 'ic-check', title: 'Commissioning and Balance',
        desc: 'The end-of-job scope that is real work and is almost always under-carried at bid.',
        items: ['Test and balance by terminal', 'Commissioning support hours', 'Duct leakage testing', 'O&amp;M documentation and training'],
      },
    ],
  },
  features: {
    eyebrow: 'Features',
    h2: 'HVAC Estimating Features',
    lead: 'Sheet metal weight, equipment schedules and control points — the three units the trade actually prices in.',
    cards: [
      { icon: 'ic-brain',  title: 'AI Duct Takeoff', desc: 'Duct runs detected and measured by size across the mechanical plans, with fittings identified and counted individually.' },
      { icon: 'ic-chart',  title: 'Pounds of Metal by Gauge', desc: 'Measured duct converted to weight by gauge and SMACNA construction class, which is how a fabrication shop prices it.' },
      { icon: 'ic-sched',  title: 'Equipment Schedule Reading', desc: 'Units extracted by tag from the schedules, reconciled against the plans, with connection and start-up scope per unit.' },
      { icon: 'ic-layers', title: 'Liner and Insulation Areas', desc: 'Internal liner and external wrap calculated by surface area from the same duct measurement, not estimated separately.' },
      { icon: 'ic-layout', title: 'Piping by System', desc: 'Hydronic, refrigerant and condensate runs measured by size and material, with fittings, valves and specialties counted.' },
      { icon: 'ic-tool',   title: 'Controls Point Counting', desc: 'Control points, sensors and actuators counted by device, so the BAS scope is priced rather than allowed for.' },
      { icon: 'ic-shield', title: 'Fire and Smoke Dampers', desc: 'Counted at rated assemblies from the plans and the rated wall types, with access panels carried alongside them.' },
      { icon: 'ic-users',  title: 'Fabrication and Field Labor', desc: 'Shop fabrication and field installation hours estimated separately against your own productivity data.' },
      { icon: 'ic-pkg',    title: 'Rigging and Access', desc: 'Crane picks, roof access and equipment routing priced as their own lines instead of assumed into an equipment rate.' },
      { icon: 'ic-refresh',title: 'Revision Comparison', desc: 'A re-issued mechanical plan compared against the previous one so a re-routed duct main is flagged, not missed.' },
      { icon: 'ic-dl',     title: 'Excel Export', desc: 'Duct schedules by size and weight, equipment lists and priced estimates exported with sheet references.' },
      { icon: 'ic-report', title: 'Fabrication Summaries', desc: 'Duct summarised by size, gauge and weight for a shop quote, alongside the estimate itself.' },
    ],
  },
  csi: {
    h2: 'HVAC Spec Coverage',
    lead: 'Division 23, with the controls and commissioning sections kept visible instead of assumed.',
    rows: [
      { n: '23 05 00', l: 'Common work results for HVAC' },
      { n: '23 07 00', l: 'HVAC insulation' },
      { n: '23 09 00', l: 'Instrumentation and control for HVAC' },
      { n: '23 21 00', l: 'Hydronic piping and pumps' },
      { n: '23 31 00', l: 'HVAC ducts and casings' },
      { n: '23 33 00', l: 'Air duct accessories' },
      { n: '23 34 00', l: 'HVAC fans' },
      { n: '23 37 00', l: 'Air outlets and inlets' },
      { n: '23 64 00', l: 'Packaged water chillers' },
      { n: '23 74 00', l: 'Packaged outdoor HVAC equipment' },
    ],
  },
  projectsLead: 'Offices, hospitals, schools, labs and industrial plants — where the equipment schedule sets the tone for the whole bid.',
  workflow: {
    h2: 'How an HVAC Estimate Comes Together',
    lead: 'Equipment first, then metal, then the scope hiding on the controls drawings.',
    steps: [
      { t: 'Upload the mechanical set', s: 'Mechanical plans, equipment schedules, duct layouts, piping and riser diagrams, control drawings and the Division 23 specification sections.' },
      { t: 'Equipment counted from schedules', s: 'Units are extracted by tag and reconciled against the plans, with curbs, connections, rigging, start-up and lead times carried per unit.' },
      { t: 'Duct measured by size', s: 'Runs are measured across the set by size and shape, with fittings, dampers and terminal devices counted individually rather than factored in.' },
      { t: 'Converted to pounds of metal', s: 'Duct converts to weight by gauge and SMACNA construction class, and liner and external insulation are calculated by surface area from the same measurement.' },
      { t: 'Piping measured by system', s: 'Chilled water, hot water, condenser, refrigerant and condensate measured by size and material, with fittings, valves, hangers and insulation quantified.' },
      { t: 'Controls and commissioning scoped', s: 'Control points counted by device, with panels, wiring and integration priced, plus test and balance by terminal and commissioning support hours.' },
      { t: 'Priced and delivered', s: 'Shop and field labor priced separately against your own rates, material from your supplier pricing, exported to Excel with a fabrication summary and a marked-up set.' },
    ],
  },
  benefits: {
    eyebrow: 'Benefits',
    h2: 'What Changes on a Mechanical Bid',
    lead: 'Each of the three sub-estimates gets priced in its own currency.',
    cards: [
      { icon: 'ic-chart',  title: 'Duct a Shop Can Quote', desc: 'Pounds of metal by gauge and class is the number a fabrication shop prices from. Linear feet is a number only the estimator can interpret.' },
      { icon: 'ic-pkg',    title: 'Fittings Counted', desc: 'A tight mechanical room with forty fittings per hundred feet costs nothing like an open ceiling run. Counting them is the only way that shows up.' },
      { icon: 'ic-tool',   title: 'Controls Actually Priced', desc: 'Point-count scoping replaces the percentage-of-mechanical habit, which is consistently low on projects with dense terminal units.' },
      { icon: 'ic-sched',  title: 'Lead Times Known at Bid', desc: 'Equipment delivery is now a schedule driver. Capturing it during the estimate turns it into a planning input rather than a mid-job surprise.' },
      { icon: 'ic-check',  title: 'Commissioning Carried', desc: 'Test and balance, duct leakage testing and commissioning support are real hours that get remembered after award if they are not counted before it.' },
      { icon: 'ic-users',  title: 'Shop and Field Separated', desc: 'Fabrication and installation productivity differ. Estimating them separately is what makes the labor number reviewable.' },
    ],
  },
  why: {
    h2: 'Why Mechanical Contractors Use BidcoreAI',
    lead: 'Because an HVAC bid has three units of measure and one of them is weight.',
    items: [
      { icon: 'ic-chart',  t: 'Metal by weight and gauge', s: 'Duct converts to pounds by construction class, the unit a fabrication shop actually quotes against.' },
      { icon: 'ic-sched',  t: 'Schedules read directly', s: 'Equipment extracted by tag with connections, curbs, rigging and start-up carried per unit rather than remembered.' },
      { icon: 'ic-tool',   t: 'Controls by point count', s: 'The BAS scope is estimated as devices and points, not as a percentage of everything else.' },
      { icon: 'ic-users',  t: 'Shop and field split', s: 'Fabrication and installation hours estimated separately against your own productivity history.' },
      { icon: 'ic-cloud',  t: 'Browser-based', s: 'No workstation licence; measure from the office, the shop or a jobsite trailer.' },
      { icon: 'ic-users',  t: 'Estimators available', s: 'HVAC packages can be measured and priced for you through <a href="/hvac-estimating-services">HVAC estimating services</a>.' },
    ],
  },
  faqs: [
    { q: 'What is HVAC estimating software?', a: 'HVAC estimating software measures and prices the three parts of a mechanical package: equipment counted from the schedules, ductwork measured and converted to pounds of metal by gauge, and piping measured by system and size. It also scopes controls, dampers, test and balance and commissioning, which are frequently under-carried because they live on different drawings.' },
    { q: 'How is ductwork estimated?', a: 'Runs are measured by size and shape across the mechanical plans, fittings are counted individually, and the result converts to pounds of metal by gauge and SMACNA construction class. Weight is the unit a fabrication shop prices in, which makes the estimate directly comparable against a shop quote rather than requiring interpretation.' },
    { q: 'Why does duct weight matter more than linear feet?', a: 'Because sheet metal is bought and fabricated by weight, and two runs of identical length can differ substantially in cost depending on size, gauge, seam type and lining. Linear feet also says nothing about fitting density, which is often the largest single driver of fabrication hours.' },
    { q: 'Does it count duct fittings?', a: 'Yes, individually — elbows, transitions, takeoffs, offsets, dampers and terminal devices. Applying a blanket percentage for fittings works acceptably on open ceiling runs and badly in congested mechanical rooms, which is where the fittings actually are.' },
    { q: 'How is equipment handled?', a: 'Units are extracted from the equipment schedules by tag and reconciled against the plans, with curbs, structural support, electrical connection, rigging, start-up and commissioning carried per unit. Lead times are noted, since equipment delivery is currently a schedule constraint on most projects.' },
    { q: 'Does it estimate hydronic piping?', a: 'Yes. Chilled water, heating hot water, condenser, glycol, refrigerant and condensate systems are measured by size and material, with fittings, valves, specialties, hangers and insulation quantified from the same measured runs.' },
    { q: 'Are controls included?', a: 'Yes, scoped by point count and device type — sensors, actuators, control valves, panels, wiring and integration — rather than carried as a percentage of the mechanical value. On projects with many terminal units, the percentage method is reliably short.' },
    { q: 'Does it separate shop fabrication from field labor?', a: 'Yes. Fabrication and field installation hours are estimated separately against your own productivity data, because they are different work performed by different people at different rates, and blending them makes the labor number impossible to review.' },
    { q: 'Can it export a fabrication summary?', a: 'Yes. Duct summarises by size, gauge and weight for a shop quote, alongside equipment lists, piping schedules and the priced estimate, all exportable to Excel or CSV with sheet references intact.' },
    { q: 'Can BidcoreAI estimate the HVAC package for me?', a: 'Yes. <a href="/hvac-estimating-services">HVAC estimating services</a> are staffed by estimators working in this platform, returning equipment lists, duct schedules by weight, piping quantities and a priced estimate with the marked-up set behind it.' },
  ],
  service: {
    h2: 'HVAC Estimating Services',
    body: 'Send the mechanical set and schedules and have the package measured for you: equipment by tag with its connections and rigging, duct by size converted to pounds of metal, piping by system, controls by point count, and commissioning carried rather than forgotten.',
    href: '/hvac-estimating-services',
    label: 'HVAC Estimating Services',
  },
  related: [
    'plumbing-estimating-software',
    'electrical-estimating-software',
    'fire-protection-estimating-software',
    'roofing-estimating-software',
    'construction-estimating-software',
    'quantity-takeoff-software',
    'construction-takeoff-software',
    'metal-framing-estimating-software',
  ],
  cta: {
    h2: 'Weigh a Duct Package You Have Bid',
    lead: 'Compare the pounds of metal, the fitting count and the controls line against what you submitted.',
  },
},

/* ══════════════════ FIRE PROTECTION ══════════════════ */
{
  slug: 'fire-protection-estimating-software',
  name: 'Fire Protection Estimating Software',
  h1: 'Fire Protection Estimating Software for Sprinkler and Alarm',
  title: 'Fire Protection Estimating Software | BidcoreAI',
  description: 'Fire sprinkler estimating software: head counts by hazard, pipe by size and system, standpipes, pumps and alarm devices, priced against your own labor units.',
  keywords: 'fire protection estimating software, fire sprinkler estimating software, sprinkler takeoff software, fire alarm estimating software, standpipe estimating, nfpa 13 estimating',
  eyebrow: 'CSI Division 21 · Fire suppression',
  eyebrowIcon: 'ic-shield',
  heroLead: 'Fire protection estimating software for sprinkler and fire alarm contractors. Heads counted by hazard classification and coverage area, pipe measured by size and system type, standpipes and pumps taken from the risers, and alarm devices counted from the plans — all priced against your own labor units.',
  pills: [
    { icon: 'ic-plus',   text: 'Heads by hazard class' },
    { icon: 'ic-layout', text: 'Pipe by system' },
    { icon: 'ic-shield', text: 'NFPA-aware scope' },
  ],
  card: {
    eyebrow: 'What a fire protection estimate needs',
    headline: 'Coverage, then pipe',
    sub: 'Head count follows the hazard classification, and the hazard classification is in the specification',
    items: [
      'Head counts by hazard and coverage area',
      'Pipe by size, system type and material',
      'Standpipes, risers, valves and FDC',
      'Fire pumps, tanks and controllers',
      'Alarm devices, panels and wiring',
    ],
  },
  intro: {
    eyebrow: 'What it is',
    h2: 'The Hazard Classification Sets the Whole Bid',
    paras: [
      'Fire protection is one of the few trades where the specification determines the quantity before anyone measures anything. The hazard classification — light, ordinary group 1 or 2, extra hazard — sets the design density, and the density sets the maximum coverage area per sprinkler head. Change the classification of a storage area and the head count in that area changes with it, along with the pipe sizes feeding it. An estimator who counts heads off a drawing without checking the classification against the specification is counting somebody else\'s design.',
      'BidcoreAI reads the specification and the design criteria alongside the drawings. Head counts are derived from area and hazard classification where a layout is not yet drawn, and counted directly where it is, with the basis shown either way. Head types are separated — pendant, upright, sidewall, concealed, dry, extended coverage — because their costs and their installation times differ materially, and because a concealed head in a finished ceiling is a different job from an upright in a warehouse.',
      'Pipe is measured by system and size: wet, dry, pre-action, deluge and antifreeze loops each carry their own material, fittings and labor. Risers, standpipes, control valve assemblies, inspector test connections, drains and fire department connections are counted as assemblies rather than reduced to feet of pipe. Fire pumps, jockey pumps, controllers and tanks are counted from the schedules with their power, structural and start-up interfaces noted.',
      'The alarm side is estimated by device count — initiating devices, notification appliances, panels, annunciators and the wiring between them — with the interface to the electrical contractor stated explicitly. That interface is where fire protection scope most often falls between two bidders, and writing it down at estimate time is considerably cheaper than discovering it at the coordination meeting.',
    ],
  },
  measures: {
    eyebrow: 'Scope',
    icon: 'ic-shield',
    h2: 'What the Software Takes Off on a Fire Protection Package',
    lead: 'Sprinkler plans, riser diagrams, the fire alarm drawings and the design criteria in the specification.',
    cards: [
      {
        icon: 'ic-plus', title: 'Sprinkler Heads',
        desc: 'Counted by type and derived by coverage where the layout is design-build.',
        items: ['Heads by type and temperature rating', 'Coverage area by hazard classification', 'Concealed, pendant, upright, sidewall', 'Escutcheons, guards and spare stock'],
      },
      {
        icon: 'ic-layout', title: 'Sprinkler Piping',
        desc: 'Measured by system and size, with fittings, hangers and seismic bracing quantified.',
        items: ['Mains, cross mains and branch lines', 'Pipe by size, schedule and material', 'Fittings, couplings and hangers', 'Seismic bracing and sway restraints'],
      },
      {
        icon: 'ic-filter', title: 'Risers and Standpipes',
        desc: 'Counted as assemblies rather than dissolved into linear feet of pipe.',
        items: ['Riser and control valve assemblies', 'Standpipes and hose valves', 'Inspector test and drain assemblies', 'Fire department connections'],
      },
      {
        icon: 'ic-cpu', title: 'Pumps and Water Supply',
        desc: 'Equipment from the schedules with the interfaces that come attached to it.',
        items: ['Fire pumps and jockey pumps', 'Controllers and transfer switches', 'Storage tanks and suction piping', 'Backflow prevention and metering'],
      },
      {
        icon: 'ic-zap', title: 'Fire Alarm',
        desc: 'Devices counted from the alarm plans, with the electrical interface stated.',
        items: ['Initiating and notification devices', 'Panels, annunciators and power supplies', 'Wiring, conduit and pathway scope', 'Interface to electrical contractor'],
      },
      {
        icon: 'ic-check', title: 'Testing and Special Systems',
        desc: 'The end-of-job scope and the systems that fall outside a standard wet layout.',
        items: ['Hydrostatic testing and flushing', 'Clean agent and kitchen suppression', 'Pre-action and deluge systems', 'Inspection, commissioning and O&amp;M'],
      },
    ],
  },
  features: {
    eyebrow: 'Features',
    h2: 'Fire Protection Estimating Features',
    lead: 'Design criteria, head counts and system types — carried as data, not held in the estimator\'s head.',
    cards: [
      { icon: 'ic-brain',  title: 'AI Head Counting', desc: 'Sprinkler heads recognised and counted by type across every level, reconciled against the legend and the design criteria.' },
      { icon: 'ic-shield', title: 'Hazard Classification Aware', desc: 'Design density and coverage area read from the specification, so head counts can be derived where the layout is design-build.' },
      { icon: 'ic-layout', title: 'Pipe by System Type', desc: 'Wet, dry, pre-action and deluge measured separately by size and material, since each carries its own labor and fittings.' },
      { icon: 'ic-filter', title: 'Riser Assemblies', desc: 'Control valve assemblies, test connections, drains and FDCs counted as assemblies rather than reduced to pipe length.' },
      { icon: 'ic-tool',   title: 'Hangers and Seismic Bracing', desc: 'Support spacing by pipe size, with sway bracing quantified where the seismic design category requires it.' },
      { icon: 'ic-cpu',    title: 'Pump and Tank Scope', desc: 'Fire pumps, controllers and tanks counted from the schedules with their power, structural and start-up interfaces noted.' },
      { icon: 'ic-zap',    title: 'Fire Alarm Device Counts', desc: 'Initiating devices, notification appliances, panels and wiring counted, with the electrical interface written down.' },
      { icon: 'ic-users',  title: 'Labor Units by Head Type', desc: 'Install hours per head, per fitting and per hundred feet of pipe from your own productivity, by ceiling condition.' },
      { icon: 'ic-layers', title: 'Ceiling Condition Factors', desc: 'Finished ceiling, open deck and rack storage each carry their own productivity, applied as visible factors.' },
      { icon: 'ic-refresh',title: 'Revision Comparison', desc: 'A re-issued sprinkler or alarm plan compared against the last, so added devices are flagged rather than missed.' },
      { icon: 'ic-dl',     title: 'Excel Export', desc: 'Head schedules, pipe by size, device counts and priced estimates exported with sheet references.' },
      { icon: 'ic-report', title: 'Material Summaries', desc: 'Heads, pipe, fittings and hangers in order units, ready for a supplier or fabrication quote.' },
    ],
  },
  csi: {
    h2: 'Fire Protection Spec Coverage',
    lead: 'Division 21 with the Division 28 alarm sections that are usually bid alongside it.',
    rows: [
      { n: '21 05 00', l: 'Common work results for fire suppression' },
      { n: '21 11 00', l: 'Facility fire suppression water service piping' },
      { n: '21 12 00', l: 'Fire suppression standpipes' },
      { n: '21 13 00', l: 'Fire suppression sprinkler systems' },
      { n: '21 21 00', l: 'Carbon dioxide and clean agent systems' },
      { n: '21 30 00', l: 'Fire pumps' },
      { n: '21 40 00', l: 'Fire suppression water storage' },
      { n: '28 31 00', l: 'Fire detection and alarm' },
      { n: '28 46 00', l: 'Fire detection and alarm interfaces' },
    ],
  },
  projectsLead: 'Warehouses, healthcare, high-rise, education and industrial — where hazard classification varies room to room.',
  workflow: {
    h2: 'How a Fire Protection Estimate Comes Together',
    lead: 'Read the criteria first. Everything downstream depends on it.',
    steps: [
      { t: 'Upload the drawings and specification', s: 'Sprinkler plans, riser diagrams, fire alarm drawings, the Division 21 and 28 specification sections and any design criteria narrative.' },
      { t: 'Design criteria extracted', s: 'Hazard classifications, design densities and coverage requirements are read from the specification and mapped to the areas they apply to, with page citations.' },
      { t: 'Heads counted or derived', s: 'Where a layout is drawn, heads are counted by type. Where the work is design-build, counts are derived from area and coverage, with the basis shown on the line.' },
      { t: 'Piping measured by system', s: 'Mains, cross mains and branch lines measured by size and system type, with fittings, hangers and seismic bracing quantified from the same runs.' },
      { t: 'Assemblies and equipment counted', s: 'Riser and control valve assemblies, standpipes, test connections, FDCs, pumps, controllers and tanks counted with their interfaces noted.' },
      { t: 'Alarm scope counted', s: 'Initiating and notification devices, panels and wiring counted from the alarm plans, with the split against the electrical contractor written down explicitly.' },
      { t: 'Priced and delivered', s: 'Labor units applied by head type and ceiling condition, material from your supplier pricing, exported to Excel with the marked-up drawings behind it.' },
    ],
  },
  benefits: {
    eyebrow: 'Benefits',
    h2: 'What Changes on a Fire Protection Bid',
    lead: 'Mostly, that the design basis is checked before the count is trusted.',
    cards: [
      { icon: 'ic-shield', title: 'Counts Tied to the Criteria', desc: 'Deriving head counts from hazard classification catches the case where the drawn layout does not match the specification — before it becomes a rework item.' },
      { icon: 'ic-layers', title: 'Ceiling Conditions Priced', desc: 'A concealed head in a finished ceiling and an upright over racking are different installations. Applying separate productivity is what stops one subsidising the other.' },
      { icon: 'ic-filter', title: 'Assemblies Not Dissolved', desc: 'Riser and valve assemblies counted as assemblies means the labor that lives in them is priced instead of vanishing into feet of pipe.' },
      { icon: 'ic-zap',    title: 'The Alarm Interface Stated', desc: 'Writing down what the electrical contractor is carrying is the cheapest possible way to avoid a gap in coverage at the coordination meeting.' },
      { icon: 'ic-tool',   title: 'Seismic Bracing Carried', desc: 'Sway bracing quantified where the seismic category requires it rather than remembered during installation, when it is a change order.' },
      { icon: 'ic-check',  title: 'Testing Included', desc: 'Hydrostatic testing, flushing, inspection and commissioning are real hours, and counting them at bid is the only time it costs nothing.' },
    ],
  },
  why: {
    h2: 'Why Fire Protection Contractors Use BidcoreAI',
    lead: 'Because the specification is part of the takeoff, not background reading.',
    items: [
      { icon: 'ic-shield', t: 'Criteria read with the drawings', s: 'Hazard classifications and design densities are extracted with page citations and mapped to the areas they govern.' },
      { icon: 'ic-plus',   t: 'Heads by type', s: 'Pendant, concealed, upright, sidewall and dry heads counted separately, each with its own cost and install time.' },
      { icon: 'ic-filter', t: 'Assemblies counted', s: 'Risers, control valves, test connections and FDCs priced as assemblies rather than reduced to pipe.' },
      { icon: 'ic-zap',    t: 'Alarm scope split written down', s: 'The interface with the electrical contractor is stated in the estimate, where it can still be negotiated.' },
      { icon: 'ic-cloud',  t: 'Browser-based', s: 'No workstation licence; measure and price from anywhere.' },
      { icon: 'ic-users',  t: 'Estimators available', s: 'Fire protection packages can be measured for you through <a href="/mep-estimating-services">MEP estimating services</a>.' },
    ],
  },
  faqs: [
    { q: 'What is fire protection estimating software?', a: 'It measures and prices a fire suppression package: sprinkler heads by type, piping by system and size, riser and standpipe assemblies, pumps and water supply, plus fire alarm devices where they are bid together. Crucially it reads the design criteria in the specification, because hazard classification determines head coverage and therefore the quantity.' },
    { q: 'How are sprinkler head counts determined?', a: 'Two ways, and the estimate shows which was used. Where a layout is drawn, heads are counted by type from the plans. Where the work is design-build, counts are derived from area and the maximum coverage per head allowed by the hazard classification in the specification. Counting a drawn layout without checking it against the criteria is how a bid ends up short.' },
    { q: 'Does it understand hazard classifications?', a: 'It reads them from the specification — light hazard, ordinary group 1 and 2, extra hazard — and maps each to the areas it governs, with the page citation retained. Design density and coverage area follow from the classification, which is what makes derived head counts defensible.' },
    { q: 'Does it handle dry, pre-action and deluge systems?', a: 'Yes, as separate systems. Wet, dry, pre-action, deluge and antifreeze loops are measured independently because each carries different pipe material, fittings, valve assemblies and labor. A dry system in a parking garage is not a wet system priced with a different name.' },
    { q: 'Are standpipes and risers included?', a: 'Yes, and they are counted as assemblies rather than reduced to feet of pipe. Riser and control valve assemblies, standpipes, hose valves, inspector test connections, drains and fire department connections each carry their own material and labor content.' },
    { q: 'Does it estimate fire alarm as well as sprinkler?', a: 'Yes. Initiating devices, notification appliances, panels, annunciators, power supplies and wiring are counted from the alarm drawings. The interface with the electrical contractor — who pulls which wire, who provides which conduit — is recorded explicitly in the estimate, because that boundary is where scope most often falls through.' },
    { q: 'Does it account for seismic bracing?', a: 'Yes. Hanger spacing follows pipe size, and sway bracing and restraints are quantified where the seismic design category requires them. Bracing is easy to omit at bid and expensive to add during installation.' },
    { q: 'Can I use my own labor units?', a: 'Yes. Install hours per head, per fitting and per hundred feet of pipe come from your own productivity history, with visible factors for ceiling condition — finished ceiling, open deck, rack storage — rather than a single blended rate.' },
    { q: 'Does it include testing and commissioning?', a: 'Yes. Hydrostatic testing, flushing, inspection, commissioning support and O&M documentation are carried as their own lines. They are real hours, and the only time they cost nothing to include is before the bid goes in.' },
    { q: 'Can BidcoreAI estimate the fire protection package for me?', a: 'Yes. <a href="/mep-estimating-services">MEP estimating services</a> cover fire protection, staffed by estimators working in this platform, returning head counts, pipe by system, assemblies, device counts and a priced estimate with the marked-up drawings behind it.' },
  ],
  service: {
    h2: 'Fire Protection and MEP Estimating Services',
    body: 'Send the sprinkler and alarm drawings with the specification, and have the package measured for you: heads by type checked against the hazard classification, pipe by system and size, riser assemblies, pumps and alarm devices — priced against your own labor units.',
    href: '/mep-estimating-services',
    label: 'MEP Estimating Services',
  },
  related: [
    'plumbing-estimating-software',
    'hvac-estimating-software',
    'electrical-estimating-software',
    'structural-steel-estimating-software',
    'construction-estimating-software',
    'quantity-takeoff-software',
    'construction-takeoff-software',
    'drywall-estimating-software',
  ],
  cta: {
    h2: 'Check a Sprinkler Package Against Its Criteria',
    lead: 'Bring a set where you know the head count. See whether the specification agrees with the drawing.',
  },
},

];
