/**
 * Site trades: earthwork, sitework, demolition, landscaping.
 *
 * The common thread is that the quantity is a difference between two surfaces
 * or two states — existing grade against proposed, building against cleared
 * lot — and neither is a thing you can measure directly off a single plan.
 * Every page here says so, because pretending otherwise is how site packages
 * get bid badly.
 */
module.exports = [

/* ══════════════════ EARTHWORK ══════════════════ */
{
  slug: 'earthwork-estimating-software',
  name: 'Earthwork Estimating Software',
  h1: 'Earthwork Estimating Software for Cut, Fill and Haul',
  title: 'Earthwork Estimating Software — Cut and Fill | BidcoreAI',
  description: 'Earthwork estimating software: cut and fill volumes from existing and proposed grades, shrink and swell applied, haul and import priced from your own rates.',
  keywords: 'earthwork estimating software, cut and fill software, excavation estimating software, grading estimating software, site earthwork takeoff, mass haul estimating',
  eyebrow: 'CSI Division 31 · Earthwork',
  eyebrowIcon: 'ic-db',
  heroLead: 'Earthwork estimating software for site contractors and general contractors. Cut and fill volumes calculated between existing and proposed grades, shrink and swell factors applied by material, and haul, import and export priced separately — because the balance, not the volume, is what decides the number.',
  pills: [
    { icon: 'ic-chart', text: 'Cut and fill by surface' },
    { icon: 'ic-percent',text: 'Shrink and swell applied' },
    { icon: 'ic-tool',  text: 'Haul priced separately' },
  ],
  card: {
    eyebrow: 'What an earthwork estimate needs',
    headline: 'The balance, not the volume',
    sub: 'A site that balances and a site that exports 20,000 yards can have identical cut volumes',
    items: [
      'Cut and fill between existing and proposed',
      'Shrink and swell by material type',
      'Topsoil strip, stockpile and respread',
      'Import and export volumes with haul distance',
      'Trench, structural excavation and backfill',
    ],
  },
  intro: {
    eyebrow: 'What it is',
    h2: 'Earthwork Is a Difference Between Two Surfaces',
    paras: [
      'Every other trade measures something that exists on a drawing. Earthwork measures the difference between two things that do not: the existing ground surface and the proposed one. Cut is where the proposed grade is below existing, fill is where it is above, and the estimate is the volume between them — adjusted for topsoil strip, for subgrade preparation below slabs and pavements, and for the fact that soil does not occupy the same volume in the ground, in a truck and compacted back into an embankment.',
      'BidcoreAI builds both surfaces from the drawings. Existing contours and spot elevations from the topographic survey; proposed contours, spot grades and pavement sections from the grading plan. The volume between them is computed by grid or by cross-section, then adjusted per material for shrink and swell so that a cubic yard of cut becomes the right number of truckloads and the right number of compacted yards in fill.',
      'The balance is what matters commercially. Two sites with identical cut volumes are entirely different jobs if one balances on site and the other exports twenty thousand cubic yards to a landfill fourteen miles away. Import and export are calculated separately with haul distance, cycle time and disposal cost, because on most projects the haul is a larger number than the excavation.',
      'Structural excavation is kept apart from mass grading. Footing and foundation excavation, trench excavation by depth and width, over-excavation and replacement, rock provisions and dewatering are estimated with their own productivity and their own risk, since they are done with different equipment by different crews under different conditions. Where soils reports flag unsuitable material or a high water table, the estimate carries the assumption explicitly rather than absorbing it into a unit rate.',
    ],
  },
  measures: {
    eyebrow: 'Scope',
    icon: 'ic-db',
    h2: 'What the Software Takes Off on an Earthwork Package',
    lead: 'Topographic survey, grading plan, pavement sections, foundation plan and the geotechnical report.',
    cards: [
      {
        icon: 'ic-chart', title: 'Mass Grading',
        desc: 'Cut and fill volumes computed between existing and proposed surfaces.',
        items: ['Existing surface from survey data', 'Proposed surface from grading plan', 'Cut and fill by grid or section', 'Balance and net import or export'],
      },
      {
        icon: 'ic-layers', title: 'Topsoil',
        desc: 'Stripped, stockpiled and respread — three operations, not one line.',
        items: ['Strip depth and area', 'Stockpile volume and location', 'Respread depth at landscape areas', 'Surplus disposal or import'],
      },
      {
        icon: 'ic-percent', title: 'Shrink and Swell',
        desc: 'Applied by material so bank, loose and compacted volumes stay distinct.',
        items: ['Bank to loose for hauling', 'Bank to compacted for fill', 'Material-specific factors', 'Subgrade compaction requirements'],
      },
      {
        icon: 'ic-building', title: 'Structural Excavation',
        desc: 'Foundations, trenches and pits, priced apart from mass grading.',
        items: ['Footing and foundation excavation', 'Trench by depth, width and length', 'Over-excavation and replacement', 'Backfill and compaction'],
      },
      {
        icon: 'ic-tool', title: 'Haul and Disposal',
        desc: 'Frequently the largest number in the package, and rarely the one measured first.',
        items: ['Haul distance and cycle time', 'Truck counts and load size', 'Import source and material cost', 'Disposal fees and tipping'],
      },
      {
        icon: 'ic-shield', title: 'Site Conditions and Risk',
        desc: 'Taken from the geotechnical report and carried as stated assumptions.',
        items: ['Rock provisions and blasting', 'Dewatering and groundwater', 'Unsuitable material and undercut', 'Erosion control and stabilisation'],
      },
    ],
  },
  features: {
    eyebrow: 'Features',
    h2: 'Earthwork Estimating Features',
    lead: 'Surfaces, factors and haul — the three things that make a site number move.',
    cards: [
      { icon: 'ic-brain',  title: 'AI Contour Reading', desc: 'Existing and proposed contours and spot elevations extracted from the survey and grading plans and built into surfaces.' },
      { icon: 'ic-chart',  title: 'Cut and Fill Calculation', desc: 'Volumes computed between surfaces by grid or cross-section, with the method and grid size recorded on the result.' },
      { icon: 'ic-percent',title: 'Shrink and Swell Factors', desc: 'Bank, loose and compacted volumes kept distinct per material, so truck counts and fill quantities are both right.' },
      { icon: 'ic-layers', title: 'Topsoil Operations', desc: 'Strip, stockpile and respread quantified separately with their own depths, areas and productivity.' },
      { icon: 'ic-tool',   title: 'Haul Modelling', desc: 'Haul distance, cycle time, truck size and disposal cost priced explicitly rather than folded into a per-yard rate.' },
      { icon: 'ic-building',title: 'Structural Excavation', desc: 'Foundation and trench excavation measured by depth and width with backfill and compaction carried alongside.' },
      { icon: 'ic-db',     title: 'Subgrade and Base', desc: 'Pavement and slab sections quantified by layer — subbase, base course, geotextile — from the section details.' },
      { icon: 'ic-shield', title: 'Geotechnical Assumptions', desc: 'Rock, groundwater and unsuitable material carried as stated assumptions with the report reference attached.' },
      { icon: 'ic-users',  title: 'Equipment Productivity', desc: 'Excavator, dozer, scraper and truck productivity from your own fleet data rather than a generic per-yard price.' },
      { icon: 'ic-refresh',title: 'Revision Comparison', desc: 'A regraded plan compared against the previous version so a changed pad elevation shows up as a volume difference.' },
      { icon: 'ic-report', title: 'Balance Reporting', desc: 'Cut, fill, net and haul reported by area and phase, so the earthwork plan and the estimate agree.' },
      { icon: 'ic-dl',     title: 'Excel Export', desc: 'Volume schedules and priced estimates exported with the calculation method and factors on every line.' },
    ],
  },
  csi: {
    h2: 'Earthwork Spec Coverage',
    lead: 'Division 31 with the pavement and utility interfaces kept visible.',
    rows: [
      { n: '31 10 00', l: 'Site clearing' },
      { n: '31 20 00', l: 'Earth moving' },
      { n: '31 22 00', l: 'Grading' },
      { n: '31 23 00', l: 'Excavation and fill' },
      { n: '31 23 19', l: 'Dewatering' },
      { n: '31 23 33', l: 'Trenching and backfilling' },
      { n: '31 25 00', l: 'Erosion and sedimentation control' },
      { n: '31 37 00', l: 'Riprap and rock' },
      { n: '32 11 00', l: 'Base courses (interface)' },
    ],
  },
  projectsLead: 'Commercial pads, warehouse sites, subdivisions, roads and infrastructure — anywhere the ground has to move.',
  workflow: {
    h2: 'How an Earthwork Estimate Comes Together',
    lead: 'Two surfaces, one difference, and then the trucks.',
    steps: [
      { t: 'Upload survey and grading plans', s: 'Topographic survey, grading plan, pavement and slab sections, foundation plan, utility plans and the geotechnical report.' },
      { t: 'Surfaces built', s: 'Existing contours and spot elevations, then proposed contours and spot grades, are extracted and built into two surfaces that can be differenced.' },
      { t: 'Cut and fill computed', s: 'Volumes are calculated between the surfaces by grid or cross-section, with the method and grid size recorded so the result can be checked or re-run.' },
      { t: 'Topsoil and subgrade adjusted', s: 'Strip depth is removed before the comparison, and subgrade preparation below slabs and pavements is added from the section details.' },
      { t: 'Factors applied', s: 'Shrink and swell are applied per material so bank, loose and compacted volumes remain distinct, giving correct truck counts and correct fill quantities.' },
      { t: 'Haul and import priced', s: 'Net import or export is calculated with haul distance, cycle time, truck size, material cost and disposal fees priced as their own lines.' },
      { t: 'Structural excavation added', s: 'Foundation and trench excavation, backfill, compaction and any rock or dewatering provisions are priced separately and exported with the mass grading.' },
    ],
  },
  benefits: {
    eyebrow: 'Benefits',
    h2: 'What Changes on an Earthwork Bid',
    lead: 'The estimate starts answering the question that decides the job: where does the dirt go?',
    cards: [
      { icon: 'ic-chart',  title: 'A Real Balance', desc: 'Knowing net import or export rather than gross cut is what separates a site that pays for itself from one that spends a fortune on trucking.' },
      { icon: 'ic-percent',title: 'Volumes That Convert', desc: 'Keeping bank, loose and compacted volumes distinct means the truck count and the fill quantity are both right — using one number for both guarantees one of them is wrong.' },
      { icon: 'ic-tool',   title: 'Haul Priced Properly', desc: 'Distance and cycle time drive the largest cost in most earthwork packages, and a per-yard rate hides them completely.' },
      { icon: 'ic-shield', title: 'Risk Stated', desc: 'Rock, groundwater and unsuitable material carried as visible assumptions gives you something to negotiate with rather than a number to defend.' },
      { icon: 'ic-building',title: 'Structural Work Separated', desc: 'Trench and foundation excavation at mass-grading rates is a standing underbid, because it is slower work with smaller equipment.' },
      { icon: 'ic-refresh',title: 'Regrades Handled', desc: 'When the pad elevation changes, comparing the surfaces gives you the volume difference directly instead of a second full takeoff.' },
    ],
  },
  why: {
    h2: 'Why Site Contractors Use BidcoreAI',
    lead: 'Because earthwork is the one package where the quantity has to be computed rather than measured.',
    items: [
      { icon: 'ic-chart',  t: 'Surfaces, not areas', s: 'Existing and proposed surfaces are built and differenced, with the calculation method recorded and re-runnable.' },
      { icon: 'ic-percent',t: 'Factors kept honest', s: 'Bank, loose and compacted volumes stay distinct through the whole estimate rather than being collapsed into one figure.' },
      { icon: 'ic-tool',   t: 'Haul as its own cost', s: 'Distance, cycle time and disposal priced explicitly, which is where most of the money actually is.' },
      { icon: 'ic-shield', t: 'Geotech assumptions visible', s: 'Rock, dewatering and undercut carried with their report references so the risk position is written down.' },
      { icon: 'ic-cloud',  t: 'Browser-based', s: 'No workstation licence; run volumes from the office or a site trailer.' },
      { icon: 'ic-users',  t: 'Estimators available', s: 'Site packages can be measured for you through <a href="/takeoff-services">professional takeoff services</a>.' },
    ],
  },
  faqs: [
    { q: 'What is earthwork estimating software?', a: 'Earthwork estimating software calculates cut and fill volumes by building surfaces from the existing survey and the proposed grading plan and computing the difference between them. It then applies shrink and swell factors, separates structural excavation from mass grading, and prices haul, import and export — which on most sites is the larger cost.' },
    { q: 'How are cut and fill volumes calculated?', a: 'By differencing two surfaces. Existing contours and spot elevations come from the topographic survey; proposed contours and spot grades from the grading plan. The volume between them is computed by grid or cross-section, with the method and grid size recorded on the result so it can be checked or re-run at a finer resolution.' },
    { q: 'What are shrink and swell factors and why do they matter?', a: 'Soil occupies different volumes in the ground (bank), in a truck (loose) and compacted into fill. A cubic yard of cut is not a cubic yard of fill or a cubic yard of hauling. Applying material-specific factors keeps the three distinct, which is what makes both the truck count and the fill quantity correct rather than one of them.' },
    { q: 'Does it calculate import and export?', a: 'Yes, as a net balance after shrink and swell are applied, with haul distance, cycle time, truck size, material cost and disposal fees priced as their own lines. Two sites with the same cut volume are completely different jobs if one balances and the other exports, and the balance is the number that decides which.' },
    { q: 'Does it handle trench and foundation excavation?', a: 'Yes, and separately from mass grading. Trench excavation by depth and width, footing and pit excavation, over-excavation, backfill and compaction are estimated with their own equipment and productivity, because they are slower work done with smaller machines.' },
    { q: 'Can it account for rock and groundwater?', a: 'Yes, as stated assumptions taken from the geotechnical report with the reference attached. Rock provisions, dewatering, undercut and unsuitable material replacement are carried explicitly rather than absorbed into a unit rate, which is what makes them negotiable rather than simply absorbed.' },
    { q: 'Does it include topsoil stripping and respreading?', a: 'Yes, as three separate operations: strip by depth and area, stockpile with its volume and location, and respread at landscape areas. Topsoil is removed before the cut and fill comparison so it is neither double-counted nor forgotten.' },
    { q: 'Can I use my own equipment production rates?', a: 'Yes. Excavator, dozer, scraper, loader and truck productivity come from your own fleet data and crew history, which is considerably more predictive than a generic price per cubic yard that knows nothing about your equipment or your haul.' },
    { q: 'What happens when the grading plan is revised?', a: 'The new surface is compared against the previous one and you get the volume difference directly, rather than re-running the entire takeoff. On projects where the pad elevation moves twice during bidding, this is the difference between a day and an hour.' },
    { q: 'Can BidcoreAI estimate the earthwork package for me?', a: 'Yes. <a href="/takeoff-services">Professional takeoff and estimating services</a> are staffed by estimators working in this platform, returning cut and fill volumes, a balance report, haul quantities and a priced estimate with the assumptions written down.' },
  ],
  service: {
    h2: 'Earthwork Takeoff and Estimating Services',
    body: 'Send the survey and grading plans with the geotechnical report and have the volumes computed for you — cut and fill between surfaces, topsoil operations, shrink and swell applied, structural excavation separated, and haul priced with real distances.',
    href: '/takeoff-services',
    label: 'Takeoff &amp; Estimating Services',
  },
  related: [
    'sitework-estimating-software',
    'demolition-estimating-software',
    'landscaping-estimating-software',
    'concrete-estimating-software',
    'construction-estimating-software',
    'quantity-takeoff-software',
    'construction-takeoff-software',
    'plumbing-estimating-software',
  ],
  cta: {
    h2: 'Run the Volumes on a Site You Have Bid',
    lead: 'Compare the balance, the truck count and the haul cost against what the job actually did.',
  },
},

/* ══════════════════ SITEWORK ══════════════════ */
{
  slug: 'sitework-estimating-software',
  name: 'Sitework Estimating Software',
  h1: 'Sitework Estimating Software for Paving, Utilities and Site Improvements',
  title: 'Sitework Estimating Software for Contractors | BidcoreAI',
  description: 'Sitework estimating software: paving by section and area, site utilities by size and depth, curb and walk by length, plus site concrete, fencing and striping.',
  keywords: 'sitework estimating software, site work takeoff software, paving estimating software, site utilities estimating, civil estimating software, asphalt estimating software',
  eyebrow: 'CSI Divisions 32–33 · Sitework',
  eyebrowIcon: 'ic-trending',
  heroLead: 'Sitework estimating software for site and civil contractors. Paving measured by area and section, utilities measured by size, material and depth with structures counted, curbs and walks measured by length, and every layer of the pavement section quantified rather than carried as a single square-yard rate.',
  pills: [
    { icon: 'ic-layers', text: 'Sections by layer' },
    { icon: 'ic-db',     text: 'Utilities by depth' },
    { icon: 'ic-plus',   text: 'Structures counted' },
  ],
  card: {
    eyebrow: 'What a sitework estimate needs',
    headline: 'Layers, lengths and structures',
    sub: 'Paving is a section not an area, and a utility run is priced by its depth as much as its length',
    items: [
      'Paving area by section, each layer quantified',
      'Curb, gutter and walk by length and type',
      'Utility runs by size, material and depth',
      'Manholes, inlets and structures counted',
      'Fencing, striping, signage and site amenities',
    ],
  },
  intro: {
    eyebrow: 'What it is',
    h2: 'A Parking Lot Is Not a Square Yard Number',
    paras: [
      'Sitework covers everything outside the building line, and it is estimated badly more often than any other package because it looks like a set of simple areas and lengths. A parking lot is an area. A storm line is a length. In reality the parking lot is a stack of layers — subgrade preparation, geotextile, aggregate base, binder course, surface course — each with its own thickness, its own unit and its own price, and the storm line is priced by depth as much as by length, because a run at fourteen feet needs trench boxes and a crew that a four-foot run does not.',
      'BidcoreAI measures the pavement section rather than the pavement. Each paved area carries its section from the detail sheet, so a heavy-duty truck court, a standard parking bay and a concrete dumpster pad each generate their own layer quantities in their own units — square yards of surface course, tons of asphalt by layer, cubic yards of base. Changing a section changes the quantities without re-measuring the area.',
      'Utilities are measured by system, size, material and depth, with structures counted individually. Manholes, catch basins, inlets, cleanouts, valves, hydrants and thrust blocks are counted from the plans and the structure schedule, each with its rim and invert elevations, which is what makes the trench depth real rather than assumed. Bedding, backfill, compaction and pavement restoration follow the trench rather than being carried as an allowance.',
      'The rest of the site — curbs, gutters, sidewalks, ramps, fencing, gates, striping, signage, bollards, dumpster enclosures and site furnishings — is measured by its own units and counted from the plan. These items are individually small and collectively substantial, and they are the ones most often reduced to a single site allowance in a hurried bid, which is why they are where site packages quietly lose money.',
    ],
  },
  measures: {
    eyebrow: 'Scope',
    icon: 'ic-trending',
    h2: 'What the Software Takes Off on a Sitework Package',
    lead: 'Site plan, paving plan, utility plans, structure schedules and the site detail sheets.',
    cards: [
      {
        icon: 'ic-layers', title: 'Paving',
        desc: 'Measured by area and section, with every layer of the section quantified.',
        items: ['Asphalt by course and thickness', 'Concrete paving by area and depth', 'Aggregate base and subbase', 'Tonnage by layer and mix'],
      },
      {
        icon: 'ic-layout', title: 'Curbs, Walks and Ramps',
        desc: 'Measured by length and type with the details that go with them.',
        items: ['Curb and gutter by profile', 'Sidewalk by width and thickness', 'ADA ramps and detectable warning', 'Wheel stops and edge treatment'],
      },
      {
        icon: 'ic-db', title: 'Site Utilities',
        desc: 'By system, size, material and depth — depth being the part that drives the price.',
        items: ['Storm, sanitary and water', 'Pipe by size, material and class', 'Trench depth from rim and invert', 'Bedding, backfill and compaction'],
      },
      {
        icon: 'ic-plus', title: 'Structures',
        desc: 'Counted individually from the plans and structure schedule with their elevations.',
        items: ['Manholes by depth and diameter', 'Catch basins, inlets and cleanouts', 'Valves, hydrants and thrust blocks', 'Frames, grates and castings'],
      },
      {
        icon: 'ic-building', title: 'Site Concrete',
        desc: 'The flatwork and small structures that never appear in a building takeoff.',
        items: ['Dumpster and equipment pads', 'Light pole and sign bases', 'Retaining and site walls', 'Stairs, rails and site steps'],
      },
      {
        icon: 'ic-tag', title: 'Site Improvements',
        desc: 'Small items in large numbers — the classic site allowance that should be a takeoff.',
        items: ['Fencing, gates and bollards', 'Striping, signage and markings', 'Site furnishings and bike racks', 'Erosion control and stabilisation'],
      },
    ],
  },
  features: {
    eyebrow: 'Features',
    h2: 'Sitework Estimating Features',
    lead: 'Sections, depths and structures — carried as data instead of as assumptions.',
    cards: [
      { icon: 'ic-brain',  title: 'AI Site Plan Takeoff', desc: 'Paved areas, curb runs, walks and utility lines detected across the site plans and proposed for confirmation.' },
      { icon: 'ic-layers', title: 'Pavement Sections', desc: 'Each area carries its section from the detail sheet, so every layer quantifies automatically in its own unit.' },
      { icon: 'ic-chart',  title: 'Asphalt Tonnage', desc: 'Surface and binder courses converted to tons by thickness and mix density rather than reported as square yards.' },
      { icon: 'ic-db',     title: 'Trench Depth From Elevations', desc: 'Rim and invert elevations from the structure schedule give real trench depths instead of a single assumed depth.' },
      { icon: 'ic-plus',   title: 'Structure Counting', desc: 'Manholes, inlets, valves and hydrants counted individually with depth, diameter and casting type.' },
      { icon: 'ic-tool',   title: 'Trench Safety and Shoring', desc: 'Trench box and shoring requirements driven by measured depth, priced rather than assumed included.' },
      { icon: 'ic-refresh',title: 'Restoration Quantities', desc: 'Pavement and surface restoration over trenches calculated from the trench footprint, not estimated at the end.' },
      { icon: 'ic-percent',title: 'Compaction and Testing', desc: 'Backfill compaction lifts and density testing carried as quantities where the specification requires them.' },
      { icon: 'ic-tag',    title: 'Small Items Counted', desc: 'Bollards, signs, wheel stops, striping and furnishings counted individually rather than folded into a site allowance.' },
      { icon: 'ic-users',  title: 'Crew and Equipment Rates', desc: 'Productivity by operation — paving, pipe laying, curb — from your own fleet and crew history.' },
      { icon: 'ic-report', title: 'Phase Reporting', desc: 'Quantities grouped by phase or area, so a staged site can be estimated and billed the way it will be built.' },
      { icon: 'ic-dl',     title: 'Excel Export', desc: 'Quantity schedules and priced estimates exported with sheet references and section details on every line.' },
    ],
  },
  csi: {
    h2: 'Sitework Spec Coverage',
    lead: 'Divisions 32 and 33, with the earthwork interface kept in view.',
    rows: [
      { n: '32 11 00', l: 'Base courses' },
      { n: '32 12 16', l: 'Asphalt paving' },
      { n: '32 13 13', l: 'Concrete paving' },
      { n: '32 16 00', l: 'Curbs, gutters, sidewalks and driveways' },
      { n: '32 17 23', l: 'Pavement markings' },
      { n: '32 31 00', l: 'Fences and gates' },
      { n: '33 10 00', l: 'Water utilities' },
      { n: '33 30 00', l: 'Sanitary sewerage utilities' },
      { n: '33 40 00', l: 'Storm drainage utilities' },
      { n: '31 23 33', l: 'Trenching and backfilling (interface)' },
    ],
  },
  projectsLead: 'Retail pads, distribution centres, campuses, subdivisions and municipal work.',
  workflow: {
    h2: 'How a Sitework Estimate Comes Together',
    lead: 'Areas and lengths first, then the sections and depths that turn them into money.',
    steps: [
      { t: 'Upload site and utility plans', s: 'Site plan, paving plan, grading plan, storm, sanitary and water plans, structure schedules, site details and the Division 32 and 33 specifications.' },
      { t: 'Areas and lengths measured', s: 'Paved areas, curb and walk runs and utility lines are measured across the site plans, each tied to the sheet it was measured on.' },
      { t: 'Sections applied', s: 'Each paved area is assigned its pavement section from the detail sheet, and every layer quantifies in its own unit — square yards, tons, cubic yards.' },
      { t: 'Structures counted', s: 'Manholes, inlets, valves and hydrants are counted with their rim and invert elevations taken from the structure schedule.' },
      { t: 'Trench depths derived', s: 'Real trench depths are calculated from rim and invert elevations, driving excavation volume, bedding, backfill, shoring and restoration.' },
      { t: 'Site improvements counted', s: 'Fencing, striping, signage, bollards, wheel stops, furnishings and erosion control are counted individually rather than allowed for.' },
      { t: 'Priced and delivered', s: 'Crew and equipment productivity by operation from your own history, exported to Excel with a marked-up site plan behind every quantity.' },
    ],
  },
  benefits: {
    eyebrow: 'Benefits',
    h2: 'What Changes on a Sitework Bid',
    lead: 'The site stops being one allowance and becomes a set of measured quantities.',
    cards: [
      { icon: 'ic-layers', title: 'Sections, Not Square Yards', desc: 'Quantifying every layer means a heavy-duty section and a standard bay are priced differently, which they are, by a lot.' },
      { icon: 'ic-db',     title: 'Depth Drives the Price', desc: 'Deriving trench depth from rim and invert elevations is what separates a bid that anticipated trench boxes from one that discovers them.' },
      { icon: 'ic-plus',   title: 'Structures Counted', desc: 'Manholes and inlets are expensive units. Counting them with their depths beats applying an average that fits no project.' },
      { icon: 'ic-refresh',title: 'Restoration Included', desc: 'Pavement restoration over trenches calculated from the trench footprint stops it being remembered after the number is submitted.' },
      { icon: 'ic-tag',    title: 'Small Items Add Up', desc: 'Bollards, signs, striping and furnishings counted individually is usually a five-figure difference against a single site allowance.' },
      { icon: 'ic-chart',  title: 'Tonnage for Suppliers', desc: 'Asphalt in tons by course and mix is what a plant quotes against, and it makes the material order match the estimate.' },
    ],
  },
  why: {
    h2: 'Why Site Contractors Use BidcoreAI',
    lead: 'Because the detail sheet and the structure schedule are where sitework is actually priced.',
    items: [
      { icon: 'ic-layers', t: 'Sections carried as data', s: 'Assign a section to an area and every layer quantifies. Change the section and the quantities follow without re-measuring.' },
      { icon: 'ic-db',     t: 'Real trench depths', s: 'Derived from rim and invert elevations rather than assumed, which changes excavation, shoring and restoration together.' },
      { icon: 'ic-plus',   t: 'Structures with elevations', s: 'Counted individually with depth and diameter, priced as the significant units they are.' },
      { icon: 'ic-tag',    t: 'No site allowance', s: 'Fencing, striping, signage and furnishings counted rather than lumped, which is where site bids leak.' },
      { icon: 'ic-cloud',  t: 'Browser-based', s: 'Measure and price from anywhere; the marked-up site plan opens on a tablet in the field.' },
      { icon: 'ic-users',  t: 'Estimators available', s: 'Site packages can be measured for you through <a href="/takeoff-services">professional takeoff services</a>.' },
    ],
  },
  faqs: [
    { q: 'What is sitework estimating software?', a: 'Sitework estimating software measures everything outside the building line — paving, curbs, walks, site utilities, structures, fencing, striping and site concrete — and prices it by section, depth and unit rather than by area alone. The distinguishing feature is that a paved area carries its pavement section, so every layer quantifies in its own unit.' },
    { q: 'How is paving estimated?', a: 'By area and section together. Each paved area is assigned its section from the detail sheet, and each layer — subgrade preparation, geotextile, aggregate base, binder course, surface course — quantifies in its own unit, with asphalt converted to tons by thickness and mix density for plant pricing.' },
    { q: 'How are trench depths determined?', a: 'From rim and invert elevations in the structure schedule rather than a single assumed depth. Depth drives excavation volume, bedding, backfill, shoring requirements and restoration, so getting it from the elevations rather than an average is the difference between a bid that works and one that hopes.' },
    { q: 'Does it count utility structures?', a: 'Yes, individually — manholes by depth and diameter, catch basins, inlets, cleanouts, valves, hydrants, thrust blocks, frames and castings — each taken from the plans and the structure schedule. They are expensive units and averaging them across a site is a reliable way to be wrong.' },
    { q: 'Does it include trench safety and shoring?', a: 'Yes. Trench box and shoring requirements follow measured depth, and are priced rather than assumed to be included in an excavation rate. Deep utility runs and shallow ones are different operations with different crews and equipment.' },
    { q: 'Is pavement restoration over trenches included?', a: 'Yes, calculated from the trench footprint rather than estimated at the end of the bid. Restoration is one of the more commonly forgotten items on utility work in existing pavement, and it is measurable rather than assumable.' },
    { q: 'Does it cover fencing, striping and site amenities?', a: 'Yes, counted individually. Fencing by length and type, gates, bollards, wheel stops, striping by length and stall count, signage, bike racks and furnishings. Collectively these routinely exceed the round-number site allowance they usually get folded into.' },
    { q: 'Can it handle phased sites?', a: 'Yes. Quantities can be grouped by phase or area so a staged site is estimated the way it will be built and billed, which also makes the estimate usable for progress claims later.' },
    { q: 'Can I use my own equipment and crew rates?', a: 'Yes. Productivity by operation — paving, pipe laying, curb machine, structure setting — comes from your own fleet and crew history rather than a generic unit price that knows nothing about your equipment.' },
    { q: 'Can BidcoreAI estimate the sitework package for me?', a: 'Yes. <a href="/takeoff-services">Professional takeoff and estimating services</a> are staffed by estimators working in this platform, returning paving quantities by layer, utility runs with real depths, structure counts and a priced estimate.' },
  ],
  service: {
    h2: 'Sitework Takeoff and Estimating Services',
    body: 'Send the site, paving and utility plans with the structure schedules and have the package measured for you — paving by section and layer, utilities by size and real depth, structures counted, and the small items counted rather than allowed for.',
    href: '/takeoff-services',
    label: 'Takeoff &amp; Estimating Services',
  },
  related: [
    'earthwork-estimating-software',
    'demolition-estimating-software',
    'landscaping-estimating-software',
    'concrete-estimating-software',
    'plumbing-estimating-software',
    'construction-estimating-software',
    'quantity-takeoff-software',
    'construction-takeoff-software',
  ],
  cta: {
    h2: 'Price a Site Package Layer by Layer',
    lead: 'Bring a paving plan and a detail sheet. Compare the tonnage and the base volume against what you carried.',
  },
},

/* ══════════════════ DEMOLITION ══════════════════ */
{
  slug: 'demolition-estimating-software',
  name: 'Demolition Estimating Software',
  h1: 'Demolition Estimating Software for Removal, Haul and Disposal',
  title: 'Demolition Estimating Software for Contractors | BidcoreAI',
  description: 'Demolition estimating software: removal quantities by element and material, disposal volume and tonnage, selective demo by room, plus abatement scope flagged.',
  keywords: 'demolition estimating software, demolition takeoff software, selective demolition estimating, interior demolition takeoff, disposal estimating software, demo bid software',
  eyebrow: 'CSI Division 02 · Demolition',
  eyebrowIcon: 'ic-refresh',
  heroLead: 'Demolition estimating software for demolition and interior contractors. Removal quantities measured by element and material from the demolition plans, converted to disposal volume and tonnage, with protection, shoring and abatement interfaces carried as scope rather than as an allowance.',
  pills: [
    { icon: 'ic-layers', text: 'Removal by element' },
    { icon: 'ic-chart',  text: 'Disposal by weight' },
    { icon: 'ic-shield', text: 'Abatement flagged' },
  ],
  card: {
    eyebrow: 'What a demolition estimate needs',
    headline: 'What comes out, and where it goes',
    sub: 'Demolition is priced by the container as much as by the hour',
    items: [
      'Removal quantities by element and material',
      'Disposal volume and tonnage by waste stream',
      'Container counts and haul cycles',
      'Protection, shoring and temporary works',
      'Abatement and hazardous material interface',
    ],
  },
  intro: {
    eyebrow: 'What it is',
    h2: 'Demolition Is a Logistics Estimate Wearing Work Boots',
    paras: [
      'Demolition looks like the least technical package on a project and behaves like one of the least forgiving. The labor to take something apart is only part of the cost. The rest is disposal — how many cubic yards of debris, how many tons, how many containers, how many haul cycles, which waste streams have to be separated, and what the tipping fee is for each. A selective interior demolition bid that got the labor right and the container count wrong will still lose money, and the container count follows from the volume and density of what comes out, which is a takeoff problem.',
      'BidcoreAI measures demolition by element and material from the demolition plans. Walls by type and area, ceilings by area, flooring by area and material, casework and fixtures by count, MEP removals by run and device, structural removals by volume and material. Each element carries a material density, so measured quantities convert into disposal volume and tonnage rather than stopping at square feet.',
      'Selective demolition is measured room by room, because that is how it is performed and how it is phased in an occupied building. Protection scope — temporary partitions, floor and surface protection, dust control, negative air, path protection — is quantified rather than allowed for, and on a fit-out in an operating facility it is frequently a larger number than the demolition itself.',
      'Where the drawings or the specification indicate hazardous materials, the abatement interface is flagged rather than swallowed. Asbestos, lead paint, mould and contaminated soils belong to a licensed abatement scope, and the estimate should say clearly what has been excluded and where the boundary lies. Structural removals carry their shoring and their sequencing, which are engineering questions that appear in a bid as costs and as risk.',
    ],
  },
  measures: {
    eyebrow: 'Scope',
    icon: 'ic-refresh',
    h2: 'What the Software Takes Off on a Demolition Package',
    lead: 'Demolition plans, existing conditions drawings, hazardous materials survey and the phasing plan.',
    cards: [
      {
        icon: 'ic-layout', title: 'Interior Removals',
        desc: 'Measured room by room, because that is how selective demolition is performed and phased.',
        items: ['Partitions by type and area', 'Ceilings, soffits and grid', 'Flooring by material and area', 'Casework, doors and fixtures'],
      },
      {
        icon: 'ic-building', title: 'Structural Removals',
        desc: 'Volume and material by element, with the shoring and sequencing that go with them.',
        items: ['Concrete removal by volume', 'Masonry and CMU removal', 'Steel and framing removal', 'Slab, deck and stair removal'],
      },
      {
        icon: 'ic-cpu', title: 'MEP Removals',
        desc: 'Runs and devices counted, since MEP demolition is slow and rarely drawn completely.',
        items: ['Duct, pipe and conduit runs', 'Fixtures, devices and equipment', 'Panels, gear and controls', 'Capping, isolation and make-safe'],
      },
      {
        icon: 'ic-chart', title: 'Disposal',
        desc: 'Converted from removal quantities using material density, by waste stream.',
        items: ['Volume and tonnage by material', 'Container size and count', 'Haul cycles and tipping fees', 'Recycling and diversion targets'],
      },
      {
        icon: 'ic-shield', title: 'Protection and Temporary Works',
        desc: 'Often the larger cost on a fit-out inside an operating building.',
        items: ['Temporary partitions and barriers', 'Floor, wall and surface protection', 'Dust control and negative air', 'Shoring and temporary support'],
      },
      {
        icon: 'ic-flag', title: 'Abatement Interface',
        desc: 'Flagged and bounded rather than absorbed into the demolition price.',
        items: ['Asbestos and lead identified', 'Survey references and locations', 'Scope boundary written down', 'Exclusions stated explicitly'],
      },
    ],
  },
  features: {
    eyebrow: 'Features',
    h2: 'Demolition Estimating Features',
    lead: 'Removal quantities that turn into containers, and protection that turns into a line item.',
    cards: [
      { icon: 'ic-brain',  title: 'AI Demolition Takeoff', desc: 'Elements marked for removal detected on the demolition plans and measured by type, with each shown on its sheet.' },
      { icon: 'ic-chart',  title: 'Density Conversion', desc: 'Measured quantities converted to disposal volume and tonnage using material densities per element type.' },
      { icon: 'ic-pkg',    title: 'Container Modelling', desc: 'Container size, count and haul cycles calculated from debris volume rather than estimated from experience alone.' },
      { icon: 'ic-layers', title: 'Room-by-Room Selective Demo', desc: 'Interior removals measured per room so the estimate matches how the work is phased in an occupied building.' },
      { icon: 'ic-shield', title: 'Protection Quantities', desc: 'Temporary partitions, floor protection, dust control and negative air quantified as scope with their own units.' },
      { icon: 'ic-flag',   title: 'Hazmat Flagging', desc: 'Hazardous material locations from the survey flagged against the areas they affect, with exclusions written into the estimate.' },
      { icon: 'ic-tool',   title: 'Shoring and Temporary Support', desc: 'Structural removals carry their shoring and sequencing requirements as costed scope rather than as an assumption.' },
      { icon: 'ic-percent',title: 'Recycling and Diversion', desc: 'Waste streams separated so diversion targets and their sorting labor are priced where the specification requires them.' },
      { icon: 'ic-sched',  title: 'Phasing and Access', desc: 'Quantities grouped by phase, floor and access route, with night and weekend work factored where required.' },
      { icon: 'ic-users',  title: 'Crew Productivity', desc: 'Removal rates by element and access condition from your own history — hand demolition and machine work are not comparable.' },
      { icon: 'ic-refresh',title: 'Revision Comparison', desc: 'A re-issued demolition plan compared against the previous one so added removals are flagged, not absorbed.' },
      { icon: 'ic-dl',     title: 'Excel Export', desc: 'Removal schedules, disposal summaries and priced estimates exported with sheet references intact.' },
    ],
  },
  csi: {
    h2: 'Demolition Spec Coverage',
    lead: 'Division 02, with the abatement sections kept separate and clearly bounded.',
    rows: [
      { n: '02 21 00', l: 'Surveys and existing conditions' },
      { n: '02 41 00', l: 'Demolition' },
      { n: '02 41 16', l: 'Structure demolition' },
      { n: '02 41 19', l: 'Selective demolition' },
      { n: '02 42 00', l: 'Removal and salvage of construction materials' },
      { n: '02 82 00', l: 'Asbestos remediation (interface)' },
      { n: '02 83 00', l: 'Lead remediation (interface)' },
      { n: '02 87 00', l: 'Biohazard remediation (interface)' },
      { n: '01 74 19', l: 'Construction waste management and disposal' },
    ],
  },
  projectsLead: 'Interior fit-outs, renovations, tenant turnovers, plant decommissioning and full structure demolition.',
  workflow: {
    h2: 'How a Demolition Estimate Comes Together',
    lead: 'Measure what goes, weigh it, then price getting it off the site.',
    steps: [
      { t: 'Upload demolition and existing plans', s: 'Demolition plans, existing conditions drawings, phasing plans, the hazardous materials survey and the Division 02 specification sections.' },
      { t: 'Removals measured by element', s: 'Partitions, ceilings, flooring, casework, MEP and structural elements marked for removal are measured by type and material, room by room where selective.' },
      { t: 'Converted to disposal', s: 'Material densities convert measured quantities into debris volume and tonnage by waste stream, which is what actually drives the disposal cost.' },
      { t: 'Containers and hauls calculated', s: 'Container size and count, haul cycles and tipping fees are calculated from the debris volume and the site access constraints.' },
      { t: 'Protection quantified', s: 'Temporary partitions, floor and surface protection, dust control and negative air are measured as scope — frequently the larger cost inside an operating building.' },
      { t: 'Hazmat boundary set', s: 'Hazardous material locations from the survey are flagged, the abatement boundary is written down, and exclusions are stated explicitly in the estimate.' },
      { t: 'Priced and delivered', s: 'Removal productivity by element and access condition from your own history, exported to Excel with a marked-up demolition plan and a written exclusions list.' },
    ],
  },
  benefits: {
    eyebrow: 'Benefits',
    h2: 'What Changes on a Demolition Bid',
    lead: 'The disposal side stops being a guess and starts being arithmetic.',
    cards: [
      { icon: 'ic-chart',  title: 'Debris in Tons and Yards', desc: 'Converting removals with real material densities is what makes the container count and the tipping cost a calculation rather than a recollection.' },
      { icon: 'ic-shield', title: 'Protection Priced', desc: 'On a fit-out in an operating building, protection and dust control routinely exceed the demolition. Quantifying it is the difference between a bid and a donation.' },
      { icon: 'ic-flag',   title: 'Hazmat Boundary Clear', desc: 'Writing the abatement exclusion into the estimate is the cheapest insurance available against a scope argument you cannot win.' },
      { icon: 'ic-layers', title: 'Room-Level Phasing', desc: 'Measuring selective demolition per room means the estimate matches the phasing plan and can be used for progress billing.' },
      { icon: 'ic-users',  title: 'Access Reflected in Labor', desc: 'Hand demolition on the fourth floor with one elevator is nothing like machine work at grade, and separate productivity says so.' },
      { icon: 'ic-percent',title: 'Diversion Costed', desc: 'Recycling targets require sorting labor and separate streams. Pricing them makes an LEED requirement a line item rather than a surprise.' },
    ],
  },
  why: {
    h2: 'Why Demolition Contractors Use BidcoreAI',
    lead: 'Because the cost of demolition is mostly the cost of moving the result.',
    items: [
      { icon: 'ic-chart',  t: 'Densities applied', s: 'Measured removals convert to volume and tonnage by material, so containers and haul cycles are computed rather than guessed.' },
      { icon: 'ic-shield', t: 'Protection as scope', s: 'Temporary partitions, dust control and negative air quantified with their own units and rates.' },
      { icon: 'ic-flag',   t: 'Exclusions written down', s: 'The abatement boundary is stated in the estimate, where it protects you, rather than assumed in a conversation.' },
      { icon: 'ic-sched',  t: 'Phased by room and floor', s: 'Quantities grouped the way the work is sequenced, which makes the estimate usable for billing.' },
      { icon: 'ic-cloud',  t: 'Browser-based', s: 'Measure and price from anywhere, with the marked-up demolition plan on a tablet on site.' },
      { icon: 'ic-users',  t: 'Estimators available', s: 'Demolition packages can be measured for you through <a href="/takeoff-services">professional takeoff services</a>.' },
    ],
  },
  faqs: [
    { q: 'What is demolition estimating software?', a: 'Demolition estimating software measures what is being removed — by element, material and room — converts those quantities into disposal volume and tonnage, calculates containers and haul cycles, and prices the protection, shoring and temporary works that surround the removal. The disposal side is at least half the cost, and it is arithmetic rather than intuition.' },
    { q: 'How is disposal volume calculated?', a: 'Measured removals are converted using material densities per element type — concrete, masonry, gypsum, wood, metal, carpet — into debris volume and tonnage by waste stream. Container size, count, haul cycles and tipping fees follow from that, rather than from an estimator\'s recollection of a similar job.' },
    { q: 'Does it handle selective interior demolition?', a: 'Yes, and it measures it room by room, because that is how it is performed, phased and billed in an occupied building. Partitions, ceilings, flooring, casework, fixtures and MEP removals are measured per room with the room reference retained.' },
    { q: 'Does it include protection and dust control?', a: 'Yes, as quantified scope: temporary partitions, floor and surface protection, dust barriers, negative air machines and path protection. On a fit-out inside an operating facility these frequently cost more than the demolition itself and are the most common omission.' },
    { q: 'How does it handle asbestos and lead?', a: 'By flagging them rather than absorbing them. Hazardous material locations from the survey are mapped against the affected areas, the abatement boundary is recorded, and the exclusion is written explicitly into the estimate. Abatement is licensed work and belongs in its own scope with its own price.' },
    { q: 'Does it estimate structural demolition?', a: 'Yes. Concrete, masonry, steel and slab removals are measured by volume and material, with shoring, temporary support and sequencing carried as costed scope. Those are engineering-driven items that appear in a bid as both cost and risk, and they should be visible.' },
    { q: 'Can it price recycling and waste diversion?', a: 'Yes. Waste streams are separated so diversion targets — common on LEED projects — carry their sorting labor, separate containers and documentation as line items rather than as an assumed inclusion.' },
    { q: 'Does it account for access and phasing?', a: 'Yes. Quantities group by phase, floor and access route, and productivity varies with access condition. Hand demolition on an upper floor with a single service elevator is a different operation from machine demolition at grade, and the estimate reflects that.' },
    { q: 'Can I use my own removal production rates?', a: 'Yes. Removal productivity by element type, material and access condition comes from your own completed work, with a starting base available for scope you have no history on.' },
    { q: 'Can BidcoreAI estimate the demolition package for me?', a: 'Yes. <a href="/takeoff-services">Professional takeoff and estimating services</a> are staffed by estimators working in this platform, returning removal quantities, a disposal summary in volume and tonnage, and a priced estimate with the exclusions written down.' },
  ],
  service: {
    h2: 'Demolition Takeoff and Estimating Services',
    body: 'Send the demolition plans and the hazardous materials survey and have the package measured for you — removals by element and room, disposal in volume and tonnage, container and haul counts, protection quantified and the abatement boundary written down.',
    href: '/takeoff-services',
    label: 'Takeoff &amp; Estimating Services',
  },
  related: [
    'earthwork-estimating-software',
    'sitework-estimating-software',
    'drywall-estimating-software',
    'flooring-estimating-software',
    'concrete-estimating-software',
    'construction-estimating-software',
    'quantity-takeoff-software',
    'construction-takeoff-software',
  ],
  cta: {
    h2: 'Count the Containers on a Job You Have Done',
    lead: 'Compare the debris tonnage and the haul count against what actually left the site.',
  },
},

/* ══════════════════ LANDSCAPING ══════════════════ */
{
  slug: 'landscaping-estimating-software',
  name: 'Landscaping Estimating Software',
  h1: 'Landscaping Estimating Software for Planting, Irrigation and Hardscape',
  title: 'Landscaping Estimating Software for Contractors | BidcoreAI',
  description: 'Landscape estimating software: plants counted from the schedule, soil and mulch by volume, irrigation by zone and head, hardscape by area and paver type.',
  keywords: 'landscaping estimating software, landscape takeoff software, irrigation estimating software, hardscape estimating software, planting takeoff software, landscape bid software',
  eyebrow: 'CSI Division 32 · Landscaping',
  eyebrowIcon: 'ic-star',
  heroLead: 'Landscape estimating software for landscape and site contractors. Plants counted by species and size from the planting schedule, soil amendment and mulch calculated by volume and depth, irrigation measured by zone, head and pipe, and hardscape measured by area, section and paver type.',
  pills: [
    { icon: 'ic-plus',   text: 'Plants from the schedule' },
    { icon: 'ic-db',     text: 'Soil and mulch by volume' },
    { icon: 'ic-filter', text: 'Irrigation by zone' },
  ],
  card: {
    eyebrow: 'What a landscape estimate needs',
    headline: 'Counts, volumes and maintenance',
    sub: 'The planting is a count; the soil beneath it is a volume; the warranty period is a cost',
    items: [
      'Plants by species, size and root condition',
      'Bed areas with soil and mulch volumes',
      'Irrigation zones, heads, pipe and controls',
      'Hardscape by area, section and material',
      'Establishment, maintenance and warranty',
    ],
  },
  intro: {
    eyebrow: 'What it is',
    h2: 'The Plant Schedule Is Only the First Page of the Bid',
    paras: [
      'Landscape estimating starts easily. The planting plan and plant schedule tell you what to count: trees by species and caliper, shrubs by size and container, groundcover by area and spacing. Counting them accurately is straightforward work. What is not straightforward is everything that has to exist before a plant goes in the ground and everything that has to happen after it does — soil preparation and amendment, bed excavation, drainage, staking, mulch, irrigation, establishment watering and the maintenance period that runs until the warranty ends.',
      'BidcoreAI counts the planting from the schedule and reconciles it against the plan, then measures the beds and lawns as areas so soil amendment, mulch and sod come out as real volumes at their specified depths. A four-inch mulch depth over an acre of beds is a substantial quantity that gets carried as a lump sum far more often than it gets measured.',
      'Irrigation is estimated by system rather than by area. Heads are counted by type and coverage, zones are counted from the valve schedule, mainline and lateral pipe are measured by size, and controllers, sensors, backflow prevention and wiring are counted individually. Where the design is performance-based, coverage is derived from the head spacing and the area rather than left as an allowance.',
      'Hardscape is measured the way a paving package is: by area and section, with base depth, bedding, edge restraint and jointing quantified by layer, and pavers, walls and steps counted or measured in the units they are bought in. And the maintenance and establishment period is priced as scope, since a twelve-month warranty with monthly visits is a labor commitment that outlasts every other trade on the project.',
    ],
  },
  measures: {
    eyebrow: 'Scope',
    icon: 'ic-star',
    h2: 'What the Software Takes Off on a Landscape Package',
    lead: 'Planting plan and schedule, irrigation plan, hardscape details and the Division 32 specification.',
    cards: [
      {
        icon: 'ic-plus', title: 'Planting',
        desc: 'Counted from the schedule by species and size, then reconciled against the plan.',
        items: ['Trees by species and caliper', 'Shrubs by size and container', 'Groundcover by area and spacing', 'Root condition — B&amp;B, container, bare'],
      },
      {
        icon: 'ic-db', title: 'Soil and Beds',
        desc: 'Bed areas measured so amendment and mulch come out as volumes at specified depth.',
        items: ['Bed areas and excavation depth', 'Topsoil, amendment and compost', 'Mulch by depth and type', 'Bed edging and separation'],
      },
      {
        icon: 'ic-layers', title: 'Lawns and Seeding',
        desc: 'Areas by treatment, with the preparation each one requires.',
        items: ['Sod by area and type', 'Seed, hydroseed and erosion mat', 'Fine grading and preparation', 'Fertiliser and soil testing'],
      },
      {
        icon: 'ic-filter', title: 'Irrigation',
        desc: 'Measured by zone, head and pipe rather than allowed for by area.',
        items: ['Heads by type and coverage', 'Zones and valve assemblies', 'Mainline and lateral by size', 'Controllers, sensors and backflow'],
      },
      {
        icon: 'ic-layout', title: 'Hardscape',
        desc: 'Measured by area and section, exactly like a paving package.',
        items: ['Pavers by type and pattern', 'Base, bedding and edge restraint', 'Seat walls, steps and columns', 'Site furnishings and features'],
      },
      {
        icon: 'ic-sched', title: 'Establishment and Maintenance',
        desc: 'Priced as scope, because the warranty period is a labor commitment.',
        items: ['Establishment watering', 'Maintenance visits by frequency', 'Warranty replacement allowance', 'Final acceptance requirements'],
      },
    ],
  },
  features: {
    eyebrow: 'Features',
    h2: 'Landscape Estimating Features',
    lead: 'Schedule-driven counts, volume-driven soils, zone-driven irrigation.',
    cards: [
      { icon: 'ic-sched',  title: 'Plant Schedule Extraction', desc: 'The plant schedule is read as structured data by species, size, quantity and root condition, then reconciled against the plan.' },
      { icon: 'ic-brain',  title: 'AI Symbol Counting', desc: 'Planting symbols counted across the plan by type, with mismatches against the schedule reported for checking.' },
      { icon: 'ic-db',     title: 'Soil and Mulch Volumes', desc: 'Bed areas and specified depths converted to cubic yards of amendment, topsoil and mulch rather than carried as a lump.' },
      { icon: 'ic-layers', title: 'Lawn Treatments', desc: 'Sod, seed, hydroseed and erosion control measured by area with their preparation and fertiliser quantities.' },
      { icon: 'ic-filter', title: 'Irrigation Takeoff', desc: 'Heads counted by type, zones from the valve schedule, pipe by size, and controls and backflow counted individually.' },
      { icon: 'ic-percent',title: 'Coverage Derivation', desc: 'Where irrigation is performance-specified, head counts are derived from spacing and area rather than left as an allowance.' },
      { icon: 'ic-layout', title: 'Hardscape Sections', desc: 'Paver areas carry their section so base, bedding, edge restraint and jointing quantify by layer automatically.' },
      { icon: 'ic-tool',   title: 'Planting Labor by Size', desc: 'Installation productivity by plant size and access, since a 4-inch caliper tree and a one-gallon shrub share nothing but a plan symbol.' },
      { icon: 'ic-sched',  title: 'Maintenance Period Pricing', desc: 'Establishment watering, maintenance visits and warranty replacement priced by frequency and duration.' },
      { icon: 'ic-report', title: 'Nursery Order Lists', desc: 'Plant lists by species, size and root condition exported in the format a nursery quotes from.' },
      { icon: 'ic-refresh',title: 'Revision Comparison', desc: 'A re-issued planting plan compared against the previous one so substitutions and added plants are flagged.' },
      { icon: 'ic-dl',     title: 'Excel Export', desc: 'Plant schedules, soil volumes, irrigation counts and priced estimates exported with sheet references.' },
    ],
  },
  csi: {
    h2: 'Landscape Spec Coverage',
    lead: 'Division 32 planting and irrigation, with the site interfaces alongside.',
    rows: [
      { n: '32 84 00', l: 'Planting irrigation' },
      { n: '32 91 00', l: 'Planting preparation' },
      { n: '32 91 13', l: 'Soil preparation' },
      { n: '32 91 19', l: 'Landscape grading' },
      { n: '32 92 00', l: 'Turf and grasses' },
      { n: '32 93 00', l: 'Plants' },
      { n: '32 94 00', l: 'Planting accessories' },
      { n: '32 14 00', l: 'Unit paving (hardscape)' },
      { n: '31 25 00', l: 'Erosion and sedimentation control (interface)' },
    ],
  },
  projectsLead: 'Campuses, commercial developments, municipal parks, multifamily and streetscapes.',
  workflow: {
    h2: 'How a Landscape Estimate Comes Together',
    lead: 'Count the plants, measure what they sit in, then price the year that follows.',
    steps: [
      { t: 'Upload planting and irrigation plans', s: 'Planting plan and schedule, irrigation plan and valve schedule, hardscape plans and details, and the Division 32 specification sections.' },
      { t: 'Plants counted and reconciled', s: 'The plant schedule is read as structured data and reconciled against symbols counted on the plan, with any mismatch reported for checking.' },
      { t: 'Beds and lawns measured', s: 'Bed and lawn areas are measured so soil amendment, topsoil, mulch, sod and seed quantify as volumes and areas at their specified depths.' },
      { t: 'Irrigation taken off', s: 'Heads counted by type, zones taken from the valve schedule, mainline and lateral pipe measured by size, and controls and backflow counted individually.' },
      { t: 'Hardscape measured by section', s: 'Paved areas carry their section, so pavers, base, bedding, edge restraint and jointing quantify by layer along with walls and steps.' },
      { t: 'Installation priced', s: 'Planting productivity by size and access, irrigation by head and trench, hardscape by area — each against your own crew rates.' },
      { t: 'Maintenance period added', s: 'Establishment watering, maintenance visits by frequency and the warranty replacement allowance are priced as their own scope through to final acceptance.' },
    ],
  },
  benefits: {
    eyebrow: 'Benefits',
    h2: 'What Changes on a Landscape Bid',
    lead: 'The invisible two thirds — soil, water and the warranty year — become quantities.',
    cards: [
      { icon: 'ic-db',     title: 'Soil and Mulch Measured', desc: 'Four inches of mulch over an acre of beds is a large volume. Calculating it from area and depth is the difference between a bid and a round number.' },
      { icon: 'ic-filter', title: 'Irrigation by Zone', desc: 'Counting heads, zones and pipe rather than allowing a per-square-foot figure is what makes an irrigation bid comparable to another one.' },
      { icon: 'ic-sched',  title: 'Maintenance Priced', desc: 'A twelve-month establishment period with monthly visits is a labor commitment that outlives the project. It belongs in the estimate as hours.' },
      { icon: 'ic-plus',   title: 'Schedule Reconciled', desc: 'Comparing the schedule against the plan symbols catches substitutions and quantity conflicts before they reach the nursery order.' },
      { icon: 'ic-tool',   title: 'Labor by Plant Size', desc: 'A 4-inch caliper tree with a crane pick and a one-gallon shrub are the same symbol and completely different costs.' },
      { icon: 'ic-report', title: 'Nursery-Ready Lists', desc: 'Plant lists by species, size and root condition in the format a nursery quotes from — usable during the bid, not after it.' },
    ],
  },
  why: {
    h2: 'Why Landscape Contractors Use BidcoreAI',
    lead: 'Because plants are the visible part and rarely the expensive part.',
    items: [
      { icon: 'ic-sched',  t: 'Schedules read structurally', s: 'Species, size, quantity and root condition parsed from the schedule and reconciled against counted symbols.' },
      { icon: 'ic-db',     t: 'Soil and mulch as volumes', s: 'Bed areas and specified depths converted to cubic yards rather than carried as an allowance.' },
      { icon: 'ic-filter', t: 'Irrigation counted', s: 'Heads, zones, valves and pipe measured individually, with coverage derived where the design is performance-based.' },
      { icon: 'ic-sched',  t: 'Warranty period costed', s: 'Establishment and maintenance visits priced by frequency and duration through to final acceptance.' },
      { icon: 'ic-cloud',  t: 'Browser-based', s: 'Measure and price from anywhere, with the marked-up planting plan on a tablet on site.' },
      { icon: 'ic-users',  t: 'Estimators available', s: 'Landscape packages can be measured for you through <a href="/takeoff-services">professional takeoff services</a>.' },
    ],
  },
  faqs: [
    { q: 'What is landscaping estimating software?', a: 'Landscape estimating software counts plants from the planting schedule, measures bed and lawn areas so soil amendment and mulch come out as volumes, takes off irrigation by zone, head and pipe, measures hardscape by section, and prices the establishment and maintenance period. The planting count is the easy part; the soil, water and warranty scope is where the cost sits.' },
    { q: 'How does it count plants?', a: 'The plant schedule is read as structured data — species, size, caliper, container or root condition and quantity — and reconciled against planting symbols counted on the plan. Mismatches are reported, which catches substitutions and quantity conflicts before they reach a nursery order.' },
    { q: 'Does it calculate soil and mulch quantities?', a: 'Yes, as volumes. Bed areas are measured and multiplied by the specified amendment and mulch depths to produce cubic yards, rather than carried as a lump sum. Mulch at four inches across a large planting area is a substantial quantity that is routinely under-carried.' },
    { q: 'Does it estimate irrigation?', a: 'Yes, by system. Heads are counted by type and coverage, zones come from the valve schedule, mainline and lateral pipe are measured by size, and controllers, sensors, backflow preventers and wiring are counted individually. Where the design is performance-specified, head counts are derived from spacing and area.' },
    { q: 'Can it handle hardscape?', a: 'Yes, measured the way a paving package is: paved areas carry their section, so pavers, aggregate base, bedding sand, edge restraint and jointing quantify by layer, with seat walls, steps, columns and site furnishings counted or measured separately.' },
    { q: 'Does it price the maintenance and warranty period?', a: 'Yes. Establishment watering, maintenance visits by frequency and duration, and a warranty replacement allowance are priced as their own scope through to final acceptance. A twelve-month establishment period is a labor commitment that outlasts every other trade on site.' },
    { q: 'Does planting labor vary by plant size?', a: 'Yes, substantially, and the estimate reflects it. A large caliper tree requiring a crane pick, a tree pit, staking and watering shares nothing but a plan symbol with a one-gallon shrub, and productivity is applied by size, root condition and site access.' },
    { q: 'Can it produce a nursery order list?', a: 'Yes. Plant lists export by species, size and root condition in the format a nursery quotes from, so material pricing can be obtained while the estimate is still being assembled rather than after the bid is submitted.' },
    { q: 'Can I use my own crew rates?', a: 'Yes. Planting, irrigation and hardscape productivity all come from your own history, with a starting base available for scope you have no data on.' },
    { q: 'Can BidcoreAI estimate the landscape package for me?', a: 'Yes. <a href="/takeoff-services">Professional takeoff and estimating services</a> are staffed by estimators working in this platform, returning reconciled plant counts, soil and mulch volumes, irrigation quantities and a priced estimate.' },
  ],
  service: {
    h2: 'Landscape Takeoff and Estimating Services',
    body: 'Send the planting, irrigation and hardscape plans with their schedules and have the package measured for you — plants reconciled against the schedule, soil and mulch as volumes, irrigation by zone and head, hardscape by section, and the maintenance period priced.',
    href: '/takeoff-services',
    label: 'Takeoff &amp; Estimating Services',
  },
  related: [
    'sitework-estimating-software',
    'earthwork-estimating-software',
    'concrete-estimating-software',
    'demolition-estimating-software',
    'construction-estimating-software',
    'quantity-takeoff-software',
    'construction-takeoff-software',
    'plumbing-estimating-software',
  ],
  cta: {
    h2: 'Price a Planting Plan End to End',
    lead: 'Compare the mulch volume, the irrigation head count and the maintenance hours against your last landscape bid.',
  },
},

];
