/**
 * Structural trades: concrete, masonry, structural steel, metal framing.
 *
 * What these four have in common is that the quantity is rarely what the plan
 * shows — concrete volume comes off the sections, rebar off the schedules,
 * steel off the shop-relevant section properties, framing off the wall types.
 * The copy leans on that, because it is the difference between a takeoff and
 * a square-foot guess.
 */
module.exports = [

/* ══════════════════ CONCRETE ══════════════════ */
{
  slug: 'concrete-estimating-software',
  name: 'Concrete Estimating Software',
  h1: 'Concrete Estimating Software for Volume, Rebar and Formwork',
  title: 'Concrete Estimating Software for Contractors | BidcoreAI',
  description: 'Concrete estimating software: cubic yards from the sections, rebar weight from the schedules, formwork by contact area, priced against your own cost data.',
  keywords: 'concrete estimating software, concrete takeoff software, rebar estimating software, formwork estimating software, cast in place concrete estimating, concrete cost estimating software',
  eyebrow: 'CSI Division 03 · Concrete',
  eyebrowIcon: 'ic-building',
  heroLead: 'AI concrete estimating software for concrete subcontractors, general contractors and civil builders. Volumes come off the structural sections rather than plan area, rebar is weighed from the bar schedules, and formwork is measured as square feet of contact area with the reuse assumption stated.',
  pills: [
    { icon: 'ic-db',    text: 'CY from the sections' },
    { icon: 'ic-chart', text: 'Rebar weighed, not ratioed' },
    { icon: 'ic-layout',text: 'SFCA formwork' },
  ],
  card: {
    eyebrow: 'What a concrete estimate needs',
    headline: 'Three quantities, done properly',
    sub: 'Volume, reinforcement and formwork — the last two are where concrete bids are won or lost',
    items: [
      'Cubic yards by element, mix and placement method',
      'Rebar tonnage by bar size from the schedules',
      'Formwork SFCA with a stated reuse count',
      'Placement labor by crew and pour method',
      'Finishing, curing and joint treatment separated',
    ],
  },
  intro: {
    eyebrow: 'What it is',
    h2: 'Why Concrete Is the Easiest Trade to Underbid',
    paras: [
      'A concrete estimate has three quantities, and only one of them is obvious. Cubic yards of concrete are easy to picture and comparatively easy to measure. Reinforcement and formwork are neither, and between them they usually carry more cost than the concrete itself. That is why so many concrete bids are lost on paper long before anything is poured: the yardage was right and the formwork was carried as a percentage.',
      'BidcoreAI measures all three from the structural drawings. Volumes come from the sections and details — footing sizes, slab thicknesses, wall dimensions, column schedules — not from plan area with an assumed depth. Reinforcement is calculated from the bar schedules by bar size and length, giving a real tonnage rather than a pounds-per-cubic-yard rule of thumb that varies by a factor of three between a slab on grade and a shear wall. Formwork is measured as square feet of contact area, element by element, with the reuse count carried as an explicit assumption rather than hidden inside a unit rate.',
      'Placement is priced by method and crew, because a pour reached by pump costs differently to one reached by crane or buggy, and a mat pour and a wall lift do not share a productivity rate. Finishing is priced against what the specification actually calls for — a burnished floor with a tight flatness class is not a broom finish with a different word in front of it.',
      'The result is an estimate that survives a scope conversation. When a general contractor asks why your number differs from the one next to it, you can show cubic yards by element, tonnage by bar size, contact area by form type and the reuse count you assumed — and find out in five minutes whether the gap is a scope difference or a pricing one.',
    ],
  },
  measures: {
    eyebrow: 'Scope',
    icon: 'ic-building',
    h2: 'What the Software Measures on a Concrete Package',
    lead: 'Measured from the structural set: plans, sections, details, column and bar schedules.',
    cards: [
      {
        icon: 'ic-building', title: 'Foundations',
        desc: 'Everything below the slab, measured from the sections rather than the foundation plan alone.',
        items: ['Spread and continuous footings', 'Grade beams and pile caps', 'Foundation and stem walls', 'Excavation and backfill interface'],
      },
      {
        icon: 'ic-layers', title: 'Slabs',
        desc: 'On grade and elevated, separated by thickness because thickness drives both volume and finishing crew.',
        items: ['Slab on grade by thickness', 'Elevated and topping slabs', 'Vapour barrier and sub-base', 'Metal deck interface quantities'],
      },
      {
        icon: 'ic-layout', title: 'Vertical Concrete',
        desc: 'Walls, columns and beams by section and lift height, which is what sets the forming cost.',
        items: ['Walls by thickness and height', 'Columns by section and lift', 'Beams and shear walls', 'Stairs, ramps and landings'],
      },
      {
        icon: 'ic-chart', title: 'Reinforcement',
        desc: 'Weighed from the bar schedules by size and length — never derived as a ratio of concrete volume.',
        items: ['Rebar tonnage by bar size', 'Bar schedules, laps and bend lists', 'Welded wire and fibre reinforcement', 'Dowels, chairs and accessories'],
      },
      {
        icon: 'ic-scan', title: 'Formwork',
        desc: 'Square feet of contact area by element type, with the reuse count recorded as an assumption.',
        items: ['SFCA by element type', 'Reuse and stripping cycles', 'Shoring and reshoring', 'Edge forms, bulkheads and blockouts'],
      },
      {
        icon: 'ic-calc', title: 'Placement and Finishing',
        desc: 'Priced by pour method and finish class, because both change the crew and the productivity rate.',
        items: ['Pump, crane or buggy placement', 'Finish type and flatness class', 'Curing, sealing and joint sawing', 'Embeds, anchor bolts and testing'],
      },
    ],
  },
  features: {
    eyebrow: 'Features',
    h2: 'Concrete Estimating Features',
    lead: 'Built around the three quantities and the two schedules that drive a concrete bid.',
    cards: [
      { icon: 'ic-brain',  title: 'AI Concrete Takeoff', desc: 'Footings, slabs, walls and columns detected across the structural set and proposed as measured quantities for review.' },
      { icon: 'ic-db',     title: 'Volume from Sections', desc: 'Thickness and depth taken from the sections and details, so a stepped footing or a thickened edge is not averaged away.' },
      { icon: 'ic-chart',  title: 'Rebar Weight Calculation', desc: 'Bar schedules read by size, length and count, with laps and bends included, returning tonnage by bar size.' },
      { icon: 'ic-scan',   title: 'Formwork Contact Area', desc: 'SFCA measured per element with form type and reuse count carried as explicit, editable assumptions.' },
      { icon: 'ic-users',  title: 'Placement Labor Models', desc: 'Crew-based productivity by pour type — mat, wall lift, elevated deck — rather than one blended rate for all concrete.' },
      { icon: 'ic-tool',   title: 'Equipment and Pumping', desc: 'Pump, crane time, buggies, vibrators and power trowels priced as their own lines instead of buried in a unit rate.' },
      { icon: 'ic-percent',title: 'Waste and Over-Pour', desc: 'Over-pour allowance applied per element type and shown as applied, because a footing and a slab do not waste alike.' },
      { icon: 'ic-sched',  title: 'Pour Sequencing', desc: 'Quantities grouped by pour, lift and phase, which is what makes the estimate usable as a plan rather than a total.' },
      { icon: 'ic-refresh',title: 'Revision Comparison', desc: 'A re-issued structural set is compared against the last one, so a slab thickness change shows up instead of hiding.' },
      { icon: 'ic-db',     title: 'Mix Design Pricing', desc: 'Different strengths, admixtures and aggregate specifications priced separately against your supplier pricing.' },
      { icon: 'ic-dl',     title: 'Excel Export', desc: 'Quantity sheets and priced estimates to Excel or CSV, with sheet references on every line.' },
      { icon: 'ic-file',   title: 'Bid-Ready Proposals', desc: 'A proposal drafted from the priced estimate with inclusions, exclusions and allowances carried across.' },
    ],
  },
  csi: {
    h2: 'Where a Concrete Estimate Lands in the Spec',
    lead: 'Output organised to current CSI MasterFormat sections and mapped to your own cost codes on request.',
    rows: [
      { n: '03 10 00', l: 'Concrete forming and accessories' },
      { n: '03 15 00', l: 'Concrete accessories — joints, embeds, waterstops' },
      { n: '03 20 00', l: 'Concrete reinforcing' },
      { n: '03 30 00', l: 'Cast-in-place concrete' },
      { n: '03 35 00', l: 'Concrete finishing' },
      { n: '03 39 00', l: 'Concrete curing' },
      { n: '03 41 00', l: 'Precast structural concrete' },
      { n: '03 45 00', l: 'Precast architectural concrete' },
      { n: '31 23 00', l: 'Excavation and fill (interface)' },
    ],
  },
  projectsLead: 'Foundations and structure for every building type — plus the civil work that surrounds them.',
  workflow: {
    h2: 'How a Concrete Estimate Comes Together',
    lead: 'Structural set in, priced concrete package out.',
    steps: [
      { t: 'Upload the structural set', s: 'Structural drawings, sections, details, column schedules and bar schedules, plus the specification sections for concrete, reinforcing and formwork.' },
      { t: 'The AI reads the schedules', s: 'Column schedules, bar schedules and slab designations are extracted and cross-referenced against the plans, with page citations for each.' },
      { t: 'Volumes measured from sections', s: 'Footings, slabs, walls and columns are measured with thickness and depth taken from the sections, and grouped by element type and mix design.' },
      { t: 'Reinforcement weighed', s: 'Bar quantities are calculated by size and length from the schedules, laps and bends included, and returned as tonnage by bar size for supplier pricing.' },
      { t: 'Formwork measured as SFCA', s: 'Contact area is measured per element with form type and reuse count set as assumptions you can change and see the effect of.' },
      { t: 'Priced against your costs', s: 'Concrete, reinforcement, formwork, placement, finishing and equipment priced from your own cost library or a regional benchmark, split by material, labor and equipment.' },
      { t: 'Delivered bid-ready', s: 'Excel estimate, marked-up structural drawings and a written basis of estimate listing assumptions, allowances and the RFIs worth issuing before bid day.' },
    ],
  },
  benefits: {
    eyebrow: 'Benefits',
    h2: 'What Changes on a Concrete Bid',
    lead: 'Mostly it changes what you can prove when the number is challenged.',
    cards: [
      { icon: 'ic-scan',   title: 'Formwork Priced, Not Assumed', desc: 'Contact area measured element by element replaces the percentage-of-pour habit — the single most common reason a concrete bid is 15% out in either direction.' },
      { icon: 'ic-chart',  title: 'Rebar You Can Buy From', desc: 'Tonnage by bar size is what a fabricator quotes against. A pounds-per-yard rule of thumb is not, and it is wrong in both directions depending on the element.' },
      { icon: 'ic-db',     title: 'Volumes That Match the Pour', desc: 'Measuring depth from the sections catches thickened edges, drop panels and stepped footings that plan-area estimating averages into nothing.' },
      { icon: 'ic-users',  title: 'Realistic Placement Labor', desc: 'Crew-based rates by pour type mean a job full of small wall lifts is not priced as though it were one big slab.' },
      { icon: 'ic-refresh',title: 'Addenda Handled', desc: 'When the structural set is re-issued, revision comparison shows the elements that changed rather than sending you back to the beginning.' },
      { icon: 'ic-check',  title: 'Assumptions in Writing', desc: 'Reuse counts, over-pour allowances and finish classes are stated in the basis of estimate, so a scope argument stays about scope.' },
    ],
  },
  why: {
    h2: 'Why Concrete Contractors Use BidcoreAI',
    lead: 'Because the three quantities that decide a concrete bid are each measured on their own terms.',
    items: [
      { icon: 'ic-layout', t: 'SFCA as a first-class quantity', s: 'Formwork is measured, not factored, with reuse recorded as an assumption you can test rather than a number buried in a rate.' },
      { icon: 'ic-chart',  t: 'Schedules read directly', s: 'Bar and column schedules are extracted and reconciled against the plans, which is where most reinforcement errors originate.' },
      { icon: 'ic-db',     t: 'Your supplier pricing', s: 'Mix designs, admixtures and reinforcement priced against your actual supplier quotes rather than a national average.' },
      { icon: 'ic-sched',  t: 'Grouped by pour', s: 'Quantities organised by pour and lift, so the estimate doubles as the start of a placement plan.' },
      { icon: 'ic-cloud',  t: 'Browser-based', s: 'No workstation licence. A superintendent can open the marked-up set on an iPad in a trailer.' },
      { icon: 'ic-users',  t: 'Estimators available', s: 'When four bids land in one week, <a href="/concrete-estimating-services">concrete estimating services</a> run in this same platform.' },
    ],
  },
  faqs: [
    { q: 'What is concrete estimating software?', a: 'Concrete estimating software measures and prices the three quantities a concrete package is built from: volume of concrete in cubic yards, weight of reinforcement in tons, and formwork in square feet of contact area. It then applies placement labor, finishing, curing and equipment costs to produce a priced estimate. Software that only measures volume is doing about a third of the job.' },
    { q: 'How does the software calculate concrete volume?', a: 'From the sections and details, not from plan area with an assumed depth. Footing sizes, slab thicknesses, wall dimensions and column sections are read off the structural drawings and schedules, so stepped footings, thickened edges and drop panels are measured as drawn rather than averaged into a single thickness.' },
    { q: 'How is rebar quantity calculated?', a: 'From the bar schedules — bar size, length, count, laps and bends — producing a tonnage by bar size that a fabricator can quote against. Deriving reinforcement as pounds per cubic yard is quick but unreliable: the ratio for a slab on grade and a shear wall differ by several times over.' },
    { q: 'Does it measure formwork?', a: 'Yes, as square feet of contact area by element type, which is how forming is actually priced. The reuse count is carried as an explicit assumption you can change, and it appears in the basis of estimate, so a reviewer can see whether the bid assumed four uses of a wall form or one.' },
    { q: 'Can it handle different mix designs?', a: 'Yes. Elements are grouped by specified strength, admixtures and aggregate requirements, and each group prices against its own supplier rate. This matters on projects where a 3,000 psi slab and a 6,000 psi column mix are both in the same package.' },
    { q: 'Does it price placement labor and pumping?', a: 'Yes, by pour method and crew rather than one blended rate. A pump pour, a crane-and-bucket lift and a buggy placement have different productivities and different equipment costs, and are priced separately. Vibrators, power trowels and pump time appear as their own lines.' },
    { q: 'Can I use my own concrete unit costs?', a: 'Yes, and you should. Import your historical unit costs for placement, forming and finishing, and your current supplier pricing for concrete and reinforcement. A regional benchmark is available for line items you have no history for, but your own numbers take precedence.' },
    { q: 'Can I export the concrete estimate to Excel?', a: 'Yes. Quantity sheets and priced estimates export to Excel or CSV with sheet references, and the measured structural set exports as a colour-coded marked-up PDF for review or for issuing with the bid.' },
    { q: 'Does it work for both concrete subcontractors and general contractors?', a: 'Both. A concrete subcontractor prices only the Division 03 scope in detail. A general contractor uses the same measurements to carry concrete in a whole-project estimate and to check the subcontractor quotes that come back against the scope that was actually sent out.' },
    { q: 'Can BidcoreAI estimate the concrete package for me?', a: 'Yes. <a href="/concrete-estimating-services">Concrete estimating services</a> are staffed by estimators working in this same platform. Send the structural set and you get back a priced estimate, a marked-up drawing set and a written basis of estimate, typically within 24 to 72 hours.' },
  ],
  service: {
    h2: 'Concrete Estimating Services',
    body: 'When the structural set arrives on Monday and the bid is due Thursday, the tool is not the constraint. Estimators working in this same platform will measure the volumes, weigh the reinforcement, measure the formwork and price the package — returning an Excel estimate, a marked-up structural set and a written basis of estimate.',
    href: '/concrete-estimating-services',
    label: 'Concrete Estimating Services',
  },
  related: [
    'masonry-estimating-software',
    'structural-steel-estimating-software',
    'earthwork-estimating-software',
    'metal-framing-estimating-software',
    'construction-estimating-software',
    'construction-takeoff-software',
    'quantity-takeoff-software',
    'demolition-estimating-software',
  ],
  cta: {
    h2: 'Price a Concrete Package You Already Know',
    lead: 'Bring a structural set you have bid. Compare the formwork contact area and the rebar tonnage against what you carried.',
  },
},

/* ══════════════════ MASONRY ══════════════════ */
{
  slug: 'masonry-estimating-software',
  name: 'Masonry Estimating Software',
  h1: 'Masonry Estimating Software for CMU, Brick and Stone',
  title: 'Masonry Estimating Software for Contractors | BidcoreAI',
  description: 'Masonry estimating software: CMU and brick unit counts by wall type, grout and reinforcement quantities, scaffold and labor priced from your own cost data.',
  keywords: 'masonry estimating software, cmu estimating software, brick estimating software, block takeoff software, masonry takeoff software, stone veneer estimating',
  eyebrow: 'CSI Division 04 · Masonry',
  eyebrowIcon: 'ic-layout',
  heroLead: 'Masonry estimating software for masonry subcontractors and general contractors. Wall areas measured by type and height, converted to unit counts at the right coursing, with grout, reinforcement, ties, lintels and scaffold priced as their own lines instead of loaded into a square-foot rate.',
  pills: [
    { icon: 'ic-layers', text: 'Units by coursing' },
    { icon: 'ic-db',     text: 'Grout and cell fill' },
    { icon: 'ic-tool',   text: 'Scaffold by height' },
  ],
  card: {
    eyebrow: 'What a masonry estimate needs',
    headline: 'Units, fill and access',
    sub: 'The wall area is the easy part — the cost sits in what goes inside the wall and how you reach it',
    items: [
      'Unit counts by size, coursing and wall type',
      'Grout volume by cell spacing and lift height',
      'Vertical and horizontal reinforcement',
      'Lintels, bond beams, ties and flashing',
      'Scaffold and access priced by wall height',
    ],
  },
  intro: {
    eyebrow: 'What it is',
    h2: 'Masonry Estimating Beyond Square Feet of Wall',
    paras: [
      'Masonry looks like the most straightforward trade to estimate — measure the wall, multiply by a rate — and that impression is exactly why it is so often mispriced. Two walls with identical square footage can differ by 40% in cost depending on unit size, coursing, how many cells are grouted, whether there is horizontal joint reinforcement every other course, how high the wall is, and whether it is a plain running bond or has three types of accent unit and a stone base.',
      'BidcoreAI measures masonry by wall type rather than by wall area alone. Each wall type carries its unit size, coursing, bond pattern and mortar joint, so a measured area converts to a real unit count instead of a nominal one. Openings are deducted by rule, jambs and returns are counted where they add cutting, and the wall height is retained because it drives both productivity and scaffold.',
      'The quantities that live inside the wall get measured on their own terms. Grout volume comes from cell spacing and lift height, not a blanket allowance. Vertical reinforcement is taken from the wall schedules by bar size and spacing. Bond beams, lintels, ties, anchors, flashing, weeps and control joints each appear as a line, because on a real project they add up to a meaningful share of the bid and they are the first things forgotten when a wall is priced as a rate per square foot.',
      'Access is treated as a cost, not an afterthought. Wall height determines whether the crew works off the ground, off frame scaffold or off a mast climber, and the estimate reflects the difference. So does the finish: split-face, ground-face, glazed and thin-veneer units each carry their own productivity and their own waste allowance.',
    ],
  },
  measures: {
    eyebrow: 'Scope',
    icon: 'ic-layout',
    h2: 'What the Software Measures on a Masonry Package',
    lead: 'Measured from the architectural and structural sets, plus the wall type and lintel schedules.',
    cards: [
      {
        icon: 'ic-layout', title: 'CMU Walls',
        desc: 'Concrete masonry measured by wall type, with unit size and coursing driving the count.',
        items: ['Wall area by type and thickness', 'Unit counts at specified coursing', 'Openings deducted, jambs counted', 'Wall height retained for productivity'],
      },
      {
        icon: 'ic-building', title: 'Brick and Veneer',
        desc: 'Face brick, thin brick and stone veneer counted at the specified bond and joint size.',
        items: ['Brick counts by bond pattern', 'Thin brick and adhered veneer SF', 'Stone veneer by type and coursing', 'Special shapes and accent bands'],
      },
      {
        icon: 'ic-db', title: 'Grout and Cell Fill',
        desc: 'Grout volume from cell spacing and lift height rather than an allowance per square foot.',
        items: ['Grouted cell volume by spacing', 'Bond beam and lintel fill', 'Lift heights and cleanout requirements', 'Mortar quantities by type'],
      },
      {
        icon: 'ic-chart', title: 'Reinforcement',
        desc: 'Vertical and horizontal steel from the wall schedules, by size and spacing.',
        items: ['Vertical bars by size and spacing', 'Horizontal joint reinforcement', 'Bond beam reinforcement', 'Dowels and starter bars'],
      },
      {
        icon: 'ic-pkg', title: 'Accessories and Embeds',
        desc: 'The items that never appear in a square-foot rate but always appear on the invoice.',
        items: ['Lintels, sills and bearing plates', 'Ties, anchors and veneer clips', 'Flashing, weeps and drainage mat', 'Control joints and sealant'],
      },
      {
        icon: 'ic-tool', title: 'Access and Labor',
        desc: 'Crew productivity by unit type and height, with the access method priced explicitly.',
        items: ['Scaffold, frame or mast climber', 'Productivity by unit and finish', 'Cutting, cleaning and pointing', 'Cold and hot weather protection'],
      },
    ],
  },
  features: {
    eyebrow: 'Features',
    h2: 'Masonry Estimating Features',
    lead: 'Wall types, coursing and access — the three things a generic area takeoff ignores.',
    cards: [
      { icon: 'ic-brain',  title: 'AI Wall Type Detection', desc: 'Wall types identified from plans and schedules, measured across every level and proposed for confirmation.' },
      { icon: 'ic-layers', title: 'Coursing Conversion', desc: 'Measured wall area converted to unit counts at the specified unit size, bond and joint thickness.' },
      { icon: 'ic-filter', title: 'Opening Deductions', desc: 'Openings deducted by rule with jamb and head conditions counted, because cutting around an opening is labor the area does not show.' },
      { icon: 'ic-db',     title: 'Grout Volume Calculation', desc: 'Cell fill computed from spacing, wall thickness and lift height, with bond beam and lintel fill separated.' },
      { icon: 'ic-chart',  title: 'Reinforcement Takeoff', desc: 'Vertical bars, joint reinforcement and bond beam steel taken from the wall schedules by size and spacing.' },
      { icon: 'ic-tool',   title: 'Scaffold and Access', desc: 'Access priced from wall height and elevation, so a two-storey lift is not carried at ground-level productivity.' },
      { icon: 'ic-users',  title: 'Crew Productivity Models', desc: 'Units per mason-day by unit type, size and finish — split-face and ground-face are not laid at the same rate.' },
      { icon: 'ic-percent',title: 'Waste and Breakage', desc: 'Waste factors per unit type, shown as applied, higher for veneer and special shapes than for standard block.' },
      { icon: 'ic-pkg',    title: 'Accessory Schedules', desc: 'Lintels, ties, flashing, weeps and control joints tracked as their own quantities against the schedules.' },
      { icon: 'ic-sched',  title: 'Phasing by Elevation', desc: 'Quantities grouped by elevation and level, matching how masonry is actually sequenced and billed.' },
      { icon: 'ic-dl',     title: 'Excel and Material Lists', desc: 'Unit counts, mortar, grout and accessories exported as a purchase-ready material summary.' },
      { icon: 'ic-refresh',title: 'Revision Comparison', desc: 'Re-issued elevations compared against the previous set so a changed wall type is flagged, not missed.' },
    ],
  },
  csi: {
    h2: 'Masonry Spec Coverage',
    lead: 'Output structured to the Division 04 sections your specification is written in.',
    rows: [
      { n: '04 05 00', l: 'Common work results for masonry — mortar and grout' },
      { n: '04 05 23', l: 'Masonry accessories — ties, anchors, joint reinforcement' },
      { n: '04 20 00', l: 'Unit masonry' },
      { n: '04 21 00', l: 'Clay unit masonry — brick' },
      { n: '04 22 00', l: 'Concrete unit masonry — CMU' },
      { n: '04 23 00', l: 'Glass unit masonry' },
      { n: '04 40 00', l: 'Stone assemblies' },
      { n: '04 43 00', l: 'Stone masonry and veneer' },
      { n: '05 50 00', l: 'Metal fabrications — lintels and bearing (interface)' },
    ],
  },
  projectsLead: 'Schools, warehouses, retail shells, healthcare and multifamily — wherever load-bearing block or veneer is the envelope.',
  workflow: {
    h2: 'How a Masonry Estimate Comes Together',
    lead: 'From elevations and wall schedules to a priced package with a material list attached.',
    steps: [
      { t: 'Upload plans, elevations and schedules', s: 'Architectural plans and elevations, structural wall schedules, lintel schedules and the Division 04 specification sections.' },
      { t: 'Wall types identified', s: 'The AI reads the wall type legend and schedules, then finds each wall type across the plans and elevations with the sheet reference retained.' },
      { t: 'Areas measured by type and height', s: 'Wall areas are measured per type with heights taken from the elevations and sections, openings deducted and jamb conditions counted.' },
      { t: 'Converted to unit counts', s: 'Areas convert to unit counts at the specified size, coursing and joint, and to mortar quantities, with waste applied per unit type and shown as applied.' },
      { t: 'Fill and reinforcement calculated', s: 'Grout volume comes from cell spacing and lift height; vertical bars, joint reinforcement and bond beam steel come from the wall schedules.' },
      { t: 'Access and labor priced', s: 'Scaffold or mast climber is priced from wall height, and laying productivity is applied by unit type, size and finish against your own crew rates.' },
      { t: 'Delivered as estimate and material list', s: 'A priced Excel estimate, a purchase-ready material summary of units, mortar, grout and accessories, and a marked-up drawing set behind every quantity.' },
    ],
  },
  benefits: {
    eyebrow: 'Benefits',
    h2: 'What Changes on a Masonry Bid',
    lead: 'Mostly, the things that were inside a square-foot rate come out where you can see them.',
    cards: [
      { icon: 'ic-layers', title: 'Real Unit Counts', desc: 'Counting at the specified coursing rather than a nominal rate per square foot is what makes a material order match what the crew actually lays.' },
      { icon: 'ic-db',     title: 'Grout Stops Being a Guess', desc: 'Cell fill calculated from spacing and lift height replaces the blanket allowance that is either quietly generous or quietly short on every job.' },
      { icon: 'ic-tool',   title: 'Access Priced Honestly', desc: 'Scaffold is a real cost that scales with height. Pricing it explicitly is what stops a tall elevation being bid at ground-floor productivity.' },
      { icon: 'ic-pkg',    title: 'Accessories Not Forgotten', desc: 'Lintels, ties, flashing and control joints tracked as quantities rather than remembered at the end, which is when they get missed.' },
      { icon: 'ic-users',  title: 'Productivity by Unit', desc: 'Split-face, ground-face and glazed units each carry their own rate, so a decorative elevation is not priced like a warehouse wall.' },
      { icon: 'ic-report', title: 'A Material List You Can Order From', desc: 'Units, mortar, grout and accessories in purchase quantities, ready to send to a supplier while the estimate is still being finished.' },
    ],
  },
  why: {
    h2: 'Why Masonry Contractors Use BidcoreAI',
    lead: 'Because masonry cost lives in the details a wall area cannot express.',
    items: [
      { icon: 'ic-layout', t: 'Wall types drive everything', s: 'Unit size, coursing, bond and finish are properties of the wall type, so the count and the productivity follow automatically.' },
      { icon: 'ic-db',     t: 'Fill measured, not allowed for', s: 'Grout comes from cell spacing and lift height. It is one of the largest hidden variances in masonry bidding.' },
      { icon: 'ic-tool',   t: 'Height is a cost input', s: 'Elevation heights feed scaffold and productivity directly rather than being noticed late in the estimate.' },
      { icon: 'ic-report', t: 'Purchase-ready output', s: 'Material summaries in order units — block, brick, mortar, grout, ties, lintels — for supplier pricing.' },
      { icon: 'ic-cloud',  t: 'Browser-based', s: 'Measure and price from anywhere, with no workstation licence and nothing to install.' },
      { icon: 'ic-users',  t: 'Estimators available', s: 'Masonry packages can be measured and priced for you through <a href="/takeoff-services">professional takeoff services</a> when volume spikes.' },
    ],
  },
  faqs: [
    { q: 'What is masonry estimating software?', a: 'Masonry estimating software measures wall areas by type and converts them into the quantities a masonry package is actually bought and built from: unit counts at the specified coursing, mortar and grout volumes, reinforcement, accessories, and the access needed to reach the work. Pricing wall area alone hides most of the cost variation between two walls of identical size.' },
    { q: 'How does it calculate CMU and brick counts?', a: 'Each wall type carries its unit size, bond pattern and mortar joint thickness, so measured area converts to a unit count at the real coursing rather than a nominal units-per-square-foot factor. Openings are deducted by rule and jamb conditions are counted, since cutting around an opening is labor the area alone does not show.' },
    { q: 'Does it calculate grout and cell fill?', a: 'Yes, from the specified cell spacing, wall thickness and lift height, with bond beam and lintel fill kept separate. Grout is one of the largest hidden variances in masonry bidding, and a blanket allowance per square foot is generous on some walls and short on others.' },
    { q: 'How is masonry reinforcement handled?', a: 'Vertical bars are taken from the wall schedules by size and spacing, horizontal joint reinforcement by course frequency, and bond beam steel by the schedule. All of it is reported by bar size, so a supplier can quote from it directly.' },
    { q: 'Does it account for scaffolding?', a: 'Yes. Wall height is retained from the elevations, and access — ground level, frame scaffold or mast climber — is priced as its own line. Laying productivity also varies with height, and the estimate applies the appropriate rate rather than one blended figure.' },
    { q: 'Can it handle stone and thin veneer?', a: 'Yes. Stone assemblies, adhered thin veneer and thin brick are measured with their own units, waste factors and productivity rates, including special shapes, accent bands and sills, which carry considerably more labor per square foot than field units.' },
    { q: 'Can it produce a material order list?', a: 'Yes. Unit counts, mortar, grout, ties, anchors, flashing and lintels export as a purchase-ready material summary in order quantities, which can go to a supplier for pricing while the estimate is still being assembled.' },
    { q: 'Can I use my own masonry unit costs?', a: 'Yes. Import your own laying rates, crew costs and supplier pricing, and the estimate prices against them. A regional benchmark database is available for items you have no history for.' },
    { q: 'Does it work for general contractors carrying masonry?', a: 'Yes. A general contractor uses the same measurements to carry masonry in a whole-project estimate and to check subcontractor quotes against the scope that was sent out — particularly whether a quote included grout, reinforcement and scaffold or excluded them.' },
    { q: 'Can BidcoreAI estimate the masonry package for me?', a: 'Yes. <a href="/takeoff-services">Professional takeoff and estimating services</a> are staffed by estimators working in this platform, returning measured quantities, a priced estimate and a marked-up drawing set, typically within 24 to 72 hours.' },
  ],
  service: {
    h2: 'Masonry Takeoff and Estimating Services',
    body: 'Send the elevations and wall schedules and have the package measured for you — unit counts by wall type, grout and reinforcement quantities, accessories and access — priced against your own rates and returned with the marked-up drawings behind every number.',
    href: '/takeoff-services',
    label: 'Takeoff &amp; Estimating Services',
  },
  related: [
    'concrete-estimating-software',
    'metal-framing-estimating-software',
    'structural-steel-estimating-software',
    'drywall-estimating-software',
    'painting-estimating-software',
    'construction-estimating-software',
    'quantity-takeoff-software',
    'construction-takeoff-software',
  ],
  cta: {
    h2: 'Try It on an Elevation You Have Bid',
    lead: 'Compare the unit count, the grout volume and the scaffold line against what you carried last time.',
  },
},

/* ══════════════════ STRUCTURAL STEEL ══════════════════ */
{
  slug: 'structural-steel-estimating-software',
  name: 'Structural Steel Estimating Software',
  h1: 'Structural Steel Estimating Software for Tonnage and Connections',
  title: 'Structural Steel Estimating Software | BidcoreAI',
  description: 'Structural steel estimating software: tonnage by section from the framing plans, connections counted, plus deck, joists, stairs and miscellaneous metals.',
  keywords: 'structural steel estimating software, steel takeoff software, steel estimating software, metal fabrication estimating, miscellaneous metals takeoff, steel tonnage software',
  eyebrow: 'CSI Division 05 · Metals',
  eyebrowIcon: 'ic-tool',
  heroLead: 'Structural steel estimating software for steel fabricators, erectors and general contractors. Members measured off the framing plans by section and length, converted to tonnage by weight per foot, with connections, deck, joists, stairs and miscellaneous metals counted as their own scope.',
  pills: [
    { icon: 'ic-chart', text: 'Tonnage by section' },
    { icon: 'ic-plus',  text: 'Connections counted' },
    { icon: 'ic-layers',text: 'Deck and joists' },
  ],
  card: {
    eyebrow: 'What a steel estimate needs',
    headline: 'Tonnage plus piece count',
    sub: 'Weight buys the material; piece count and connections buy the shop and field hours',
    items: [
      'Member lengths by section, converted to tons',
      'Piece counts — the real driver of shop labor',
      'Connection types counted from the details',
      'Metal deck, joists and girders by area and span',
      'Miscellaneous metals kept as their own package',
    ],
  },
  intro: {
    eyebrow: 'What it is',
    h2: 'Tonnage Is Not the Whole Steel Estimate',
    paras: [
      'Structural steel is priced two ways at once. The material is bought by weight, so tonnage matters. The fabrication and erection are driven by piece count and connection complexity, so a light frame made of many small members can cost more to build than a heavier one made of fewer long spans. An estimate that reports only tons has priced the mill order and guessed at the shop.',
      'BidcoreAI measures the framing plans member by member: section designation, length, level and grid location. Weight per foot converts those lengths to tonnage by section, so the estimate can be checked against a mill quote. At the same time the piece count is retained, and connections are counted from the typical details and the connection schedule — shear tabs, moment connections, base plates, stiffeners, bracing gussets — because they are what fills a shop.',
      'The rest of Division 05 is measured on its own terms rather than folded into a tons figure. Metal deck by type, gauge and area with side lap and end lap allowances. Open-web joists and girders by mark, span and depth from the joist schedule. Stairs, rails, ladders, embeds, bollards and lintels as a miscellaneous metals package, which on a fit-out or a parking structure is often larger than the frame itself.',
      'Finishes and treatment are separated as well. Shop primer, galvanising, intumescent and spray-applied fireproofing each carry their own cost per square foot of surface area, which does not track tonnage — a job full of small members has far more surface area per ton than one made of heavy sections, and pricing fireproofing by weight is how that difference gets missed.',
    ],
  },
  measures: {
    eyebrow: 'Scope',
    icon: 'ic-tool',
    h2: 'What the Software Measures on a Steel Package',
    lead: 'Framing plans, sections, connection details, joist and deck schedules, all read together.',
    cards: [
      {
        icon: 'ic-layout', title: 'Structural Framing',
        desc: 'Beams, columns and bracing measured by section and length across every framing level.',
        items: ['Beams and girders by section', 'Columns by section and lift', 'Bracing, struts and kickers', 'Length, level and grid retained'],
      },
      {
        icon: 'ic-chart', title: 'Tonnage Conversion',
        desc: 'Weight per foot applied by section designation to give tonnage a fabricator can quote against.',
        items: ['Tons by section designation', 'Grade and specification separated', 'Piece count retained alongside weight', 'Mill order summary by shape'],
      },
      {
        icon: 'ic-plus', title: 'Connections',
        desc: 'Counted from the typical details and the connection schedule, because they drive shop hours.',
        items: ['Shear and moment connections', 'Base plates and anchor rods', 'Stiffeners and doubler plates', 'Bracing gussets and splices'],
      },
      {
        icon: 'ic-layers', title: 'Metal Deck',
        desc: 'Decking by type, gauge and profile with lap allowances rather than a raw plan area.',
        items: ['Roof and floor deck by type', 'Gauge, depth and finish', 'Side lap and end lap allowance', 'Closures, pour stops and edge angle'],
      },
      {
        icon: 'ic-building', title: 'Joists and Girders',
        desc: 'Open-web joists taken from the joist schedule by mark, span and depth.',
        items: ['Joists by mark and span', 'Joist girders and headers', 'Bridging and bracing', 'Special loading conditions'],
      },
      {
        icon: 'ic-pkg', title: 'Miscellaneous Metals',
        desc: 'The Division 05 items that make up a whole package on fit-outs and parking structures.',
        items: ['Stairs, landings and rails', 'Ladders, grating and trench covers', 'Embeds, angles and lintels', 'Bollards and equipment supports'],
      },
    ],
  },
  features: {
    eyebrow: 'Features',
    h2: 'Structural Steel Estimating Features',
    lead: 'Built for the two numbers that actually price a steel package: tons and pieces.',
    cards: [
      { icon: 'ic-brain',  title: 'AI Framing Takeoff', desc: 'Members detected across the framing plans with section designation, length and grid position proposed for confirmation.' },
      { icon: 'ic-chart',  title: 'Weight per Foot Library', desc: 'Standard section weights applied automatically by designation, with grade and specification kept separate.' },
      { icon: 'ic-plus',   title: 'Connection Counting', desc: 'Connection types counted from typical details and schedules, so shop labor is priced from complexity rather than assumed from weight.' },
      { icon: 'ic-layers', title: 'Deck Takeoff with Laps', desc: 'Deck areas measured by type and gauge with side and end lap allowances applied and shown as applied.' },
      { icon: 'ic-sched',  title: 'Joist Schedule Reading', desc: 'Joist and girder marks, spans and depths extracted from the schedule and reconciled against the framing plans.' },
      { icon: 'ic-tool',   title: 'Miscellaneous Metals Package', desc: 'Stairs, rails, ladders, embeds and supports tracked as a separate package with their own units and rates.' },
      { icon: 'ic-percent',title: 'Surface Area for Coatings', desc: 'Painted, galvanised and fireproofed surface area calculated from section geometry rather than inferred from tonnage.' },
      { icon: 'ic-users',  title: 'Shop and Field Labor Split', desc: 'Fabrication and erection hours estimated separately, by piece count and connection type, against your own productivity data.' },
      { icon: 'ic-refresh',title: 'Revision Comparison', desc: 'A re-issued framing plan is compared against the previous one so a changed section size is flagged rather than missed.' },
      { icon: 'ic-report', title: 'Mill Order Summary', desc: 'Quantities summarised by shape and length for a mill or service centre quote, alongside the estimate itself.' },
      { icon: 'ic-dl',     title: 'Excel Export', desc: 'Member lists, tonnage summaries and priced estimates exported to Excel or CSV with sheet references intact.' },
      { icon: 'ic-calc',   title: 'Erection Equipment', desc: 'Crane time, lifts and access priced as their own lines rather than absorbed into a per-ton erection rate.' },
    ],
  },
  csi: {
    h2: 'Steel Spec Coverage',
    lead: 'Structured to Division 05, with the Division 03 and 09 interfaces kept visible.',
    rows: [
      { n: '05 12 00', l: 'Structural steel framing' },
      { n: '05 21 00', l: 'Steel joist framing' },
      { n: '05 31 00', l: 'Steel decking' },
      { n: '05 40 00', l: 'Cold-formed metal framing (interface)' },
      { n: '05 50 00', l: 'Metal fabrications' },
      { n: '05 51 00', l: 'Metal stairs' },
      { n: '05 52 00', l: 'Metal railings' },
      { n: '05 53 00', l: 'Metal gratings' },
      { n: '09 96 00', l: 'High-performance coatings and fireproofing (interface)' },
    ],
  },
  projectsLead: 'Frames, mezzanines, canopies and stair packages across commercial, industrial and institutional work.',
  workflow: {
    h2: 'How a Steel Estimate Comes Together',
    lead: 'Framing plans and schedules in; tonnage, piece count and a priced package out.',
    steps: [
      { t: 'Upload the structural set', s: 'Framing plans by level, sections, typical connection details, joist and deck schedules, and the Division 05 specification sections.' },
      { t: 'Members measured', s: 'Beams, columns and bracing are measured by section designation and length across every framing level, with grid position and level retained on each piece.' },
      { t: 'Converted to tonnage', s: 'Weight per foot is applied by section, producing tonnage by shape for a mill quote while the piece count is kept alongside it for shop pricing.' },
      { t: 'Connections counted', s: 'Connection types are counted from the typical details and the connection schedule — shear, moment, base plate, gusset — and priced by shop hours per type.' },
      { t: 'Deck, joists and misc measured', s: 'Deck areas with lap allowances, joists from the schedule by mark and span, and the miscellaneous metals package measured with its own units.' },
      { t: 'Coatings and fireproofing', s: 'Surface area is calculated from section geometry so primer, galvanising and fireproofing are priced per square foot rather than per ton.' },
      { t: 'Priced and delivered', s: 'Material, shop labor, erection labor and equipment priced against your own rates, exported to Excel with a mill order summary and a marked-up framing set.' },
    ],
  },
  benefits: {
    eyebrow: 'Benefits',
    h2: 'What Changes on a Steel Bid',
    lead: 'Chiefly, that the shop is priced from what the shop actually does.',
    cards: [
      { icon: 'ic-plus',   title: 'Piece Count Kept', desc: 'Fabrication hours track pieces and connections, not weight. Keeping both numbers is what stops a light, fussy frame being priced like a heavy simple one.' },
      { icon: 'ic-chart',  title: 'Tonnage a Mill Can Quote', desc: 'Summaries by shape, grade and length go straight to a service centre for pricing, instead of being reverse-engineered from a total.' },
      { icon: 'ic-percent',title: 'Coatings Priced by Area', desc: 'Fireproofing and galvanising follow surface area, which diverges sharply from tonnage on light framing. Calculating it properly removes a routine underbid.' },
      { icon: 'ic-pkg',    title: 'Misc Metals Not Lost', desc: 'Stairs, rails and embeds tracked as their own package rather than a lump allowance, which on a fit-out is often the larger half of the scope.' },
      { icon: 'ic-layers', title: 'Deck With Laps', desc: 'Lap allowances applied and visible means the deck order matches the deck installed, rather than arriving 6% short.' },
      { icon: 'ic-refresh',title: 'Design Changes Tracked', desc: 'A re-issued framing plan is compared against the last, so a section size change is a flagged difference instead of an expensive surprise.' },
    ],
  },
  why: {
    h2: 'Why Steel Estimators Use BidcoreAI',
    lead: 'Because a steel bid needs two quantities, and most tools only carry one.',
    items: [
      { icon: 'ic-chart',  t: 'Tons and pieces together', s: 'Both are measured and both are reported, so material pricing and shop pricing each get the number they need.' },
      { icon: 'ic-plus',   t: 'Connections as a quantity', s: 'Counted by type from the details, which is the closest available proxy for shop hours before detailing starts.' },
      { icon: 'ic-percent',t: 'Surface area calculated', s: 'Coatings and fireproofing priced from geometry rather than from a per-ton rule that flatters heavy frames.' },
      { icon: 'ic-pkg',    t: 'Misc metals as real scope', s: 'Stairs, rails, ladders and embeds measured properly instead of carried as an allowance and argued about later.' },
      { icon: 'ic-cloud',  t: 'Browser-based', s: 'No workstation licence, and the marked-up framing set opens on a tablet in the shop or on site.' },
      { icon: 'ic-users',  t: 'Estimators available', s: 'Steel packages can be measured and priced for you through <a href="/takeoff-services">professional takeoff services</a>.' },
    ],
  },
  faqs: [
    { q: 'What is structural steel estimating software?', a: 'It measures the steel frame off the structural drawings and turns it into the numbers a steel bid needs: tonnage by section for material pricing, piece count and connection types for shop labor, and separate quantities for deck, joists and miscellaneous metals. Reporting tons alone prices the mill order and leaves the fabrication cost to a guess.' },
    { q: 'How is steel tonnage calculated?', a: 'Members are measured by section designation and length off the framing plans, then converted using standard weight per foot for each shape. Tonnage is reported by shape and grade so it can be checked against a mill or service centre quote, with the piece count retained alongside it.' },
    { q: 'Why does piece count matter as well as tonnage?', a: 'Because fabrication cost tracks pieces and connections rather than weight. A frame made of many short, heavily connected members takes far more shop hours per ton than one made of long simple spans. Carrying both numbers is what lets shop labor be priced from complexity instead of assumed from weight.' },
    { q: 'Does it count connections?', a: 'Yes, by type, from the typical details and the connection schedule — shear tabs, moment connections, base plates, stiffeners and bracing gussets. Each type carries its own shop hours, which is the most reliable way to estimate fabrication before detailing has started.' },
    { q: 'Does it handle metal deck and joists?', a: 'Yes. Deck is measured by type, gauge and profile with side lap and end lap allowances applied and shown. Joists and joist girders are read from the joist schedule by mark, span and depth, and reconciled against the framing plans.' },
    { q: 'How are miscellaneous metals handled?', a: 'As their own package: stairs, landings, railings, ladders, grating, embeds, angles, lintels and bollards, each with its own unit and rate. On fit-outs and parking structures this package is frequently larger than the frame, and carrying it as a lump allowance is a common source of loss.' },
    { q: 'Can it estimate fireproofing and galvanising?', a: 'Yes. Surface area is calculated from section geometry rather than inferred from tonnage, because light framing has far more surface area per ton than heavy framing. Shop primer, galvanising, intumescent and spray-applied fireproofing are each priced per square foot of surface.' },
    { q: 'Can I export a mill order summary?', a: 'Yes. Quantities summarise by shape, grade and length for a service centre quote, and the full member list, tonnage summary and priced estimate export to Excel or CSV with sheet references on every line.' },
    { q: 'Does it price erection as well as fabrication?', a: 'Yes, separately. Erection is estimated from piece count, connection type and lift heights against your own crew productivity, with crane time and access equipment priced as their own lines rather than absorbed into a per-ton rate.' },
    { q: 'Can BidcoreAI estimate the steel package for me?', a: 'Yes. <a href="/takeoff-services">Professional takeoff and estimating services</a> are staffed by estimators working in this platform, returning a member list, tonnage summary, connection counts and a priced estimate with the marked-up framing set behind it.' },
  ],
  service: {
    h2: 'Steel Takeoff and Estimating Services',
    body: 'Send the framing plans, connection details and schedules, and have the package measured for you: member list by section, tonnage by shape, connection counts, deck and joists, and a miscellaneous metals package — priced against your own shop and field rates.',
    href: '/takeoff-services',
    label: 'Takeoff &amp; Estimating Services',
  },
  related: [
    'metal-framing-estimating-software',
    'concrete-estimating-software',
    'masonry-estimating-software',
    'roofing-estimating-software',
    'construction-estimating-software',
    'construction-takeoff-software',
    'quantity-takeoff-software',
    'fire-protection-estimating-software',
  ],
  cta: {
    h2: 'Run It Against a Frame You Have Priced',
    lead: 'Check the tonnage by shape and the connection count against the package you last sent to a mill.',
  },
},

/* ══════════════════ METAL FRAMING ══════════════════ */
{
  slug: 'metal-framing-estimating-software',
  name: 'Metal Framing Estimating Software',
  h1: 'Metal Framing Estimating Software for Studs, Track and Assemblies',
  title: 'Metal Framing Estimating Software | BidcoreAI',
  description: 'Metal stud framing estimating software: studs at spacing, track, headers and bracing measured by wall type, with drywall and insulation from one takeoff.',
  keywords: 'metal framing estimating software, metal stud takeoff software, light gauge framing estimating, stud and track takeoff, cold formed steel estimating software, framing estimating software',
  eyebrow: 'CSI Division 05 · Cold-formed framing',
  eyebrowIcon: 'ic-layout',
  heroLead: 'Metal framing estimating software for drywall and framing contractors. Partitions measured by wall type, converted to stud counts at the specified spacing, with track, headers, bracing, deflection connections and backing counted from the wall type legend and the details.',
  pills: [
    { icon: 'ic-layout', text: 'Studs at spacing' },
    { icon: 'ic-layers', text: 'Assemblies in one pass' },
    { icon: 'ic-tool',   text: 'Backing and bracing' },
  ],
  card: {
    eyebrow: 'What framing needs measured',
    headline: 'Wall types, not wall length',
    sub: 'Gauge, spacing, height and head condition change the cost of a foot of wall several times over',
    items: [
      'Stud counts at the specified spacing',
      'Top and bottom track by wall type',
      'Headers, jambs and opening framing',
      'Deflection track and slip connections',
      'Bridging, bracing and in-wall backing',
    ],
  },
  intro: {
    eyebrow: 'What it is',
    h2: 'A Foot of Wall Is Not a Unit of Cost',
    paras: [
      'Metal framing is measured in linear feet of wall and priced in something else entirely. A 10-foot-high 20-gauge shaft wall at 16 inches on centre with a deflection head and full-height bracing has almost nothing in common, cost-wise, with an 8-foot 25-gauge office partition at 24 inches on centre — yet a linear-foot rate treats them as the same product. That is the gap this software is built to close.',
      'BidcoreAI measures partitions by wall type. Each type carries its stud size, gauge, spacing, height and head condition from the wall type legend, so a measured length converts directly into stud counts, track lengths and the connection details that go with them. Openings generate their own framing — jambs, headers, sills and the extra studs a wide opening needs — rather than being deducted from the wall and forgotten.',
      'The items that make framing slow are counted too. Deflection track and slip connections at structural interfaces. Bridging and bracing rows by height. Backing for millwork, grab bars, TVs, handrails and equipment, taken from the interior elevations and details, which is the scope most often discovered on site rather than in the estimate. Fire-rated and acoustic assemblies carry their own detailing and their own labor.',
      'Because framing and drywall share the same walls, the same measurement produces both. One pass over the plan set yields the framing package and the board, tape, insulation and finish quantities — which is the practical reason drywall contractors end up doing the framing takeoff twice in most workflows, and why doing it once is worth this much attention.',
    ],
  },
  measures: {
    eyebrow: 'Scope',
    icon: 'ic-layout',
    h2: 'What the Software Measures on a Framing Package',
    lead: 'Read from the wall type legend, the floor plans, the interior elevations and the framing details.',
    cards: [
      {
        icon: 'ic-layout', title: 'Partitions by Type',
        desc: 'Wall lengths measured per wall type, with size, gauge, spacing and height taken from the legend.',
        items: ['Length by wall type and level', 'Stud size, gauge and spacing', 'Wall height and head condition', 'Rated and acoustic assemblies flagged'],
      },
      {
        icon: 'ic-plus', title: 'Stud and Track Counts',
        desc: 'Converted from length at the real spacing, with corners, intersections and ends counted.',
        items: ['Studs at 12, 16 or 24 inch centres', 'Top and bottom track by size', 'Corner, tee and end studs', 'Stud lengths by wall height'],
      },
      {
        icon: 'ic-file', title: 'Opening Framing',
        desc: 'Jambs, headers and sills generated from the door, window and borrowed-light openings.',
        items: ['Jamb studs by opening width', 'Headers and header depth', 'Sills and sub-sills', 'Extra studs at wide openings'],
      },
      {
        icon: 'ic-refresh', title: 'Deflection and Connections',
        desc: 'The structural interface details that decide how long a wall actually takes to build.',
        items: ['Deflection track and slip clips', 'Slotted track and vertical movement', 'Anchors and fasteners by substrate', 'Bracing to structure above'],
      },
      {
        icon: 'ic-tool', title: 'Bracing and Backing',
        desc: 'Bridging rows and in-wall backing taken from the details and interior elevations.',
        items: ['Bridging and bracing rows by height', 'Backing for millwork and equipment', 'Grab bar, TV and handrail backing', 'Blocking at mechanical penetrations'],
      },
      {
        icon: 'ic-layers', title: 'Ceilings and Soffits',
        desc: 'Suspended framing, furring and soffit framing measured as their own quantities.',
        items: ['Suspended ceiling framing', 'Soffit and bulkhead framing', 'Furring channels and hat channel', 'Shaft wall and chase framing'],
      },
    ],
  },
  features: {
    eyebrow: 'Features',
    h2: 'Metal Framing Estimating Features',
    lead: 'Wall types drive the quantities; the details drive the labor. Both are read.',
    cards: [
      { icon: 'ic-brain',  title: 'AI Wall Type Takeoff', desc: 'Wall types recognised from the legend and measured across every level, with lengths proposed for confirmation on the sheet.' },
      { icon: 'ic-plus',   title: 'Spacing Conversion', desc: 'Lengths converted to stud counts at 12, 16 or 24 inch centres, with corner, intersection and end studs counted properly.' },
      { icon: 'ic-layout', title: 'Height-Aware Quantities', desc: 'Stud lengths and bridging rows follow wall height from the sections, so a two-storey wall is not carried at 8 feet.' },
      { icon: 'ic-file',   title: 'Opening Framing Generation', desc: 'Jambs, headers and sills generated automatically from the door and window schedules and reconciled against the plans.' },
      { icon: 'ic-refresh',title: 'Deflection Detail Recognition', desc: 'Slip and deflection connections identified from the details, and priced as the labor item they are.' },
      { icon: 'ic-tool',   title: 'Backing from Elevations', desc: 'In-wall backing taken from interior elevations and details, which is where the scope hides until somebody hangs a grab bar.' },
      { icon: 'ic-layers', title: 'Assemblies to Drywall', desc: 'One measurement produces framing, board, tape, insulation and finish quantities, so the wall is measured once.' },
      { icon: 'ic-shield', title: 'Rated Assembly Tracking', desc: 'Fire and acoustic assemblies tracked by UL design number with their detailing requirements carried into labor.' },
      { icon: 'ic-percent',title: 'Waste Factors', desc: 'Applied per component — stud, track, channel — and shown as applied rather than folded into one blanket allowance.' },
      { icon: 'ic-report', title: 'Purchase Summaries', desc: 'Material lists in order units: sticks by length, track by bundle, screws by box, ready for a supplier quote.' },
      { icon: 'ic-dl',     title: 'Excel Export', desc: 'Quantity sheets and priced estimates to Excel or CSV with wall type and sheet reference on every line.' },
      { icon: 'ic-sched',  title: 'Phasing by Level', desc: 'Quantities grouped by level, zone or phase to match how framing is sequenced and billed on a multi-storey job.' },
    ],
  },
  csi: {
    h2: 'Framing Spec Coverage',
    lead: 'Division 05 40 00 and the Division 09 assemblies that sit on top of it.',
    rows: [
      { n: '05 40 00', l: 'Cold-formed metal framing' },
      { n: '05 41 00', l: 'Structural metal stud framing' },
      { n: '05 42 00', l: 'Cold-formed metal joist framing' },
      { n: '05 44 00', l: 'Cold-formed metal trusses' },
      { n: '09 21 16', l: 'Gypsum board assemblies' },
      { n: '09 22 16', l: 'Non-structural metal framing' },
      { n: '09 22 26', l: 'Suspension systems' },
      { n: '09 81 00', l: 'Acoustic insulation (interface)' },
      { n: '07 84 00', l: 'Firestopping (interface)' },
    ],
  },
  projectsLead: 'Interior build-outs, healthcare, hospitality, education and multifamily — anywhere the walls are stud and board.',
  workflow: {
    h2: 'How a Framing Estimate Comes Together',
    lead: 'Wall type legend first, then the plans, then the details nobody reads until they cost money.',
    steps: [
      { t: 'Upload plans, legend and details', s: 'Floor plans, the wall type legend, sections, interior elevations, framing details and the door and window schedules.' },
      { t: 'Wall types extracted', s: 'Each wall type is read from the legend with its stud size, gauge, spacing, rating and head condition, and stored as a property that quantities inherit.' },
      { t: 'Partitions measured by type', s: 'Wall lengths are measured per type across every level, with heights taken from the sections and each run tied to the sheet it came from.' },
      { t: 'Converted to components', s: 'Lengths convert to stud counts at the specified spacing, track lengths, and the corner, intersection and end studs the geometry requires.' },
      { t: 'Openings and details added', s: 'Jamb, header and sill framing is generated from the openings; deflection connections, bridging rows and backing come from the details and interior elevations.' },
      { t: 'Priced against your rates', s: 'Material and labor priced from your own cost library, with rated and high-wall assemblies carrying their own productivity rather than a single blended rate.' },
      { t: 'Framing and drywall together', s: 'The same measurement produces the board, tape, insulation and finish quantities, so the drywall estimate comes out of the same pass over the plan set.' },
    ],
  },
  benefits: {
    eyebrow: 'Benefits',
    h2: 'What Changes on a Framing Bid',
    lead: 'The wall stops being a linear foot and becomes what it actually is.',
    cards: [
      { icon: 'ic-layout', title: 'Wall Types Priced Correctly', desc: 'Gauge, spacing and height are carried per wall type, so a shaft wall and an office partition stop sharing a rate they never deserved.' },
      { icon: 'ic-tool',   title: 'Backing Gets Estimated', desc: 'In-wall backing taken from the interior elevations is scope that is otherwise discovered on site — at which point it is a change order you are paying for.' },
      { icon: 'ic-plus',   title: 'Openings Framed, Not Deducted', desc: 'Jambs and headers generated from the schedules mean a wall full of doors costs more than a blank one, which is the actual state of the world.' },
      { icon: 'ic-layers', title: 'One Pass, Two Estimates', desc: 'Framing and drywall from the same measurement removes a whole duplicate takeoff from every interior bid.' },
      { icon: 'ic-shield', title: 'Rated Assemblies Tracked', desc: 'UL assemblies carry their detailing and firestopping implications, so the rating is priced rather than assumed to be free.' },
      { icon: 'ic-report', title: 'Orders That Match', desc: 'Sticks by length and track by bundle means the delivery matches the wall, instead of arriving in a length the crew has to cut down.' },
    ],
  },
  why: {
    h2: 'Why Framing Contractors Use BidcoreAI',
    lead: 'Because the wall type legend is the most useful page in the set, and most tools ignore it.',
    items: [
      { icon: 'ic-layout', t: 'Wall types are the unit', s: 'Gauge, spacing, height and head condition are properties of the type, so quantities and productivity follow automatically.' },
      { icon: 'ic-layers', t: 'Framing and drywall together', s: 'One measurement produces both packages. Interior contractors bid both, and measuring twice is pure waste.' },
      { icon: 'ic-tool',   t: 'Details read, not skimmed', s: 'Deflection connections, bridging and backing are pulled from the details and elevations where the scope actually lives.' },
      { icon: 'ic-shield', t: 'Ratings carried through', s: 'Fire and acoustic assemblies keep their UL references, with the detailing labor priced rather than assumed.' },
      { icon: 'ic-cloud',  t: 'Browser-based', s: 'No workstation licence, and the marked-up plan set opens on a tablet in the field.' },
      { icon: 'ic-users',  t: 'Estimators available', s: 'Framing and drywall packages can be measured for you through <a href="/drywall-estimating-services">drywall estimating services</a>.' },
    ],
  },
  faqs: [
    { q: 'What is metal framing estimating software?', a: 'It measures partitions by wall type and converts them into the components a framing package is built from: studs at the specified spacing, top and bottom track, opening framing, deflection connections, bridging and backing. Pricing framing by linear foot of wall hides the differences in gauge, spacing, height and head condition that actually drive the cost.' },
    { q: 'How are stud counts calculated?', a: 'From measured wall length and the spacing carried on the wall type — 12, 16 or 24 inches on centre — with corner, intersection and end studs counted from the geometry rather than added as a percentage. Stud length follows the wall height taken from the sections.' },
    { q: 'Does it frame the openings?', a: 'Yes. Jamb studs, headers and sills are generated from the door, window and borrowed-light openings and reconciled against the schedules. Openings therefore add framing rather than simply deducting wall, which is how a corridor full of doors ends up costing more than a blank wall of the same length.' },
    { q: 'Does it account for deflection track and slip connections?', a: 'Yes. Head conditions are read from the wall type legend and the details, and deflection track, slotted track and slip clips are counted as their own items. They are a meaningful labor cost at every structural interface and are routinely left out of a linear-foot rate.' },
    { q: 'Can it take off in-wall backing?', a: 'Yes, from the interior elevations and details — backing for millwork, grab bars, handrails, wall-hung equipment and displays. This is the framing scope most often discovered during installation instead of during the estimate.' },
    { q: 'Does it handle drywall as well as framing?', a: 'Yes, from the same measurement. One pass over the plan set produces the framing package and the board, tape, insulation and finish quantities. See <a href="/software/drywall-estimating-software">drywall estimating software</a> for the finishing side.' },
    { q: 'Does it track fire-rated and acoustic assemblies?', a: 'Yes. Rated assemblies keep their UL design references, and the extra detailing they require — additional layers, firestopping, acoustic sealant, staggered studs — is carried into both the material list and the labor rate.' },
    { q: 'Can it produce a material order list?', a: 'Yes. Studs by length and gauge, track by bundle, channel, clips, fasteners and screws in order units, ready to send to a supplier while the estimate is still being assembled.' },
    { q: 'Can I use my own labor productivity rates?', a: 'Yes. Import your own crew rates and productivity by assembly type. High walls, rated assemblies and shaft walls each carry their own rate rather than a single blended figure, and the estimate prices against your history.' },
    { q: 'Can BidcoreAI estimate the framing package for me?', a: 'Yes — <a href="/drywall-estimating-services">drywall and framing estimating services</a> are staffed by estimators working in this platform, returning quantities, a priced estimate and a marked-up plan set with every wall type identified.' },
  ],
  service: {
    h2: 'Framing and Drywall Estimating Services',
    body: 'Send the plans and the wall type legend and have the interior package measured for you: partitions by type, stud and track counts, opening framing, backing and bracing, plus the board and finish quantities from the same pass — priced against your own rates.',
    href: '/drywall-estimating-services',
    label: 'Drywall &amp; Framing Estimating',
  },
  related: [
    'drywall-estimating-software',
    'structural-steel-estimating-software',
    'painting-estimating-software',
    'doors-hardware-estimating-software',
    'masonry-estimating-software',
    'construction-estimating-software',
    'quantity-takeoff-software',
    'construction-takeoff-software',
  ],
  cta: {
    h2: 'Measure an Interior Package Once',
    lead: 'Bring a floor plan with a wall type legend and see the framing and drywall quantities come out of the same pass.',
  },
},

];
